src/sys/mod.rs, test/sys/mod.rs
This is a continuation of #1336 which also enables the timerfd tests.
```
running 3 tests
test sys::test_timerfd::test_timerfd_unset ... ok
test sys::test_timerfd::test_timerfd_oneshot ... ok
test sys::test_timerfd::test_timerfd_interval ... ok
```
=> Allow Android to use timerfd

CHANGELOG.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
Test: `cargo test --test test test_ttl_opts`
=> Add IP_TTL/IPV6_UNICAST_HOPS SockOpts

src/unistd.rs
An edge case I found in another wrapper around `getgroups()`. @jhscheer pointed me to this implementation which had the same issue.
=> Prevent buffer over-read in getgroups()

CHANGELOG.md, src/sys/socket/addr.rs, src/sys/socket/mod.rs, test/sys/test_socket.rs
Fixes #1494
I went with making `sun_path` always nul-terminated since that just seems to make things easier, since (at least according to linux man pages) `sockaddr_un`s returned by the kernel will always be nul-terminated.
=> Rework UnixAddr to fix soundness issues

CHANGELOG.md, src/sys/mman.rs, test/sys/mod.rs, test/sys/test_mman.rs
This was an oversight from #1306.
Reported-by:	@ocadaruma
=> Actually connect the mman tests to the build

CHANGELOG.md, src/poll.rs, test/test_poll.rs
Test: `cargo test --test test test_pollfd_events`
=> Fix #411 - Provide accessors for 'events' in PollFd

src/sys/resource.rs
The current values causes the doc test to fail on Fedora 34 for unprivileged users. The values can be lowered without meaningfully changing the example.
Previously the example failed with EPERM.
=> Lower limits in setrlimit example

CHANGELOG.md, src/fcntl.rs, test/test_fcntl.rs
- `posix_fadvise(2)` does return error number directly (i.e. not through `errno`)
* refs: https://man7.org/linux/man-pages/man2/posix_fadvise.2.html , https://man7.org/linux/man-pages/man2/posix_fadvise.2.html
- However `posix_fadvise`-binding uses `Errno::result` to translate the error now, which is mis-use.
=> posix_fadvise doesn't return -1 as sentinel value

CHANGELOG.md, src/unistd.rs
=> Fix memory unsafety in unistd::getgrouplist

src/ifaddrs.rs, src/sys/socket/addr.rs
This reverts commit ed43d2c65e65dd68c9cf2dcf06f5ec45a44aaccd.
As discussed in #1544 the API of this function needs to change.  For
now, revert the PR that made it public, because it has not yet been
included in any release.
=> Revert "Expose SockAddr::from_raw_sockaddr"

Cargo.toml
…so it is possible to run checks on the crate again.
Fixup for 7a2fe9099fc226cf5010b450f473ca9a0db5bafc.
=> Include tests in the crate again

src/sys/signal.rs
This has previously been done for `killpg`, but not `kill` it seems.
=> Update doc comment to match type `Option<Signal>`

Cargo.toml, test/sys/test_aio.rs, test/sys/test_ptrace.rs, test/sys/test_select.rs, test/sys/test_signal.rs, test/sys/test_signalfd.rs, test/sys/test_termios.rs, test/sys/test_uio.rs, test/sys/test_wait.rs, test/test.rs, test/test_kmod/mod.rs, test/test_pty.rs, test/test_unistd.rs
The synchronization primitives in the standard library are not panic-safe, however the `parking_lot` crate provides drop-in replacement primitives which are.
Add the `parking_lot` crate as a dev dependency and update the tests to use it. This should make it easier to narrow down which test(s) in a group of tests are actually failing, since the entire group will no longer fail due to poisoning.
=> Avoid lock poisoning by using parking_lot

src/sys/memfd.rs, src/sys/mman.rs, src/sys/mod.rs
Added docs for `memfd_create`, `shm_open`, and `shm_unlink`, and some man-page and intra doc links.
=> Update `mman` related docs

.cirrus.yml, test/sys/test_uio.rs
This was an oversight from PR #1511.  Also, update the OSX test environment for Big Sur.  Big Sur is the first OSX version that supports preadv/pwritev
=> Test preadv and pwritev on more operating systems

Cargo.toml
This is a new feature in Cargo 1.56.0, currently in beta.  Once Nix's
MSRV is >= 1.56.0, this feature will prevent future problems like the
bitflags 1.3.0 fiasco.
Issue #1491
Issue #1510
Issue #1548
Issue #1555
=> Declare the MSRV in Cargo.toml

release.toml
`cargo release` is returning the following warning: `WARN  cargo_release::config] Negative config values are deprecated ('no_', 'disable_')`.
The root cause is `cargo-release` changing its behavior to default to not bumping the version: https://github.com/crate-ci/cargo-release/pull/340. Remove the `no-dev-version flag` from release.toml to match.
=> Fix warning when running cargo release

src/lib.rs
Remove use of `unsafe` in the implementation of `with_nix_path()` for `[u8]`. This also comes with a nice determinism win across input sizes, and is fairly performance neutral (slightly slower for small strings, much faster for large strings).
I suspect the performance degradation in the existing implementation is related to the following note in the `CStr::from_ptr()` documentation:
> Note: This operation is intended to be a 0-cost cast but it is currently implemented with an up-front calculation of the length of the string. This is not guaranteed to always be the case.
---
Tested with `cargo 1.57.0-nightly (7fbbf4e8f 2021-10-19)`, with variations of the following benchmarking code:
```rs
#[bench]
fn bench_with_nix_path_1024(b: &mut test::Bencher) {
let bytes = …
```
=> Remove unsafe in with_nix_path() for [u8]

src/time.rs
Nix has never supported a newlib target, but there were a few cfg checks
for it in our codebase.  Some of them were misspelled (newlibc vs
newlib), and some of the checks were wrong.  Removing them makes the
code much more readable.
=> Remove broken newlib support

CHANGELOG.md, Cargo.toml, src/unistd.rs, test/test_unistd.rs
Enable `fexecve()` on DragonFly, as it was added in the 6.0 release.
=> DragonFly 6.0 added fexecve(2)

CHANGELOG.md, src/sys/epoll.rs, test/sys/mod.rs
[Corresponding libc change](https://github.com/rust-lang/libc/commit/36be4cd4f65c326f2a30d3afee50db78c014f07f).
Enable the epoll tests on Android, because they are passing.
=> Recent versions of Android support EPOLLEXCLUSIVE

CHANGELOG.md, src/unistd.rs
These platforms stub out `fdatasync()` by just calling `fsync()`, but that is a conforming implementation.
DragonFly recently provided [an implementation](https://github.com/DragonFlyBSD/DragonFlyBSD/commit/74fa2560ac77f9db4a34b2a7c72450126fec4ed6), but it has not made it into a release or rust-lang/libc.
=> Add fdatasync for missing platforms

CHANGELOG.md, src/sched.rs, test/test.rs
Move `CpuSet`, `sched_getaffinity()`, and `sched_setaffinity()` from the `sched_linux_like` namespace to `sched_affinity`. Declare support for DragonFly BSD.
`test_sched_affinity()` passes locally on DragonFly BSD.
=> DragonFly BSD supports `sched_getaffinity()` and `sched_setaffinity()`

src/sys/aio.rs
Clippy added a lint for non-constructor methods which return `self`, encouraging them to be marked as `#[must_use]`.
Mark the methods which are failing with the latest nightly's clippy.
```
$ cargo clippy
warning: missing `#[must_use]` attribute on a method returning `Self`
--> src/sys/aio.rs:1068:5
|
1068 | /     pub fn emplace_slice(mut self, fd: RawFd, offs: off_t, buf: &'a [u8],
1069 | |                          prio: libc::c_int, sigev_notify: SigevNotify,
1070 | |                          opcode: LioOpcode) -> Self
1071 | |     {
...    |
1074 | |         self
1075 | |     }
| |_____^
|
= note: `#[warn(clippy::return_self_not_must_use)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#return_self_not_must_use
warning: …
```
=> Fix clippy warning by adding #[must_use]

CHANGELOG.md, src/sys/socket/addr.rs
* All sockaddr newtypes should be repr(transparent)
* All sockaddr newtypes should be opaque, so the user can't do something
like change the sa_family field in a way that violates invariants.
This is a prerequisite for #1544.
=> Improve the sockaddr interface:

test/test_stat.rs
Like FreeBSD, DragonFly does not support creating regular files (i.e. `S_IFREG`) with `mknod` or `mknodat`. These tests should be disabled as they always fail.
There are still a few other failing tests on DragonFly, but it is unclear to me if they are due to faulty/inapplicable test logic or a bug in DragonFly.
=> Disable mknod and mknodat tests on DragonFly

src/sys/resource.rs
In addition to existing resources, NetBSD supports `RLIMIT_MEMLOCK`, `RLIMIT_NPROC` and `RLIMIT_RSS`.
https://man.netbsd.org/setrlimit.2
`RLIMIT_AS` is also supported, but it looks like it was added [after version 5.0](https://mail-index.netbsd.org/tech-kern/2009/03/28/msg004702.html), so I'm not sure if that should be enabled.
=> Add NetBSD configuration for supported process resources

CHANGELOG.md, src/fcntl.rs, test/test_fcntl.rs
Enable the existing `posix_fallocate()` tests as they are passing locally.
=> Add posix_fallocate on DragonFly

CHANGELOG.md, src/mqueue.rs
With the existing code, if you call `mq_getattr()`, there does not appear to be a way to get any of the attributes from the returned `MqAttr` struct, other than the flags. This adds getter functions to retrieve the size parameters of the queue, and the current number of messages in the queue.
=> Added getters for the MqAttr struct

src/sys/socket/addr.rs, src/sys/socket/mod.rs
* Within UnixAddr, replace the path_len variable (length of the sun_path
field) with sun_len (length of the whole structure).  This is more
similar to how other sockaddr types work, and it's the same way that the
BSDs use the sun_len field.
Also, don't require that sun_path be nul-terminated. The OS doesn't
require it.
* On BSD-derived operating systems, struct sockaddr has a sa_len field
that holds the length of the structure.  UnixAddr's path_len field is
redundant.  Remove path_len on BSD-derived OSes, retaining it only for
Illumos and Linux-based OSes.
=> Refactor UnixAddr

Cargo.toml
f5ee22db489f78b9c003ef60b7ad1b837503bc4a removed the need for this dependency.
=> Remove cc dependency on DragonFly

CHANGELOG.md, src/sys/mod.rs, src/sys/signal.rs, src/sys/time.rs, src/sys/timer.rs, src/sys/timerfd.rs, test/test.rs, test/test_timer.rs
This commit adds support for the signal timer mechanism in POSIX, the mirror to timerfd on Linux. I wasn't _quite_ sure of how to fit into the project organization but hopefully this patch isn't too far off.
Resolves #1424
Signed-off-by: Brian L. Troutwine <brian@troutwine.us>
=> Introduce `timer_*` support 

test/test_timer.rs
The test was disabling the signal handler before disabling the timer.
Fix intermittent failures but reversing the cleanup order.
Also, speed up the timer to make the test suite complete faster.
=> Fix intermittency in test_timer::alarm_fires

test/test_mq.rs
NetBSD (and DragonFly, which borrows its implementation) include additional flags beyond O_NONBLOCK in MqAttr, such as the flags passed to mq_open(). Modify the mq tests to validate _at least_ the expected flags are set, but don't require strict equality on these platforms.
Verified these tests pass on DragonFly and NetBSD locally.
=> Fix mq tests on NetBSD and DragonFly

src/sys/mman.rs, test/sys/test_mman.rs
The previous documentation described the default behavior, rather than the behavior when the flag was set.
Also fix a test which is failing due to passing this flag erroneously.
=> Correct MAP_FIXED documentation for NetBSD

CHANGELOG.md, src/sys/mod.rs, src/sys/sendfile.rs, test/test.rs, test/test_sendfile.rs
The code is copied from the Mac OS and FreeBSD implementations.
=> Add sendfile(2) for DragonFly

test/sys/test_socket.rs
The socket tests request specific ports, and `test_timestamping` and `test_txtime` are currently conflicting in the port they request.
This leads to the second of the tests failing with `EADDRINUSE` when run locally.
=> Change port used by test_txtime to avoid conflict

.cirrus.yml, Cargo.lock.msrv
Reverts 0df82ded4704caf78c32df941c170cdacc9688dc and ac159d9c4e4165d74af25dc8b4913e6b7efe7272.
=> Re-enable deprecation warnings on DragonFly

CHANGELOG.md, Cargo.toml, src/sys/event.rs
It is not stable across OpenBSD versions and is reserved by the system on FreeBSD and NetBSD.
This should fix the nix build for OpenBSD, which is failing due to https://github.com/rust-lang/libc/pull/2596. Bump the libc dependency to uptake that change.
=> Remove EventFlag::EV_SYSFLAG

CHANGELOG.md, src/mount/linux.rs, src/sys/statfs.rs
Resolves #1631 and resolves  #1633.
=> Define UMOUNT_NOFOLLOW, FUSE_SUPER_MAGIC

CHANGELOG.md, src/sys/mman.rs
=> Add MAP_FIXED_NOREPLACE on Linux

.cirrus.yml, CHANGELOG.md, src/mqueue.rs, src/sys/ptrace/bsd.rs, test/test_mq.rs
* Better type safety for mqueue
* Suppress clippy::not_unsafe_ptr_arg_deref warnings in ptrace on BSD
=> Fix Clippy warnings on FreeBSD with the latest nightly

Cargo.toml
Only the socket feature depends on memoffset. Allow clients to skip pulling memoffset in as a dependency if they don't need it.
=> Make memoffset dependency optional

CHANGELOG.md, src/sys/socket/addr.rs
=> InetAddr::from_std should set sin_len/sin6_len on the BSDs

.cirrus.yml, README.md, bors.toml, src/sys/mod.rs, src/sys/personality.rs, src/sys/ptrace/linux.rs, src/sys/resource.rs, src/sys/signal.rs, src/sys/socket/addr.rs, src/sys/statfs.rs, src/sys/uio.rs, src/time.rs, test/sys/mod.rs, test/sys/test_aio_drop.rs, test/sys/test_uio.rs, test/test_fcntl.rs
uclibc is a libc alternative (peer to glibc and musl) which is used in low-resource embedded linux applications.
It's supported in rust as the `target_env` of several tier 3 targets, but `nix` currently doesn't build.  This patch provides a few customizations to get uclibc building.
To test:
* Get nightly rust
* Follow directions for getting a cross toolchain and env setup here: https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/platform-support/armv7-unknown-linux-uclibceabihf.md
Thanks for your consideration!
=> uclibc support

CHANGELOG.md, src/sys/socket/mod.rs
Expand accept4 support to more platforms.
=> Add accept4 on DragonFly, Emscripten, Fuchsia, Illumos, and NetBSD.

Cargo.toml
https://github.com/rust-lang/libc/pull/2543 was merged and is available
starting from 0.2.114.
Using published version of libc makes it easier to use git version of nix
=> use version of libc published on crates

CHANGELOG.md, src/sys/uio.rs
see https://github.com/rust-lang/libc/pull/1878
=> expose process_vm_readv, process_vm_writev for android

CHANGELOG.md, src/lib.rs
Added to libc by https://github.com/rust-lang/libc/commit/38569c719befeb5b5051caeb6b0ff628ccd0ff90
=> Enable uconxtext module for s390x

.gitignore, src/lib.rs
I've been digging into CPU instructions counts and found that `nix` accounted for an eye-watering 85% of my program's instruction counts (yes, I do a lot of I/O, I know).
The fix is simple: don't initialize the stack memory since we're just going to overwrite it anyway.
> Note: I also ran rustfmt in a separate commit, not sure if that's ok.
```
650,398,225 (85.05%) 5,451,056 (17.31%) 627,714,969 (97.28%) 60 ( 0.54%) 22 ( 0.07%) 3,997 (20.98%) 10 ( 0.18%) 0          752 ( 5.98%) 627,716,244 (97.30%) 267,333 (34.62%) 914,814 (35.11%) 105 ( 0.73%)  => /home/asaveau/Desktop/nix/src/lib.rs:<[u8] as nix::NixPath>::with_nix_path (152,469x)
```
```
1,677,159 ( 0.22%)       0          762,345 ( 0.12%) 14 ( 0.13%)  0           0          2 ( 0.04%) .           .                .          . …
```
=> 30x performance improvement in `with_nix_path`

CHANGELOG.md, src/pty.rs, test/test_pty.rs
align with std::fs::File which also does this because the underlying calls are just syscalls which are safe to run concurrently
=> also implement Read and Write for &PtyMaster

src/sys/termios.rs
This fixes the compilation [this](https://github.com/rtzoeller/nix/blob/1a2ee3da3026a14d42498f5ca4e4b2c1a75bc81d/src/sys/termios.rs#L27) example documentation on Android. Tested on Termux.
=> Define _POSIX_VDISABLE on Android to fix doc test

CHANGELOG.md, src/lib.rs
This PR removes the `PATH_MAX` limitation since that's wrong anyway: https://insanecoding.blogspot.com/2007/11/pathmax-simply-isnt.html
A nice side effect is that this lets us further optimize `with_nix_path` by having the compiler not insert probe frames, saving us another fat pile of instructions:
```
2,289,930 ( 1.67%) 305,324 ( 0.99%) 152,662 ( 0.74%) 18 ( 0.15%)  .            .          .          .           .           => ???:__rust_probestack (152,662x)
```
New numbers:
```
19,257,593 (16.43%) 4,415,242 (15.75%) 2,593,635 (12.82%) 41 ( 0.27%) 47 ( 0.12%) 53 ( 0.26%) 7 ( 0.12%) 0          3 ( 0.02%) 2,404,730 (14.52%) 2,721 ( 0.53%) 762,780 (30.96%)    66 ( 0.90%)  => /home/asaveau/Desktop/nix/src/lib.rs:<[u8] as nix::NixPath>::with_nix_path (152,556x)
```
```
Ir                 Dr …
```
=> Remove PATH_MAX restriction from with_nix_path and further improve performance

CHANGELOG.md, src/sys/socket/mod.rs
(I guess I will see if I did the cfg block correctly)
=> Add `MsgFlag::MSG_NOSIGNAL`

CHANGELOG.md, src/sys/wait.rs, test/sys/test_wait.rs
waitid() has a number of additional features that waitpid() is missing:
- WNOWAIT is only accepted for waitid() on Linux (and possibly other platforms)
- Support for waiting on PID file descriptors on Linux
For now support is added for all platforms with waitid() that have proper siginfo_t support in libc. NetBSD support is currently a work in progress [1].
Tests for the signal/exit code are currently skipped on MIPS platforms due to multiple bugs in qemu-user in the translation of siginfo_t (one fixed in January [2], one currently under review [3]).
[1] rust-lang/libc#2476
[2] https://lists.nongnu.org/archive/html/qemu-devel/2021-01/msg04810.html
[3] https://lists.nongnu.org/archive/html/qemu-devel/2021-10/msg05433.html
=> wait: implement waitid()

src/sys/socket/mod.rs
Link to cmsg_space macro for recvmmsg and recvmsg should
be the doc's root of crate as macro is an exported macro.
Signed-off-by: bin liu <liubin0329@gmail.com>
=> docs: fix link in doc for cmsg_space in sys/socket

CHANGELOG.md, src/sys/socket/addr.rs
The function assumed something about the values of the sockaddr_dl's
fields.  But because the inner type is public, we musn't do that.  The
only solution is to change the function's signature to return an Option.
=> Fix a panic in Linkaddr::addr

CHANGELOG.md, src/sys/resource.rs, test/test_resource.rs
=> Change getrlimit and setrlimit to use rlim_t directly.

CHANGELOG.md, src/sys/socket/addr.rs
This should've been done as part of #1675
=> Use the same signature for LinkAddr::addr on all platforms

Cargo.toml, src/sys/resource.rs, src/sys/signal.rs
- Redox renamed `sigaction.sa_handler` to `.sa_sigaction`, which lets us drop some specialized code for the platform.
- uclibc now uses a `u32` for the `RLIMIT` definitions, like Linux GNU.
=> Fix build for Redox and uclibc

CHANGELOG.md, src/ifaddrs.rs, src/lib.rs, src/sys/socket/addr.rs, src/sys/socket/mod.rs, test/sys/test_socket.rs, test/sys/test_sockopt.rs
The SockAddr enum is quite large, and the user must allocate space for
the whole thing even though he usually knows what type he needs.
Furthermore, thanks to the sa_family field, the sockaddr types are
basically an enum even in C.
So replace the ungainly enum with a SockaddrLike trait implemented by
all sockaddr types and  a SockaddrStorage union that has safe accessors.
Also, deprecate InetAddr, which only existed to support SockAddr.
Supplants #1504
Fixes #1544
=> Replace the Sockaddr enum with a union

CHANGELOG.md, src/sys/socket/addr.rs, src/sys/socket/mod.rs, test/sys/test_socket.rs
Because they're redundant with types in the standard library.
Fixes #1681
=> Deprecate IpAddr, Ipv4Addr, and Ipv6Addr

CHANGELOG.md, src/features.rs, src/sys/utsname.rs, test/common/mod.rs
Currently `uname` doesn't check for errors and just blindly assumes that it always succeeds. According to the manpage this function can fail, even though no actual errors are defined:
```
RETURN VALUE
Upon successful completion, a non-negative value shall be returned.  Otherwise, -1 shall be returned and errno set to indicate the error.
ERRORS
No errors are defined.
The following sections are informative.
```
Looking at [the glibc's sources](https://github.com/bminor/glibc/blob/b92a49359f33a461db080a33940d73f47c756126/posix/uname.c#L29) we can see that it indeed could fail if the internal `gethostname` call fails for some reason.
This code also assumes that every field of `utsname` is going to be initialized by the call to `uname`, which apparently is also not true. Even though the …
=> Make `uname` always safe

CHANGELOG.md, src/sys/statfs.rs
The statfs magic constants of file systems types are available on
target_os android and the cfg guard is updated accordingly.
Sync the list of constant with the constants declared in libc.
Fixes #1689
=> Enable statfs magic constants for target_os = "android"

CHANGELOG.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
IP_DONTFRAG: iOS, macOS
IPV6_DONTFRAG: android, iOS, linux and macOS
Test: `cargo test --test test dontfrag_opts`
Some CI tests running ENOPROTOOPT are disabled.
=> Add IP_DONTFRAG and IPV6_DONTFRAG SockOpts

CHANGELOG.md, src/fcntl.rs, src/mount/bsd.rs, src/sys/sendfile.rs, src/sys/socket/mod.rs, src/sys/uio.rs, test/sys/test_socket.rs, test/sys/test_uio.rs, test/test_fcntl.rs
As per discussion in #1637, the `IoVec<&[u8]>` and `IoVec<&mut [u8]>` types have been replaced with `std::io::IoSlice` and `IoSliceMut`, respectively. Notable changes made in this pull request include:
- The complete replacement of `IoVec` with `IoSlice*` types in both public API, private API, and tests.
- Replacing `IoVec` with `IoSlice` in docs.
- Replacing `&[IoVec<&mut [u8]>]` with `&mut [IoSliceMut]`, note that the slice requires a mutable reference now. This is how it's done in the standard library, and there might be a soundness issue in doing it the other way.
Resolves #1637
=> Replace the IoVec struct with IoSlice and IoSliceMut from the standard library

.cirrus.yml, Cargo.toml, src/lib.rs, src/sys/mod.rs, src/unistd.rs
features => feature
users => user
Neither of these features have yet been included in a release, so it's
ok to rename them.
=> Use singular number for all feature names

CHANGELOG.md, src/sys/socket/addr.rs
SockaddrLike::size() is meant to return the amount of space that can be
used to store the sockaddr.  But on Linux-based OSes, UnixAddr contains
an extra field to store the address's length.  This field is not part of
the address, and should not contribute to the value of size().
This bug can't cause an out-of-bounds write, and every OS that we test
on can tolerate the greater-than-expected length, but it might confuse
applications that implement functions similar to getsockname in
userland.
=> Fix UnixAddr::size on Linux and Android

Cargo.toml, src/mount/bsd.rs, test/common/mod.rs, test/sys/test_lio_listio_resubmit.rs
Upgrade sysctl dev-dependency to 0.4 and handle its breaking API changes.
=> Upgrade sysctl to 0.4

Cargo.toml
Don't change how the versions are specified (i.e. whether a patch version is listed).
parking_lot cannot be upgraded due to 0.12.0 bumping the MSRV to 1.49.
In many cases, nix was one of the only consumers of the current versions (i.e. we are late to upgrade).
=> Upgrade dev-dependencies to the latest versions

CHANGELOG.md, src/sys/socket/addr.rs, test/sys/test_socket.rs
=> Restore conversions from ip v4/6 Sockaddr types to std::net equivalents.

src/sys/statfs.rs
These constants are provided by Linux (linux/magic.h), not libc.
See rust-lang/libc#2639.
=> Define FsType constants for musl

src/sys/event.rs
FreeBSD 12 changes struct kevent.  For now, libc always binds to the
11-compat ABI.  But that will change some day.  Adjust Nix's code to
build with either struct definition.
=> Future-proof the kevent ABI

.cirrus.yml, Cargo.toml
This reverts commit 23f18dfc18929965c95e0bcbdb8731645f07e401.
libc v0.2.124 fixes the problem.
=> Revert "Pin nightly compiler used in CI for uclibc"

src/macros.rs, src/sys/socket/sockopt.rs
It just so happens that Redox doesn't use any of the libc_enum entries
that aren't followed by a comma.
=> Fix a warning on Redox with the latest nightly compiler.

.cirrus.yml, CHANGELOG.md, README.md, bors.toml, src/dir.rs, src/errno.rs, src/fcntl.rs, src/features.rs, src/net/if_.rs, src/sys/ioctl/mod.rs, src/sys/mman.rs, src/sys/mod.rs, src/sys/signal.rs, src/sys/socket/addr.rs, src/sys/socket/mod.rs, src/sys/socket/sockopt.rs, src/sys/stat.rs, src/sys/statvfs.rs, src/sys/termios.rs, src/sys/uio.rs, src/unistd.rs, test/sys/mod.rs, test/sys/test_uio.rs, test/sys/test_wait.rs, test/test.rs, test/test_dir.rs, test/test_net.rs, test/test_resource.rs, test/test_stat.rs, test/test_unistd.rs
hello,
the following changeset(s) adds support for compiling on haiku.
below is an sample run showing compilation
```sh
> uname -a
Haiku shredder 1 hrev56040 Apr 22 2022 06:24:48 x86_64 x86_64 Haiku
> cargo build
Compiling autocfg v1.1.0
Compiling libc v0.2.123
Compiling bitflags v1.3.2
Compiling cfg-if v1.0.0
Compiling memoffset v0.6.5
Compiling nix v0.24.1 (/boot/home/src/git/rust-libs/nix)
Finished dev [unoptimized + debuginfo] target(s) in 11.09s
```
and some results from running ```cargo test```:
```sh
running 32 tests
test sys::select::tests::fdset_clear ... ok
test sys::select::tests::fdset_insert ... ok
test sys::select::tests::fdset_highest ... ok
test sys::select::tests::fdset_fds ... ok
test sys::select::tests::fdset_remove ... ok
test sys::signal::tests::test_clear ... ok
test …
```
=> add haiku support

test/sys/test_uio.rs
`cargo +nightly clippy --tests` currently produces
```
warning: this let-binding has unit value
--> test/sys/test_uio.rs:256:20
|
256 |             loop { let _ = pause(); }
|                    ^^^^^^^^^^^^^^^^ help: omit the `let` binding: `pause();`
|
= note: `#[warn(clippy::let_unit_value)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_unit_value
```
=> Fix nightly clippy in tests

CHANGELOG.md, src/unistd.rs
Conversions to/from primitive uid_t and gid_t to newtype Uid and Gid types are valid and infallible, but are only implemented in one direction. This provides the counterparts in the other direction.
These conversions are identical in behavior to the from_raw methods. However, using the more idiomatic From trait enables easier interoperability with other crates (e.g., deserialization with serde)
=> Add From<uid_t> and From<gid_t>

src/macros.rs
Due to rust-lang/rust#97030, cargo test will fail to doctest macros unless they are exported, breaking the examples for `libc_bitflags!` and `libc_enum!`.
Adds `ignore` to the examples for these macros to stop tests from failing.
`cargo test` already fails on cargo 1.62.0-beta.2, and the above issue makes it seem unlikely that this will be changed on the Rust side. If rust-lang/rust#96630 *does* get reverted, this PR can be closed/unmerged, although the test wasn't running beforehand, and it might be worth making this explicit regardless.
=> Ignore doctests for unexported macros

CHANGELOG.md, src/sys/socket/addr.rs
This was an oversight from #1684.
Fixes #1728
=> Enable SockaddrStorage::{as_link_addr, as_link_addr_mut} on Linux.

test/test_unistd.rs
It has never actually executed its command, so the only reason that it
ever worked is that on most systems there are usually processes starting
and exiting all the time.
=> Fix the test_acct test

src/env.rs, src/fcntl.rs, src/lib.rs, src/net/if_.rs, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs, test/test_fcntl.rs
Remove obsolete references to target_env = wasi, target_os = nacl, target_os = osx, and a typo'd target_os = fushsia that didn't compile when fixed.
- target_env = wasi is dead: https://github.com/rust-lang/rust/pull/60117
- target_os = nacl is dead: https://github.com/rust-lang/rust/pull/45041
- target_os = osx is dead, but I can't find a link.
Found while exploring `--check-cfg`, as mentioned in #1734.
=> Cleanup cfg blocks

CHANGELOG.md, src/sys/socket/addr.rs
The `SockaddrLike::from_raw` implementations for `VsockAddr` and `SysControlAddr` were checking against the wrong address family constant. This PR makes them consistent with the values matched against in `SockaddrStorage::from_raw`.
=> Fix socket address family checks

CHANGELOG.md, src/poll.rs, test/test_poll.rs
ppoll(2) supports 'sigmask' as NULL. In that case no signal mask
manipulation is performed.
Let's make `sigmask` parameter of `nix::poll::ppoll` optional
to allow that behaviour.
Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>
=> ppoll: make sigmask parameter optional

src/unistd.rs
Some of the operations inside the pipe function are safe and should not be included inside an unsafe block.
=> Fix typo and minimise the use of `unsafe` blocks inside the `pipe` function

CHANGELOG.md, src/sys/resource.rs
Includes an enum to specify what to get resource usage for, and a new
struct that provides a more readable view into libc::rusage, including
using TimeVal for user and system CPU time.
Signed-off-by: Gustavo Noronha Silva <gustavo@noronha.dev.br>
=> Add getrusage wrapper

Cargo.toml, build.rs, src/dir.rs, src/sys/signal.rs, src/sys/timer.rs, src/sys/timerfd.rs, src/unistd.rs
Add the autocfg crate as a build dependency, and introduce `has_doc_alias` as a conditional compilation symbol.
Closes #1673.
=> Document aliases for functions like getuid()

CHANGELOG.md, README.md, src/unistd.rs
Changing `gethostname` to accept a buffer of `MaybeUninit` bytes allows the user to avoid needlessly initializing a buffer. This is a breaking API change.
=> Change gethostname to use a buffer of MaybeUninit values

CHANGELOG.md, src/sys/socket/sockopt.rs
I'm not sure, but according to [unix standard](https://pubs.opengroup.org/onlinepubs/7908799/xns/setsockopt.html), SO_DONTROUTE should appear in all unix systems.
Does this need a test?
=> Add missing DontRoute SockOpt

CHANGELOG.md, src/sys/time.rs
These are basically the same as From<libc::timespec> and
From<libc::timeval>, but they're const and require less typing.
=> Add const constructors for TimeSpec and TimeVal

CHANGELOG.md, src/sys/signal.rs
Currently,  the only way to create a `SigSet` from a `sigset_t` object
is by using pointer casts, like:
```
unsafe {
let sigset = *(&sigset as *const libc::sigset_t as *const SigSet)
};
```
This is un-ergonomic for library creators with interfaces to C.
So, let's add a new unsafe method that creates a `SigSet` from a 
`libc::sigset_t` object.
We can't implement `From` since converting from `libc::sigset_t` to
`SigSet` is unsafe, because objects of type `libc::sigset_t` must be
initialized by calling either `sigemptyset(3)` or `sigfillset(3)`
before being used. In other case, the results are undefined.
We can't implement `TryFrom` either, because there is no way to check
if an object of type `libc::sigset_t` is initialized.
Signed-off-by: German Maglione <gmaglione@redhat.com>
=> SigSet: A new unsafe helper method to create a SigSet from a sigset_t

src/unistd.rs
Based on the man page for `fchownat` and `lchown`, I have got the impression that with `FchownatFlags::NoFollowSymlink`, fchownat and lchown are identical. I couldn't find any documentation on `lchmod`.
=> Fix description of fchownat

.cirrus.yml, src/lib.rs, src/sys/socket/addr.rs, src/sys/socket/mod.rs
The major users of this function are functions like gethostname, which
will always properly align their buffers.  But out-of-crate consumers
could manually construct an unaligned buffer.  Handle that correctly.
Enable Clippy's cast_ptr_alignment lint.  It's disabled by default as it
reports many false positives, but it would've caught this problem.
Reported-by:	Miri
Fixes:		1769
=> Fix SockaddrLike::from_raw with unaligned inputs

CHANGELOG.md, src/sys/socket/mod.rs
Hi. I am working on a networking project that uses [packet sockets](https://man7.org/linux/man-pages/man7/packet.7.html) and noticed that ETH_P_ALL is not there in the `SockProtocol` enum. I thought it would be nice to have it here alongside IPPROTO_TCP and IPPROTO_UDP instead of having to separately import it from the libc crate.
=> Add ETH_P_ALL protocol number to SockProtocol

CHANGELOG.md, src/sys/mod.rs
Memory fds (`memfd`) are implemented and exported by Androids bionic.
Export the `memfd` module if the target os is `android`.
https://cs.android.com/android/platform/superproject/+/master:bionic/libc/include/sys/mman.h;drc=23c7543b8e608ebcbb38b952761b54bb56065577;bpv=1;bpt=1;l=182
=> Add memfd for target_os = "android"

CHANGELOG.md, src/sys/socket/mod.rs, src/sys/socket/sockopt.rs, test/sys/test_socket.rs
=> Add support for RecvOrigDstAddr on Linux

src/sys/signal.rs, src/sys/signalfd.rs, src/sys/termios.rs, test/sys/test_aio.rs, test/sys/test_epoll.rs, test/sys/test_socket.rs, test/sys/test_termios.rs, test/sys/test_uio.rs, test/sys/test_wait.rs, test/test_fcntl.rs, test/test_net.rs, test/test_stat.rs, test/test_time.rs, test/test_unistd.rs
https://rust-lang.github.io/rust-clippy/master/index.html#assertions_on_result_states
Fixes broken CI for https://github.com/nix-rust/nix/pull/1744
=> fix clippy assertions_on_result_states

Cargo.toml
This is the last version of libc which will support Rust 1.46, per https://github.com/rust-lang/libc/pull/2845.
I think we should ship nix 0.25.0 against this version of libc (at some point, not necessarily now), as it will allow us to maintain an MSRV of 1.46, and subsequently upgrade to a later libc immediately after releasing 0.25.0.
=> Upgrade libc to 0.2.127

CHANGELOG.md, src/unistd.rs, test/test_unistd.rs
This is a re-post of #1134, which seems to have been abandoned. Includes the changes requested in [this comment](https://github.com/nix-rust/nix/pull/1134#issuecomment-541346612).
=> Implement faccessat

.cirrus.yml
Serde accidentally raised its MSRV to 1.51.0 in a patch release.  They
don't intent to fix it. Nix uses Serde via cargo-hack in CI.  Disable it
so we can publish a final release at 1.46.0.
=> Disable cargo-hack in CI

src/unistd.rs
Passwords are hashed, not encrypted.
=> minor terminology fix in User docs

src/sched.rs, src/sys/personality.rs, src/sys/quota.rs, src/sys/socket/mod.rs, src/sys/socket/sockopt.rs, src/sys/termios.rs, src/sys/time.rs, src/unistd.rs, test/sys/test_pthread.rs, test/sys/test_ptrace.rs, test/test_dir.rs, test/test_pty.rs, test/test_stat.rs, test/test_unistd.rs
1. Convert `assert!(x == y)` to `assert_eq!(x, y)`
2. Convert `assert!(x != y)` to `assert_ne!(x, y)`
3. Add `.unwrap()` to unused `Result/Option` (in code comments)
4. Convert `std::ixx::MAX` to `ixx::MAX`
5. Convert `Box<Trait>` to `Box<dyn Trait>`
=> Remove deprecated items

CHANGELOG.md, src/sys/socket/mod.rs, test/sys/test_socket.rs
This control message is available on FreeBSD, NetBSD, and OpenBSD. When used with `sendmsg`, it sets the IPv4 source address. This adds support through a new `ControlMessage::Ipv4SendSrcAddr` variant that complements `ControlMessageOwned::Ipv4RecvDstAddr`.
A few notes:
* `IP_SENDSRCADDR` is actually just an alias for `IP_RECVDSTADDR` (though the code doesn't depend on this).
* On NetBSD, `IP_PKTINFO` can be used to accomplish the same thing and is already supported by nix. On FreeBSD and OpenBSD, though, `IP_SENDSRCADDR` is the only method I'm aware of.
* The accompanying test binds a UDP socket to all local interfaces (0.0.0.0). If this is not acceptable, please let me know; however, FreeBSD requires this to use `IP_SENDSRCADDR`.
I'll add a change-log entry once I see the PR number. …
=> Add support for the IP_SENDSRCADDR control message

src/fcntl.rs
=> feat #1733: add F_GET_SEALS and F_ADD_SEALS on FreeBSD

.cirrus.yml
But instead of building it from source, download pre-built binaries.
=> Reenable cargo-hack in CI

CHANGELOG.md, src/sys/time.rs
The implementation of `num_microseconds()` for `TimeSpec` returns the number of seconds not microseconds, as it divided by the wrong factor. The number of nanoseconds should be divided by 1000 to get the number of microseconds.
=> fix microsecond calculation for TimeSpec

Cargo.toml, build.rs, src/dir.rs, src/sys/signal.rs, src/sys/timer.rs, src/sys/timerfd.rs, src/unistd.rs
Remove the MSRV-related workaround added by #1693, since we now can use doc aliases in all supported versions of Rust.
Closes #1674.
=> Remove MSRV-related workaround for doc aliases

CHANGELOG.md, src/sys/termios.rs
Fixes https://github.com/nix-rust/nix/issues/1802
I have to admit I'm not really sure how to test this properly, so if that's necessary I require some help :)
=> Add `line` field to `Termios` struct

CHANGELOG.md, src/unistd.rs
Calling `unwrap` on the result of `CString::new` may cause the current thread to panic, which is a bit surprising undocumented behavior. It would be more reasonable to treat the erroneous name as a non-existing user or group.
=> Handle unacceptable name gracefully in {User,Group}::from_name

CHANGELOG.md, src/sys/memfd.rs, src/sys/mod.rs
=> expose memfd on freebsd

CHANGELOG.md, src/sys/utsname.rs
=> fix issue1814 add domainname field of utsname on android and linux

CHANGELOG.md, src/unistd.rs
crash on my Android phone because `pw.pw_passwd == NULL`
=> fix bugs on android armv7, because `pw.pw_passwd.is_null()`

Cargo.toml
Bump `libc` so that `setgrent/getgrent/endgrent` are available on fuchsia, and thus the CI failure in #1820 will be resolved
=> bump libc to 0.2.133

CHANGELOG.md, Cargo.toml, src/sys/statfs.rs
Namespace filesystem magic is missing from FsType constants.
=> statfs: add namespace fs magic

CHANGELOG.md, src/sys/resource.rs
=> re-export RLIM_INFINITY from libc

src/dir.rs, src/errno.rs, src/sys/pthread.rs, src/sys/socket/addr.rs, src/sys/socket/mod.rs, src/sys/socket/sockopt.rs, src/sys/statfs.rs, src/sys/sysinfo.rs, src/sys/termios.rs, src/sys/time.rs, src/sys/uio.rs, test/sys/test_ioctl.rs, test/sys/test_stat.rs, test/test_mount.rs
Clippy is now smarter about detecting unnecessary casts and useless conversions, which means we need to be more explicit about when the conversions are needed for a subset of platforms.
Required changes found by repeatedly running the following command against a list of the supported platforms.
`xargs -t -I {} sh -c "cargo clippy -Zbuild-std --target {} --all-targets -- -D warnings || exit 255"`
I removed the casts it complained about, and then restored them with an `#[allow]` if a later target needed the cast.
=> Fix clippy warnings on nightly

CHANGELOG.md, src/unistd.rs
Fixes #1818 
Change has not been added to `CHANGELOG.md`, will add it when #1831 is merged, or there will be a merge conflict
=> add syncfs on linux

Cargo.toml
We were previously stuck on 0.11 for MSRV reasons, but since bumping nix's MSRV to Rust 1.56 this is no longer the case.
=> Upgrade parking_lot dev-dependency to 0.12

CHANGELOG.md, Cargo.toml, src/unistd.rs
This binding has been added in [libc#2953](https://github.com/rust-lang/libc/pull/2953)
=> add faccessat on illumos

src/unistd.rs
Extremely minor one, but I found it by chance so why not open a PR :)
=> Fix typo: remove unnecessary verb from doc comment of `dup`

CHANGELOG.md, src/unistd.rs, test/test_unistd.rs
* [FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=eaccess&sektion=2&n=1)
* [DragonFly](https://man.dragonflybsd.org/?command=access&section=2)
* [Linux](https://man7.org/linux/man-pages/man3/euidaccess.3.html)
IMHO, `eaccess` uses effective identifiers to perform the permission check while `access/faccessat` use real IDs.
Fixes #1373
=> add eaccess on freebsd, dragonfly and linux

src/sys/statfs.rs
=> add XFS_SUPER_NUMBER to nix::sys::statfs

CHANGELOG.md, src/sys/socket/mod.rs, test/sys/test_socket.rs
Motivation is explained in #1602, new version allows to receive data without performing allocations inside the receive loop and to use received data without extra copying.
This pull request contains a breaking change to API `recvmmsg` (obviously) and also affects `recvmsg` - new version does not set length of control message buffer if one is passed. Later change can be avoided with a bit more copy-paste.
Fixes #1602
=> reimplement sendmmsg/recvmmsg with better API

CHANGELOG.md, src/errno.rs
@rtzoeller It's been quite a few releases since these have been deprecated, more bloat removal.
=> Nuke deprecated Errno flags

src/sys/stat.rs
Adds rustdoc to the `sys::stat::Mode` bit flags.
=> Mode flag documentation

Cargo.toml, src/sys/socket/addr.rs
* Make ipv4addr_to_libc const
* Use mem::transmute in ipv4addr_to_libc and ipv6addr_to_libc
Fixes #1687
Fixes #1688
=> Misc internal optimizations

CHANGELOG.md, src/sys/mman.rs, test/sys/test_mman.rs
When calling [`mmap`](https://man7.org/linux/man-pages/man2/mmap.2.html) the passed length needs to be greater than zero, else an  error is returned:
> EINVAL (since Linux 2.6.12) length was 0.
By specifying the argument as `std::num::NonZeroUsize` we eliminate this error case.
=> mmap non-zero length

CHANGELOG.md, src/sys/socket/addr.rs, test/sys/test_socket.rs
This adds the following 2 functions/methods: `UnixAddr::new_unnamed` and `UnixAddr::is_unnamed`.
Closes #1585
unix(7) on Linux:
> unnamed: A stream socket that has not been bound to a pathname using bind(2) has no name. Likewise, the two sockets created by socketpair(2) are unnamed. When the address of an unnamed socket is returned, its length is `sizeof(sa_family_t)`, and `sun_path` should not be inspected.
**Edit:** This currently isn't working on BSD, but I see why. Will fix it shortly.
=> Add better support for unnamed unix socket addrs

src/sys/socket/addr.rs
Use it in the from_sockaddr_un_abstract_unnamed test.  That test and this method were introduced by PRs #1871 and #1857, which crossed each other.
=> Use the new UnixAddr::new_unnamed in the unit tests

CHANGELOG.md, src/sys/socket/mod.rs
Hey, I wanna to make call like `socket(af_type, SOCK_RAW, IPPROTO_RAW)` but currently there is no way to do it with rust
https://github.com/rickettm/SendIP/blob/aad12a001157489ab9053c8665e09aec24a2ff6d/sendip.c#L143
Update: Feel free to add `#[cfg]` attribute if I made mistakes that might cause errors on some platforms
=> SockProtocol::Raw = libc::IPPROTO_RAW for raw sockets

CHANGELOG.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
Resolves https://github.com/nix-rust/nix/issues/1864
=> Add IpMtu sockopt

src/sys/time.rs
In a future release of the `libc` crate, `libc::timespec` will contain private padding fields on `*-linux-musl` targets and so the struct will no longer be able to be created using the literal initialization syntax.
Update places where `libc::timespec` is created to first zero initialize the value and then update the `tv_sec` and `tv_nsec` fields manually. Many of these places are in `const fn`s so a helper function `zero_init_timespec()` is introduced to help with this as `std::mem::MaybeUninit::zeroed()` is not a `const` function.
Some matches on `libc::timespec` are also updated to include a trailing `..` pattern which works when `libc::timespec` has additional, private fields as well as when it does not (like for
`x86_64-unknown-linux-gnu`).
See also …
=> Update use of libc::timespec to prepare for future libc version

CHANGELOG.md, src/poll.rs
Adds `poll::PollFd::any()` and `poll::PollFd::all()` functions which returns if any/all of the events of interest occurred in the last call to `poll` or `ppoll`.
Consider the case:
```rust
let (first_fd, second_fd) = /* ... */;
let mut poll_fds = [
poll::PollFd::new(interrupt_fd, poll::PollFlags::POLLIN),
poll::PollFd::new(transfer_fd, poll::PollFlags::POLLIN),
];
let _ = poll::poll(&mut poll_fds, -1)?;
let first = poll_fds[0].revents()? != poll::PollFlags::empty();
let second = poll_fds[1].revents()? != poll::PollFlags::empty();;
if first { /* ... */ }
if second { /* ... */ }
```
which can now be reduced:
```rust
let (first_fd, second_fd) = /* ... */;
let mut poll_fds = [
poll::PollFd::new(interrupt_fd, poll::PollFlags::POLLIN),
poll::PollFd::new(transfer_fd, poll::PollFlags::POLLIN),
]; …
```
=> PollFd utility functions

CHANGELOG.md, src/ifaddrs.rs
=> Workaround XNU bug in getifaddrs netmasks

CHANGELOG.md
I opted to preserve explicit entries for backports in both the original feature release and the backported point release, rather than trying to pretend that the releases were actually sequential.
Also, remove some empty subsections from the file.
=> [skip ci] add CHANGELOG entries for old point releases.

CHANGELOG.md, src/sys/socket/mod.rs, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
When reading a value into an enum from getsockopt, we must validate it. Failing to do so can lead to UB for example with SOCK_PACKET on Linux.
Perform the validation in GetSockOpt::get.  Currently SockType is the only type that requires validation.
Fixes #1819
=> Fix UB in the SO_TYPE sockopt

CHANGELOG.md, src/sys/socket/addr.rs, src/sys/socket/mod.rs
This is a small change to add the routing socket type to the list of socket types one can open with `nix`. I've added a smoke test to see that a socket of such type can actually be opened, but I'm not sure if such a test belongs in the codebase here.
=> Add routing socket type on macOS

CHANGELOG.md, src/sys/uio.rs
A release cycle went by... it's be nice to remove some bloat.
Closes https://github.com/nix-rust/nix/issues/1647, closes https://github.com/nix-rust/nix/issues/1371, closes https://github.com/nix-rust/nix/issues/305
=> Nuke IoVec

CHANGELOG.md, Cargo.toml, src/lib.rs
Untested, but I saw https://github.com/rust-lang/libc/commit/fd32da6e7dfa2afcae86e176904244cf45a90c06 and figured we should uptake it.
=> Enable ucontext module on aarch64-unknown-linux-gnu

.cirrus.yml, README.md
And promote aarch64-unknown-darwin to Tier 1.  Because that's what Cirrus CI is doing.
Fixes #1904
=> Drop x86_64-unknown-darwin to Tier 2

src/sys/mman.rs, src/sys/socket/addr.rs, src/sys/socket/sockopt.rs
Extracted from https://github.com/nix-rust/nix/pull/1862
=> More annoying formatting changes

src/sys/statfs.rs, test/test_fcntl.rs
1. Adds I/O safety for module `sys/statfs`. 
This PR is pretty small as all we need to do is to change the interface of `fstatfs(2)`:
from:
```rust
pub fn fstatfs<T: AsRawFd>(fd: &T) -> Result<Statfs> 
```
to:
```rust
pub fn fstatfs<Fd: AsFd>(fd: &Fd) -> Result<Statfs>
```
------
~Besides from the changes in module `sys/statfs`, there are two extra places where care needs to be taken:~
```shell
$ cd nix
$ rg "fstatfs\("
test/test_fcntl.rs
386:        let statfs = nix::sys::statfs::fstatfs(&tmp).unwrap();
424:        let statfs = nix::sys::statfs::fstatfs(&tmp).unwrap();
CHANGELOG.md
849:- Now functions `statfs()` and `fstatfs()` return result with `Statfs` wrapper
src/sys/statfs.rs
769:        check_fstatfs("/tmp");
770:        check_fstatfs("/dev");
771:        check_fstatfs("/run"); …
```
=> feat: I/O safety for 'sys/statfs'

src/kmod.rs
1. Adds I/O safety for module `kmod`.
=> feat: I/O safety for 'kmod'

src/kmod.rs, src/sys/mman.rs, src/sys/statfs.rs, src/sys/termios.rs, test/sys/test_termios.rs, test/test.rs, test/test_pty.rs
1. Changes the `fd` type to take `AsFd` by value for the I/O safety PRs that are merged.
* #1916 
* #1919 
* #1921 
* #1922
=> refactor: take `AsFd` by value

src/sys/inotify.rs
1. Changes the `fd` field of `struct Inotify` from `RawFd` to `OwnedFd`
2. Changes the interfaces of functions in the `impl Inotify {}`
> The type of `self` changes from `Self` to `&mut Self`. 
From:
```rust
pub fn add_watch<P: ?Sized + NixPath>(
self,
path: &P,
mask: AddWatchFlags,
) -> Result<WatchDescriptor> 
pub fn rm_watch(self, wd: WatchDescriptor) -> Result<()>
pub fn read_events(self) -> Result<Vec<InotifyEvent>>
```
To:
```rust
pub fn add_watch<P: ?Sized + NixPath>(
&mut self,
path: &P,
mask: AddWatchFlags,
) -> Result<WatchDescriptor>
pub fn rm_watch(&mut self, wd: WatchDescriptor) -> Result<()>
pub fn read_events(&mut self) -> Result<Vec<InotifyEvent>>
```
In the previous implementation, these functions can take `self` by value as `struct Inotify` [was …
=> feat: I/O safety for 'sys/inotify'

src/sys/sendfile.rs, test/test_sendfile.rs
1. Adds I/O safety for module `sys/sendfile`.
=> feat: I/O safety for 'sys/sendfile'

src/sched.rs, src/sys/uio.rs, test/sys/test_uio.rs
Adds I/O safety for modules:
1. `sys/uio`
2. `sched`
=> feat: I/O safety for 'sys/uid' & 'sched'

src/sys/timerfd.rs
1. Adds I/O safety  for module `sys/timerfd`.
=> feat: I/O safety for 'sys/timerfd'

src/poll.rs, test/test_poll.rs
1. Adds I/O safety for module `poll`.
=> feat: I/O safety for 'poll'

src/sys/epoll.rs, src/sys/event.rs, src/sys/eventfd.rs, src/sys/memfd.rs
Adds I/O safety for moduels:
1. `sys/memfd`
2. `sys/event`
3. `sys/eventfd`
-----
BYW, I called `rustfmt` on these 4 files, which introduces some noise, sorry about this.
=> feat: I/O safety for 'sys/memfd' & 'sys/event' & 'sys/eventfd'

CHANGELOG.md, src/sys/signalfd.rs
The SignalFd type is just as capable and easier to use.
CC @JonathanWoollett-Light
=> Deprecate the signalfd function.

src/sys/wait.rs
1. Adds I/O safety for `sys/wait`
----------
Actually, I am not sure about which type to use here:
```rust
pub enum Id<'fd> {
/// Wait for the child referred to by the given PID file descriptor
#[cfg(any(target_os = "android", target_os = "linux"))]
PIDFd(RawFd),
PIDFd(BorrowedFd<'fd>),
}
```
If we use `Fd: AsFd`
```rust
pub enum Id<'fd, Fd: AsFd> {
/// Wait for the child referred to by the given PID file descriptor
#[cfg(any(target_os = "android", target_os = "linux"))]
PIDFd(RawFd),
PIDFd(&'fd Fd),
}
```
then the user has to specify that generic type when using this interface, which is kinda user-unfriendly...
------
The typical usage of this interface will be something like:
```rust
// Thought currently we don't have pidfd_open(2) in `Nix`
let fd_referring_to_a_process: OwnedFd  = …
```
=> feat: I/O safety for 'sys/wait'

CHANGELOG.md, src/sys/socket/mod.rs
Added CANbus socket family protocol values for `CanRaw` and `CanBcm`
=> Added CANbus socket family protocol constants.

.cirrus.yml, test/sys/test_socket.rs
We mainly provide VsockAddr, so let's try to test well that VsockAddr mapping to libc::sockaddr_vm is correct.
Let's remove all interactions with the socket, since vsock may or may not be available in the environment.
Testing socket(), bind(), listen(), connect(), etc. caused unexpected failures, and it's out of scope of this crate.
So let's simplify the vsock test focussing on VsockAddr. This should work also on graviton, so let's try to re-enable it.
Fixes #1934
Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>
=> Rework vsock test

src/unistd.rs, test/test_unistd.rs
Uses `AsFd` for `unistd::ftruncate`.
=> feat: I/O safety `ftruncate`

Cargo.toml
To include fix https://github.com/rust-lang/libc/commit/44cc30c6b68427d3628926868758d35fe561bbe6.
This is needed to unblock https://github.com/nix-rust/nix/pull/1868.
=> fix: Update libc

CHANGELOG.md, src/mqueue.rs, test/test_mq.rs
Noticed when working on a project that `mq_timedreceive` is missing from the `mqueue` module.
Not entirely familiar with best practices around feature gating in tests - I feel like I might have messed up by not including a `#[cfg(feature = "time")]`. Would like a little guidance there.
=> Added `mq_timedreceive` to `::nix::mqueue`.

CHANGELOG.md, src/sys/socket/addr.rs
This is a bug. flowinfo and scope_id should not be byte swapped here.
See also https://github.com/nix-rust/nix/issues/1963.
=> Fix endian swap on SocketAddrV6.

src/net/if_.rs
illumos [also has if_nameindex()](https://illumos.org/man/3XNET/if_nameindex); this change allows calling nix's wrappers when building for it.
=> if_nameindex: add `target_os = illumos`

.cirrus.yml, CHANGELOG.md, README.md, src/sys/socket/addr.rs, src/sys/socket/mod.rs
=> Prepare release 0.26.2

src/unistd.rs
The called function must uphold some invariants about initializing data in order for the calls to `from_anything` to be sound.
=> Make `*::from_anything` methods unsafe

src/unistd.rs
This mirrors the approach used for the `From<&libc::passwd> for User` impl.
=> Null-check `libc::group` members before converting

CHANGELOG.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
macOS has a badly documented `LOCAL_PEERPID` sockopt that can be used to retrieve the PID of the connected peer.
I intentionally only added this for macOS because I know it exists there, and I'm not sure about ios yet even if it exists there, it's doubtful that the PID information gets any use there.
=> Added LOCAL_PEERPID/LocalPeerPid sockopt for macos

CHANGELOG.md, src/macros.rs, src/sys/event.rs, src/sys/mod.rs
* Prefer methods instead of functions.
* Create a newtype for a kqueue.
* Document everything.
* Deprecate EVFILT_SENDFILE, because it was never fully implemented upstream.
* Add support to the libc_enum! macro to be able to deprecate variants.
=> Rustier kqueue API

CHANGELOG.md, src/fcntl.rs
On Linux, I need the `AT_EACCESS` flag for `faccessat`:
```
AT_EACCESS
Perform access checks using the effective user and group IDs.  By default, faccessat() uses the real IDs (like access()).
```
~~This commit is enabling it for all platforms but redox. I'm not really sure if this is correct of I should have just added a target_os = "linux". A did quick git grep -e AT_EACCESS -e 'AT_REMOVEDIR' on libc and it showed they're available on the same targets, so for consistence I just removed the cfg limitation.~~ CI was helpful and showed me I was wrong: it's undefined on android.
=> Add `AT_EACCESS` to `AtFlags` on all platforms

src/sys/inotify.rs
This resolves issue #1998 and allows `Inotify` to be used by `Epoll` by adding AsFd.
I'm not entirely sure about the unit test. Maybe it would be possible to do a more comperhensive check by contructing inotify using `from_raw_fd` and checking that I get the same value back. However, that would basically mean duplicating  `Inotify::new` and that feels a bit pointless.
Another option would be to create an integration test to combine `Inotify` and `Epoll`.
Fixes #1998
=> inotify: Add AsFd to allow using with epoll (issue #1998)

src/unistd.rs
Link text is correct but the URL goes to the wrong function. Probably just a copy/paste issue from the other function.
=> Fixing link in rustdoc comments in User::from_name

src/sys/socket/mod.rs
This addresses diagnostics like:
error: variable does not need to be mutable
--> src/sys/socket/mod.rs:1537:13
|
1537 |         let mut p = &mut mmsghdr.msg_hdr;
=> remove unused mut from two variable declarations in sys/socket/mod.rs

src/features.rs
Resolves #2028 
Note that this is (AFAICT) the first use of `Atomic*` types in `nix` (other than tests). However, this shouldn't be a portability issue, since `nix` is not `#![no_std]`, and (IIUC) [`std` requires](https://doc.rust-lang.org/std/sync/atomic/#portability) at least loads and stores of pointer-sized atomics (i.e. `AtomicUsize`), which is all this PR uses.
=> Remove 'static mut' usage in features::os::kernel_version.

src/fcntl.rs, src/sys/socket/mod.rs, src/sys/socket/sockopt.rs, test/test_fcntl.rs
fix the new clippy::non_minimal_cfg lint
=> Clippy cleanup:

CHANGELOG.md, src/sys/time.rs, src/sys/timerfd.rs
Hi.
This PR adds an TFD_TIMER_CANCEL_ON_SET flag to use with `timerfd` on Linux and Android
=> timerfd: Add TFD_TIMER_CANCEL_ON_SET flag

src/sys/ptrace/linux.rs
All functions are documented with the equivalent C call example except for `read`, `read_user`, `write` & `write_user`.
I was looking for the function that used `PTRACE_PEEKDATA` and couldn't find it using the documentation and had to go to the source code to find it out. In hindsight, it's pretty obvious that it was read... But still I think it would be nice to have it documented
=> Add more detail for ptrace documentation

src/sys/personality.rs
It's failing in CI, and we don't yet know why.  Possibly the cloud provider just turned on seccomp.
Issue #2060
=> Disable the doc test for sys::personality::personality on aarch64

CHANGELOG.md, Cargo.toml, src/sys/socket/addr.rs
Rust's standard library no longer guarantees that Ipv4Addr and Ipv6Addr are wrappers around the C types (though for now at least, they are identical on all platforms I'm aware of).  So do the conversions explicitly instead of transmuting.
Fixes #2053
=> For invalid IP address conversions with future Rust versions

src/sys/termios.rs
This fixes the build on 32 bit Haiku systems.
=> Haiku: `speed_t` is defined as `u8` for 32 and 64 bit systems

src/lib.rs
I believe the `my` here was intended to be `many` -- but am not sure.
=> Address seeming typo in lib.rs

CHANGELOG.md, Cargo.toml, src/sys/socket/mod.rs, src/sys/socket/sockopt.rs
Requires https://github.com/rust-lang/libc/pull/3267 which landed in libc 0.2.147.
=> Enable socket timestamping options on Android

CHANGELOG.md, src/sys/signal.rs
It triggers UB, which the compiler warns about beginning with 1.41.0. Remove it, due to lack of a Fuchsia maintainer and lack of feedback from the original Fuchsia porter.
Fixes #1441
=> Remove sigevent support on Fuchsia

CHANGELOG.md, src/sys/socket/addr.rs, src/sys/socket/mod.rs, test/sys/test_socket.rs
Adds vsock support for macOS.  It's not possible to create a listening
vsock socket on a macOS host, but you can create one from inside a 
VM and connect back to the host.
=> add vsock support for macOS

CHANGELOG.md, src/sys/socket/sockopt.rs
Also SO_ACCEPTFILTER for FreeBSD/NetBSD.
=> sockopt add OpenBSD's SO_RTABLE to set the route table.

src/sys/aio.rs
aio_suspend would probably fail with EFAULT if the first operation in the list wasn't complete, due to an invalid pointer cast.
Also, deprecate lio_listio, which has the same problem, and others besides.
Fixes #1980
=> Fix aio_suspend in non-trivial cases

CHANGELOG.md, src/fcntl.rs
Solaris hasn't included flock(2) for a long while now, and building this wrapper creates issues with undefined symbols.  However, OpenSolaris derivatives like Illumos do include flock(2) so they should not be excluded here.
=> Don't build flock on Solaris

src/sys/socket/addr.rs, src/sys/socket/mod.rs, src/sys/socket/sockopt.rs, test/sys/test_socket.rs, test/sys/test_sockopt.rs
* socket
* socketpair
* listen
* setsockopt
* getsockopt
=> Add I/O safety to sockopt and some socket functions

CHANGELOG.md, src/fcntl.rs, test/test_fcntl.rs
=> Expose copy_file_range on FreeBSD and use I/O Safety

.cirrus.yml, CHANGELOG.md, Cargo.toml, src/lib.rs
The original intention behind https://github.com/nix-rust/nix/pull/1498 was to allow repositories to slim down what amount of nix they consume, saving on compile time. However, with all these features enabled by default, it only takes one crate in your entire dependency tree that doesn't set `default-features = false` and suddenly you're back to square one. The better solution IMHO would be to always require crates to opt in to the functionality they need, ensuring that this footgun can't fire.
This is a breaking change, and would need a new version number before release.
=> Do not enable any features by default

src/sys/ioctl/linux.rs
This PR adds basic support for LoongArch and does not include CI for now.
=> Add support for LoongArch

src/sys/memfd.rs
I think this is related to https://github.com/nix-rust/nix/issues/1972
I want this because I'm trying to use `ctrlc` in the compiler (https://github.com/rust-lang/rust/pull/111769), which uses this crate, and the feature set that `ctrlc` uses pulls in this function.
The compiler is primarily built as a shared object, and it is linked against an old version of glibc (2.17) so there is no `memfd_create` symbol available when it is built. Adding `#[inline]` causes this function to be codegenned differently; it is kept as MIR then since it is in fact dead, we never actually codegen it. Without `#[inline]` this function is eagerly codegenned then since dylibs have poor/no dead code elimination, we end up with an undefined symbol.
=> Add #[inline] to memfd_create to delay codegen and prevent undefined symbols in dylibs

CHANGELOG.md, src/sys/socket/mod.rs, test/sys/test_socket.rs
=> Fix an incorrect lifetime in the return value of recvmsg

.cirrus.yml, README.md
Cirrus CI is eliminating unlimited free open source builds.  Open source projects will now be limited to about 16,000 CPU-minutes per month. Tweak our CI configuration to reduce its demands:
* Eliminate the FreeBSD 12 x86_64, iOS x86_64, macOS x86_64, and Linux powerpc builds.  They weren't providing a useful amount of test coverage.
* Reduce each task to 1 CPU and 2 GB of RAM (but 4 GB for OSX).  Our build rarely uses more than a single CPU anyway.
* Split the tasks up into two groups.  The first group of 8 builds contains broad coverage.  Most build failures will be caught by one of these tasks.  The second group of 29 tasks will only run after the first group completes.
https://cirrus-ci.org/blog/2023/07/17/limiting-free-usage-of-cirrus-ci/
=> Economize our Cirrus CI builds

CHANGELOG.md, src/sys/socket/mod.rs
I'm not sure what platforms this is defined on, so I listed the ones that I think it's defined on. Below I've listed why I think it's defined on each platform.
- android - android src: https://android.googlesource.com/platform/bionic/+/c7ca8f3/libc/include/sys/socket.h#233
- freebsd - man page: https://man.freebsd.org/cgi/man.cgi?query=recvmmsg&apropos=0&sektion=2&manpath=FreeBSD+11-current&format=html
- fuchsia - defined in rust libc: https://github.com/rust-lang/libc/blob/60bf6d7fa9d561820ea562751ee455ccf67d3015/src/fuchsia/mod.rs#L1768
- illumos - I think this is the illumos src?: https://github.com/TritonDataCenter/illumos-joyent/blob/master/usr/src/uts/common/brand/lx/syscall/lx_socket.c
- linux - man page: https://man7.org/linux/man-pages/man2/recvmmsg.2.html
- netbsd - man page: …
=> Add `MSG_WAITFORONE` flag

CHANGELOG.md, src/mqueue.rs, test/test_mq.rs
Bringing `mq_open` and `mq_unlink` in line with other `nix` functions that use a path-like value.
=> Changed `name` parameter of `mqueue` functions to be generic over `NixPath`.

CHANGELOG.md, src/sys/socket/mod.rs
Add the following (linux-only) netlink `SockProtocol`s:
- `NETLINK_GENERIC`
- `NETLINK_NFLOG`
=> Add NFLOG and generic netlink families

Cargo.toml, src/sys/signal.rs
Depends on https://github.com/rust-lang/libc/pull/2813
Blocks https://github.com/tokio-rs/tokio/issues/4728
=> Allow setting kevent_flags on struct sigevent

CHANGELOG.md, src/sys/socket/sockopt.rs
=> introduces FreeBSD's SO_TS_CLOCK into net::sys::socket::sockopt.

.cirrus.yml, CHANGELOG.md, Cargo.toml, src/dir.rs, src/fcntl.rs, src/macros.rs, src/mount/bsd.rs, src/mount/linux.rs, src/mqueue.rs, src/sys/event.rs, src/sys/ioctl/mod.rs, src/sys/personality.rs, src/sys/ptrace/mod.rs, src/sys/socket/addr.rs, src/sys/socket/mod.rs, src/sys/socket/sockopt.rs, src/sys/stat.rs, src/sys/statvfs.rs, src/sys/termios.rs, src/sys/time.rs, src/sys/uio.rs, src/unistd.rs, test/sys/test_aio.rs, test/sys/test_socket.rs, test/test_fcntl.rs, test/test_sendfile.rs
Most just a bunch of cherry-picks from master, for bug fixes and Clippy stuff.
=> Prepare release 0.26.3

CHANGELOG.md, src/sched.rs
There are many features of `clone` that may cause memory unsafety when called. This documents one of them and references `fork()`, which is already unsafe to call.
Fixes #1975
=> Make `clone` unsafe

Cargo.toml, src/sys/aio.rs, src/sys/signal.rs, test/sys/test_aio.rs, test/sys/test_signal.rs, test/test.rs
It's no longer needed, because for several versions now AtomicBool::new and parking_lot::Mutex::new are const functions.
Fixes #1791
=> Eliminate the lazy_static dev dependency

CHANGELOG.md, Cargo.toml, src/sys/mod.rs, src/sys/prctl.rs, test/sys/test_prctl.rs
I have added support for the prctl syscall.
However, I am not sure that this is the right way to do it. Another way would be to wrap each possible flag to prctl as it's own function, that way it would be more similar to how the [prctl](https://github.com/viraptor/prctl-rs) crate does it. Wrapping the different options would be safer, since some options to prctl return data through pointers.
What do you think?
=> Add the Linux prctl syscall

release.toml
which no longer supports dev-version.
[skip ci]
=> release.toml: compatibility with cargo-release 0.22

CHANGELOG.md, Cargo.toml
* Add entry for 0.26.3, released from a separate branch
* Reorder some entries, and tweak a few for consistency.
* Change the crate version to 0.26.3
=> Edit CHANGELOG

Cargo.toml, src/lib.rs, src/macros.rs, src/mount/bsd.rs, src/mount/linux.rs, src/mqueue.rs, src/sys/stat.rs, src/sys/statvfs.rs, src/sys/termios.rs, src/sys/time.rs, src/unistd.rs
This reverts commit 0c3afc27d7bdbea7e5c12969e1ba0607c14b1dc9.
This rolls back the version of bitflags used to 1.1.  Upgrading bitflags to 2.0 inadvertently caused breaking changes in the r0.26 branch, by virtue of the methods that the bitflags! macro adds.
Also, mask the bad_bit_mask lint, triggered by bitflags's generated code.  That lint was the motivation for upgrading bitflags in the first place.  The bitflags maintainers have decided not to fix those warnings in the 1.x release series.
https://github.com/bitflags/bitflags/pull/373
Fixes #2112
=> Revert "Merge #2027 #2057"

CHANGELOG.md, src/sys/socket/sockopt.rs, src/unistd.rs, test/test_unistd.rs
I noticed that the `sockopt` APIs now take `AsFd`, so I figured this API should be made to do the same :slightly_smiling_face: 
`AsFd` returns a `BorrowedFd` that is correct by construction, meaning that this API rejects more error states at the type level (such as passing in `fd = -1`). As such, I've removed the `test_getpeereid_invalid_fd` testcase, since its error state is no longer reachable from Rust users of this API.
=> unistd: make getpeereid take AsFd rather than a raw FD

src/fcntl.rs
This is https://github.com/nix-rust/nix/pull/2049 but for FreeBSD
Failed build is here: https://github.com/rust-lang-ci/rust/actions/runs/6066172674/job/16456459499
With patch: https://github.com/rust-lang-ci/rust/actions/runs/6069815522/job/16464786535
I modified Rust's CI a bit so that it tests all platforms on that PR (https://github.com/rust-lang/rust/pull/111769), there should be no need for another PR after this.
=> Add #[inline] to fspacectl to prevent linker errors with dylibs and --no-allow-shlib-undefined

src/pty.rs, src/sys/epoll.rs, src/sys/select.rs, src/sys/socket/mod.rs, src/unistd.rs, test/sys/test_select.rs, test/sys/test_socket.rs, test/sys/test_sockopt.rs, test/sys/test_termios.rs, test/sys/test_uio.rs, test/test_fcntl.rs, test/test_poll.rs, test/test_pty.rs, test/test_sendfile.rs, test/test_unistd.rs
Changes `pipe`, `pipe2` and `write` to use `OwnedFd`s.
=> feat: I/O safety `pipe`, `pipe2` & `write`

CHANGELOG.md, src/sys/signal.rs
`signal::SigSet` derives `Eq`, `PartialEq` and `Hash`, but on linux, `sigfillset(3)` only initializes the first 64 bits, leaving the rest uninitialized. So two `signal::SigSets` can be different even though both have the same set of signals.
closes #1749
=> SigSet: Fix incorrect implementation of Eq, PartialEq and Hash

src/fcntl.rs, src/ifaddrs.rs, src/lib.rs, src/mount/bsd.rs, src/mqueue.rs, src/net/if_.rs, src/poll.rs, src/sys/aio.rs, src/sys/epoll.rs, src/sys/event.rs, src/sys/inotify.rs, src/sys/ptrace/linux.rs, src/sys/quota.rs, src/sys/sendfile.rs, src/sys/signalfd.rs, src/sys/socket/addr.rs, src/sys/socket/mod.rs, src/sys/socket/sockopt.rs, src/sys/uio.rs, src/unistd.rs, test/sys/test_mman.rs, test/sys/test_socket.rs
Prefer ptr::{cast, cast_const, cast_mut} over `as`.  The latter makes it too easy to accidentally change both the type and mutability when changing only one was intended.
This exercise caught an unintended mutability cast in one function, the BSD version of sendfile.  In this case there's no UB because it isn't possible for anything else to get a reference to the data that was incorrectly cast.
There was also a type cast that wasn't guaranteed to be correct (but probably was) due to memory layout guarantees in if_nametoindex.
=> Cast pointers more carefully

CHANGELOG.md, src/sys/select.rs, test/sys/test_select.rs
=> Relax lifetime requirements for FdSet::{insert, remove, contains}

CHANGELOG.md, src/dir.rs, src/fcntl.rs, test/test_fcntl.rs
Fixing  #1850 ,  Changed signature to use an Optional `rawfd`
=> Changed signature for openat function

CHANGELOG.md, src/poll.rs, test/test_poll.rs
=> Relax lifetime requirements for PollFd::new

CHANGELOG.md, src/sys/socket/mod.rs, test/sys/test_socket.rs
The signature of `recvmmsg` gets changed to:
```rust
pub fn recvmmsg<'a, XS, S, I>(
fd: RawFd,
data: &'a mut MultiHeaders<S>,
slices: XS,
flags: MsgFlags,
mut timeout: Option<crate::sys::time::TimeSpec>,
) -> crate::Result<MultiResults<'a, S>>
where
XS: IntoIterator<Item = I>,
I: AsMut<[IoSliceMut<'a>]>,
```
The signature of `sendmmsg` gets changed to:
```rust
pub fn sendmmsg<'a, XS, AS, C, I, S>(
fd: RawFd,
data: &'a mut MultiHeaders<S>,
slices: XS,
addrs: AS,
cmsgs: C,
flags: MsgFlags
) -> crate::Result<MultiResults<'a, S>>
where
XS: IntoIterator<Item = I>,
AS: AsRef<[Option<S>]>,
I: AsRef<[IoSlice<'a>]>,
C: AsRef<[ControlMessage<'a>]>,
S: SockaddrLike,
```
Fixes #2119
=> Fixes UB of `recvmmsg` and simplifies signatures of `recvmmsg` and `sendmmsg`

CHANGELOG.md, src/sys/socket/mod.rs, test/sys/test_socket.rs
`CanRaw`/`KextEvent` have the same value as `ICMP`, which means one of them has to be a constant.
I chose to make `CanRaw` & `KextEvent` constants since as far as I can tell, `Icmp` is always present (similar to Udp/Tcp, etc).
I started writing a test that sends an Echo-Request, but opening an ICMP/Raw socket requires root permissions, so I'm not sure if it's fit as a test.
=> Add `SockProtocol` variants for ICMP{,v6}

CHANGELOG.md, src/sys/signalfd.rs, test/sys/test_signalfd.rs
In 0.27.0 it inadvertently closed the file descriptor, leaving the SignalFd object accessing a stale file descriptor.
Fixes #2116
=> Fix SignalFd::set_mask

.cirrus.yml, CHANGELOG.md, README.md, src/mount/bsd.rs, src/sys/prctl.rs, src/unistd.rs
This allows us to use the very useful CStr::from_bytes_until_nul
=> Raise MSRV to 1.69.0

CHANGELOG.md, src/sys/socket/mod.rs
When sending IPv6 multicast packets with `sendmsg`, Linux does not use the hop limit set on the socket. Instead, the hop limit has to be specified for each individual message with ancillary data in a cmsg.
This commit adds the enum variant
`ControlMessage::Ipv6MulticastHopLimit` to specify the limit.
=> Add ControlMessage::Ipv6MulticastHopLimit

CHANGELOG.md, src/sys/signal.rs
Adds convenience functions for dealing with `SigSet`.
```rust
let mut sigset = SigSet::empty();
sigset.add(SIGINT);
pthread_sigmask(SigmaskHow::SIG_SETMASK, Some(&sigset), None)
```
becomes
```rust
let sigset = SigSet::from(SIGINT);
pthread_sigmask(SigmaskHow::SIG_SETMASK, Some(&sigset), None)
```
---
```rust
let mut sigset = SigSet::empty();
sigset.add(SIGINT);
sigset.add(SIGUSR1);
sigset.wait();
```
becomes
```rust
(SIGINT | SIGUSR1).wait();
```
=> Sigset conveniance

CHANGELOG.md
Remove duplicate `### Added` sections in `CHANGELOG.md`
[skip ci]
=> chose: fix CHANGELOG.md remvoe duplicate Added sections

CHANGELOG.md, src/sys/socket/addr.rs
=> Modified return type for ipaddr

CHANGELOG.md, changelog/2151.changed.md
Fix the changelog of PR #2151
-------
Since there are no code changes, to save our CI usage, I will:
1. Manually skip the CI
2. Bypass the branch protection, skip the merge queue, directly merge this into the master branch
=> chore: fix the changelog of #2151

CHANGELOG.md, changelog/2157.changed.md, src/fcntl.rs, src/sys/stat.rs, src/unistd.rs, test/test_fcntl.rs, test/test_stat.rs, test/test_unistd.rs
The following APIs now take optional `dirfd`s:
- `readlinkat()`
- `fstatat()`
- `mknodat()`
- `mkdirat()`
- `execveat()`
=> refactor: change `dirfd` arg of `xxxat()` to `Option<fd>`

changelog/2127.added.md, changelog/2127.changed.md, src/sys/mman.rs, test/sys/test_mman.rs
=> Add `mmap_anonymous` function

src/fcntl.rs
Fix the `fd_in` argument of the `copy_file_range(2)` syscall on Linux/Andorid
Well, I have no idea how the test passed before this...
=> fix: copy_file_range fd_in arg on Linux/Android

CONTRIBUTING.md
1. Document that we can have multiple change logs in 1 PR as our contributors [may be confused about this](https://github.com/nix-rust/nix/pull/2127#issuecomment-1793728040)
=> docs: document that having multi logs for 1 PR is allowed

src/sys/ioctl/mod.rs
Slices are not FFI-safe.
&[u8] and &mut [u8] are *wide pointers*, which means that at the moment, we're getting lucky because they're passed via the "ScalarPair" ABI, and this means that passing a `&[u8]` results in passing two arguments, `*const u8` and `usize` for pointer and length. This passes an extra argument to ioctl, which happens to work because the extra vararg is skipped. We're getting lucky right now, and we should explicitly pass the pointer we meant to pass instead.
This is normally checked on `extern "C"` functions, but `ioctl` in particular uses varargs which prevents the compiler check from reporting.
Passes the buffer pointer to `libc::ioctl` rather than trying to pass slices across FFI.
=> Pass pointers, not slices, to libc::ioctl

Cargo.toml, changelog/2065.added.md, src/sys/socket/mod.rs
cf. #2064 - I've added the absolute minimum I need. We could swap that u8 with something more strongly-typed, but since I'm clearly the first person using ktls & the nix crate together, I'm treading lightly in terms of added lines.
=> Parse SOL_TLS control message, closes #2064

changelog/2138.added.md, src/sys/ioctl/linux.rs, src/sys/ptrace/linux.rs, src/sys/signal.rs, test/sys/test_aio.rs, test/sys/test_ioctl.rs, test/sys/test_socket.rs, test/sys/test_wait.rs, test/test_mq.rs
Currently, R6 targets are almost identical to their R2/R5 counterparts. So we add target_arch and bump libc.
=> sys: add MIPS R6 support

changelog/2000.changed.md, src/sys/mman.rs, test/sys/test_mman.rs
Updates functions in  `nix::sys::mman` to use `NonNull`.
The case where the returned pointer is null is the error case, therefore in the `Ok` case we can return `NonNull`.
=> feat: mman `NonNull`

changelog/2125.added.md, src/sys/mman.rs
=> Add `MapFlags::map_hugetlb_with_size_log2`

src/fcntl.rs, src/lib.rs, src/mount/bsd.rs, src/mount/mod.rs, src/mqueue.rs, src/net/if_.rs, src/poll.rs, src/pty.rs, src/sched.rs, src/sys/aio.rs, src/sys/mman.rs, src/sys/mod.rs, src/sys/personality.rs, src/sys/ptrace/bsd.rs, src/sys/ptrace/linux.rs, src/sys/resource.rs, src/sys/sendfile.rs, src/sys/signal.rs, src/sys/socket/addr.rs, src/sys/socket/mod.rs, src/sys/stat.rs, src/sys/statfs.rs, src/sys/statvfs.rs, src/sys/termios.rs, src/sys/uio.rs, src/sys/wait.rs, src/time.rs, src/unistd.rs
Remove all the `#[cfg_attr(docsrs, doc(cfg(all())))]` attributes as [they are useless now](https://github.com/nix-rust/nix/pull/1611#discussion_r1391729184)
=> refactor: remove legacy `#[doc(cfg(all()))]` attributes

src/env.rs, src/errno.rs, src/ifaddrs.rs, src/lib.rs, src/pty.rs, src/sched.rs, src/sys/inotify.rs, src/sys/ioctl/mod.rs, src/sys/mman.rs, src/sys/ptrace/bsd.rs, src/sys/ptrace/linux.rs, src/sys/signal.rs, src/sys/socket/addr.rs, src/sys/socket/mod.rs, src/sys/socket/sockopt.rs, src/sys/timerfd.rs, src/sys/wait.rs, src/unistd.rs
Enable the `unsafe_op_in_unsafe_fn` lint, closes #2165
=> refactor: enable lint unsafe_op_in_unsafe_fn

.github/workflows/ci.yml
Issue #2200
Disables a target which fails in CI due to a toolchain bug.
=> Temporarily disable armv7-unknown-linux-uclibceabihf in CI

changelog/1876.changed.md, src/poll.rs, test/test_poll.rs
Implements a wrapper around `i32` for the `timeout` argument in [`poll::poll`](https://docs.rs/nix/latest/nix/poll/fn.poll.html).
This prevents the error case:
> EINVAL (ppoll()) The timeout value expressed in *ip is invalid
(negative).
Most of the code additions are simple conversions to/from integer primitives.
An alternative approach to implement the same safety with less code would require something like https://internals.rust-lang.org/t/non-negative-integer-types/17796 and would offer less usability like converting to/from `std::time::Duration`s.
=> Safer poll timeout

Cargo.toml
It adds the file `build.rs` to the package included files in `Cargo.toml`. Without it, when vendoring a project that depends on `nix`, `build.rs` is not added in vendor cache, then macos targets are broken since the `cfg_aliases` configuration added in https://github.com/nix-rust/nix/pull/2169 is missing.
=> fix(vendor): declare build.rs as included file in Cargo.toml

CONVENTIONS.md
Document that we prefer `cast()`, `cast_mut()` and `cast_const()` to cast pointer types over the `as` keyword in `CONVENTIONS.md`
=> docs: document ptr type casting in CONVENTIONS.md

changelog/2187.added.md, src/sys/socket/mod.rs, src/sys/socket/sockopt.rs, test/sys/test_socket.rs, test/sys/test_sockopt.rs
Adds FreeBSD's SCM_REALTIME and SCM_MONOTONIC into sys::socket::ControlMessageOwned to read socket control messages after setting SO_TS_CLOCK to either SO_TS_REALTIME or SO_TS_MONOTONIC. Note that this does not also support SO_TS_BINTIME yet as that requires a new data structure. See [man setsockopt for FreeBSD](https://man.freebsd.org/cgi/man.cgi?setsockopt) for more info on these settings. 
Also adds a proper enum as a parameter to sockopt::TsClock for choosing which clock to timestamp with. Previously this took a raw i32 and required libc as a dependency to properly configure.
Resolves #2186.
=> Added FreeBSD's SCM_REALTIME and SCM_MONOTONIC into sys::socket::ControlMessageOwned

build.rs
fix the wrong Solaris alias in `build.rs`
=> fix: fix wrong solaris alias

CONVENTIONS.md
Document how to remove/deprecate an interface in `CONVENTIONs.md`, I saw this in [this comment](https://github.com/nix-rust/nix/pull/1882#issuecomment-1329968842) and #2170
=> docs: document how to remove/deprecate an interface

changelog/2206.added.md, examples/getifaddrs.rs, src/net/if_.rs
And add a full example for getifaddrs.
implements fmt::Display for InterfaceFlags, and adds an example for getifaddrs
=> impl Display for InterfaceFlags

src/sys/epoll.rs, src/sys/fanotify.rs, src/sys/ptrace/bsd.rs, src/sys/sendfile.rs, src/sys/socket/addr.rs
=> cargo fmt --all -- "**/*.rs"

changelog/2213.added.md, src/fcntl.rs
Add `fctrl::SealFlag::F_SEAL_FUTURE_WRITE`, a file sealing flag available since Linux 5.1 which prevents modification except via shared writable mappings that were created prior to the seal being set.
=> Add `fctrl::SealFlag::F_SEAL_FUTURE_WRITE`

src/sys/event.rs, src/sys/mman.rs, src/sys/mod.rs, src/sys/resource.rs, src/sys/sendfile.rs, src/sys/signal.rs
Apply the cfg aliases for:
* sys/aio.rs
* sys/epoll.rs
* sys/event.rs
* sys/mman.rs
* sys/mod.rs
* sys/resource.rs
* sys/sendfile.rs
* sys/signal.rs
Ref: #2188
=> refactor: cfg for aio/epoll/event/mman/mod/resource/sendfile/signal

src/sys/stat.rs, src/sys/statfs.rs
Apply the cfg alias for:
* sys/stat.rs
* sys/statfs.rs
Ref: #2188
=> refactor: cfg for stat/statfs

src/sys/uio.rs, src/sys/wait.rs, src/time.rs
Apply the cfg aliases for
* sys/time.rs
* sys/uio.rs
* sys/wait.rs
Ref: https://github.com/nix-rust/nix/issues/2188
=> refactor: cfg for time/uio/wait

src/mount/bsd.rs, src/mount/mod.rs, src/net/if_.rs
Apply the cfg aliases for:
* mount/*.rs
* net/if_.rs
Ref: #2188
=> refactor: cfg for mount/* & if_.rs

src/sys/socket/mod.rs
=> refactor: cfg for socket/mod.rs

src/sys/socket/sockopt.rs
=> refactor: cfg for socket/sockopt.rs

src/fcntl.rs, src/features.rs, src/ifaddrs.rs, src/lib.rs, src/poll.rs, src/sched.rs, src/time.rs
Apply the cfg aliases for:
* fcntl.rs
* features.rs
* ifaddrs.rs
* lib.rs
* poll.rs
* scehed.rs
* time.rs
Ref: #2188
=> refactor: cfg for fcntl/fetures/ifaddrs/lib/poll/sched/time

src/sys/time.rs
cfg for `src/sys/time.rs`, this should be done in #2221, but I accidentally modified `src/time.rs` rather than `src/sys/time.rs` in that PR.
=> refactor: cfg for sys/time.rs

src/dir.rs
Remove the `l4re` target from `src/dir.rs` as requested in this [comment](https://github.com/nix-rust/nix/pull/2214#discussion_r1405421337)
=> refactor: remove the l4re target

src/errno.rs, src/fcntl.rs, src/features.rs, src/mount/bsd.rs, src/mount/mod.rs, src/net/if_.rs, src/sys/aio.rs, src/sys/mman.rs, src/sys/mod.rs, src/sys/ptrace/mod.rs, src/sys/resource.rs, src/sys/socket/addr.rs, src/sys/socket/mod.rs, src/sys/socket/sockopt.rs, src/sys/statfs.rs, src/sys/termios.rs, src/unistd.rs
Apply the `netbsdlike` for src/*.rs, this should be the last PR of #2188, closes #2188
=> refactor: apply the netbsdlike alias for src/*

changelog/2240.added.md, src/sys/socket/mod.rs, src/sys/socket/sockopt.rs, test/sys/test_socket.rs
Enable `ControlMessageOwned::{Ipv4RecvIf,Ipv4RecvDstAddr}` for DragonFlyBSD as requested in [this comment](https://github.com/nix-rust/nix/pull/2231/files#r1411115229)
=> feat: ControlMessageOwned::{Ipv4RecvIf,Ipv4RecvDstAddr} for DragonFlyBSD

changelog/2241.added.md, changelog/2241.changed.md, src/mount/bsd.rs, src/mount/mod.rs, src/net/if_.rs, src/sys/event.rs, src/sys/mod.rs, src/sys/ptrace/bsd.rs, src/sys/ptrace/mod.rs, src/sys/socket/addr.rs, src/sys/socket/mod.rs, src/sys/statfs.rs, src/sys/termios.rs, src/time.rs, test/sys/mod.rs, test/sys/test_aio.rs, test/sys/test_socket.rs
1. Enable most macOS functions for apple_targets
2. Enable `ClockId::setime()` and `time::clock_settime()` on macOS
Closes #2238
=> refactor: enable most macOS funcs for apple_targets

changelog/2244.added.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
From [man page](https://man7.org/linux/man-pages/man7/ip.7.html):
```
IP_BIND_ADDRESS_NO_PORT (since Linux 4.2)
Inform the kernel to not reserve an ephemeral port when
using bind(2) with a port number of 0.  The port will
later be automatically chosen at connect(2) time, in a way
that allows sharing a source port as long as the 4-tuple
is unique.
```
=> Added IpBindAddressNoPort sockopt

Cargo.toml, changelog/2245.added.md, src/sys/mman.rs
Enable `MapFlags::map_hugetlb_with_size_log2` for Android/Fuchsia
This is a TODO left in #2125
=> feat: MapFlags::map_hugetlb_with_size_log2 for Android/Fuchsia

CONTRIBUTING.md, CONVENTIONS.md, RELEASE_PROCEDURE.md
1. Document that we should use the libc from its git repo when under development, closes #2243
2. style: make all the documents use one space between sentences
3. Fix a typo and a code snippet that was not correctly rendered
=> docs: document that we should use libc from git repo when under dev

test/common/mod.rs, test/sys/mod.rs, test/sys/test_socket.rs, test/sys/test_sockopt.rs, test/test.rs, test/test_fcntl.rs, test/test_net.rs, test/test_poll.rs, test/test_sendfile.rs, test/test_stat.rs, test/test_time.rs, test/test_unistd.rs
cfg for test/*.rs
This PR also applies the `netbsdlike` alias added in #2226
=> refactor: cfg for test/*

changelog/2072.fixed.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
The socket option `IpMulticastTtl` was implemented with `u8` as type however `i32` seems to be the correct type.
=> Fix setting sockopt::IpMulticastTtl

changelog/2251.added.md, src/sys/mod.rs, src/sys/reboot.rs
Implements `reboot(2)` for NetBSD/OpenBSD, closes #2174.
Manual:
* NetBSD: https://man.netbsd.org/reboot.2
* OpenBSD: https://man.openbsd.org/reboot.2
The `RebootMode` type, different from the one defined on Linux, is a bitflag rather than an enum, so I defined a new type. On NetBSD, there is a `RebootMode`  `RB_RDONLY`:
> RB_RDONLY  0x0080    
>
> Initially mount the root file system read-only. This is currently the default, and this option has been **deprecated**.
which is deprecated, so I didn't add it.
=> feat: reboot(2) for OpenBSD/NetBSD

changelog/1945.added.md, changelog/1945.changed.md, src/sys/epoll.rs, src/sys/eventfd.rs
Added an `EventFd` type that makes usage a little more convenient and explicit.
=> EventFd type

test/sys/test_aio.rs
Ref:
* [test_aio_suspend crashes on Linux with rust nightly](https://github.com/nix-rust/nix/issues/1099)
* [aio_suspend returns EINVAL on OSX in CI](https://github.com/nix-rust/nix/issues/1361)
Since we migrated our macOS CI to GHA, Let's try if it works on GHA. For that glibc bug, let's see if it got fixed in the past 2 years.
=> test: enable test_aio_suspend on both Linux and macOS

README.md
Add `i686-unknown-hurd-gnu` to tier 3 in README and the branch protection rule as we forgot to do this in #2131
=> docs: add hurd to tier 3 in README

Cargo.toml
It looks like the libc team cut a release just after @devnexen's last PR.  Switch to it.  That makes it easier for downstream crates to use a git dependency on Nix.
=> Use the latest libc release

changelog/2263.added.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
Adds a new sockopt: `ListenQLimit`, which wraps `libc::SO_LISTENQLIMIT`.
=> Add the ListenQLimit sockopt (SO_LISTENQLIMIT)

src/sys/statfs.rs
I believe this should fix problems in the log, except the one related to the libc crate. however, I'm not sure how to test these changes.
<details>
<summary>log from an s390x build</summary>
<pre>
Compiling nix v0.24.2
error[E0428]: the name `fs_type_t` is defined multiple times
--> /home/buildozer/.cargo/registry/src/github.com-eae4ba8cbf2ce1c7/nix-0.24.2/src/sys/statfs.rs:33:1
|
31 | type fs_type_t = libc::c_uint;
| ------------------------------ previous definition of the type `fs_type_t` here
32 | #[cfg(all(target_os = "linux", target_env = "musl"))]
33 | type fs_type_t = libc::c_ulong;
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `fs_type_t` redefined here
|
= note: `fs_type_t` must be defined only once in the type namespace of this module
Compiling regex v1.6.0
error[E0425]: cannot find value …
=> statfs: fixes for s390x+musl

changelog/2270.added.md, src/fcntl.rs
Add `AtFlags::AT_EMPTY_FLAG` for FreeBSD and Hurd as discussed in https://github.com/nix-rust/nix/pull/2267#discussion_r1428832072
=> feat: AT_EMPTY_PATH for FreeBSD/Hurd

changelog/2270.added.md
Fix the wrong changelog of #2270, [found by @devnexen](https://github.com/nix-rust/nix/commit/cc42c028a24223af88dd12e826ebbccfd846c4fe#r135529221)
=> chore: fix wrong changelog of 2270[skip ci]

src/sys/stat.rs
There is a typo in `stat.rs`. "fr" should be "for".
=> Fix: typo "fr"

changelog/2275.added.md, changelog/2275.changed.md, src/fcntl.rs
Allows `O_DIRECTORY` to be used on illumos and Solaris.
Confirmed that `O_DIRECTORY` was defined on Solaris (confirmed on at least 11.4) and illumos (added via [illumos bug 9965](https://www.illumos.org/issues/9965) in early 2020)
See discussion on: nix-rust/nix/issues/2273
=> Enable OFlag::O_DIRECTORY for Solarish

Cargo.toml, changelog/2276.added.md, src/sys/socket/mod.rs, test/sys/test_socket.rs, test/sys/test_sockopt.rs
changing the sys::socket::listen backlog type from `usize` to a `i32` wrapper, offering known sane values, from -1, SOMAXCONN to
511.
close gh-2264
=> sys::socket listen's Backlog wrapper type addition.

changelog/2175.added.md, src/sys/socket/sockopt.rs, test/common/mod.rs, test/sys/test_sockopt.rs
1. kTLS is implemented as a TCP ULP, so add a `SetSockOpt` impl for it.
2. kTLS parameters are pushed to the kernel using `setsockopt(SOL_TLS)`,
so add `SetSockOpt` impls for them.
Other test fixes:
1. Change `setsockopt` tests to bind to port 0 so that
they bind to an unbound port and don't affect each other.
2. Fix `skip!` macro used to skip tests to generate its own block so that
it can be used as an expr.
---
Implement additional definitions needed to set up kTLS.
=> Add `SetSockOpt` definitions related to Linux Kernel TLS.

src/sys/sendfile.rs
~~Test the DragonFlyBSD CI failure in #2277, theoretically, I should be able to reproduce it in this PR.~~
Fix that CI failure by converting the type `SendfileHeaderTrailer` into a real struct and explicitly mark the fields that are not in use as unused with a `_` prefix.
=> fix: unused struct tuple fields on DragonFlyBSD

changelog/2268.changed.md, changelog/2268.fixed.md, changelog/2268.removed.md, src/unistd.rs
Pick up #960, closes #939
Before this PR, we were emulating `dup3()` with `dup2()` and `fcntl()`, and thus can cause a race condition, this PR makes the `dup3()` wrapper involve the real `dup3()`.
=> refactor: make dup3 wrapper call the real dup3

src/sys/socket/mod.rs
And while here, make cmsg_space a const fn, though I doubt it will make a difference since it's already inline.
The original comment was _almost_ correct.  Changing the cmsg_space macro to return an array works in most locations.  However, it fails in the test_recverr_impl function in the tests due to a E0401 Error "Inner items do not inherit the generic parameters from the items they are embedded in."  That error is very difficult to fix in our test, and it might occur in user code, too.  The root of the problem is that each length of array is its own distinct type, and in a generic function cmsg_space returns an array type that may depend on the generic parameters.
Alternatively we could provide a second macro that always heap allocates.  But that may be too complicated just to save a …
=> Correct a comment

changelog/2277.added.md, src/time.rs, test/test_time.rs
Pick up #1315, add `clock_nanosleep()`.
Closes #1315
Closes #1299
=> feat: clock_nanosleep()

changelog/2267.added.md, changelog/2267.removed.md, src/fcntl.rs, src/unistd.rs, test/test_unistd.rs
Picks up #1128
Closes #1128 Closes #1029
Enable the `AT_EMPTY_PATH` flag for `fchownat()` on Linux/Android/FreeBSD/Hurd
=> feat: AT_EMPTY_PATH for fchownat on Linux/Android/FreeBSD/Hurd

changelog/2258.added.md, src/sys/event.rs
1. impl AsFd for Kqueue
2. impl From\<Kqueue\> for OwnedFd
The author of #2183 wants to use the inner fd to identify a Kqueue instance, this PR implements it, so closes #2183
Should we do `impl AsRawFd` for it as well, I don't have any strong view over this, but if we have made decision on this, we should do it to all the I/O-safe types
=> feat: expose the inner fd of Kqueue

changelog/2283.added.md, changelog/2283.changed.md, src/errno.rs, src/fcntl.rs, src/sys/aio.rs, src/time.rs, src/unistd.rs, test/test.rs, test/test_errno.rs, test/test_mount.rs
This adds a way to set errno, it makes it possible to fully drop errno crate in crates that already use nix.
=> Introduce set_errno

.cirrus.yml
Make the Linux aarch64 CI no longer depend on the FreeBSD CI to reduce our CI time.
Credits:
We used 7 credits in the last month, so the usage should be fine:)
=> ci: run Linux aarch64 && FreeBSD checks in parallel

src/fcntl.rs, src/lib.rs, src/time.rs
Also, deprecate FlockArg::UnlockNonblock.  That combination of flags doesn't make sense.  And indeed, reviewing the kernel source code shows that the kernel will ignore LOCK_NB when LOCK_UN is set.
=> Add docs to the time and fcntl modules

src/fcntl.rs, src/sys/statfs.rs, src/sys/statvfs.rs
OpenHarmony(alias ohos) is tie 3 supported target for rust. see https://github.com/rust-lang/compiler-team/issues/568.
In implementation it sits close to musl instead of bionic and napi instead jni when comparing with android.
=> Fix compilation error with target_env=ohos

Cargo.toml
Preparing for a new release Nix 0.28.0, libc 0.2.152 is probably the last release before libc 0.3, let's try if it will work.
=> chore(deps): try libc 0.2.152

test/sys/test_fanotify.rs
Tweak `test_fanotify()` to make it monitor ONLY 1 file rather than the whole mount point. 
For more info, see [this comment](https://github.com/nix-rust/nix/pull/2269#issuecomment-1893018541).
=> test: tweak `test_fanotify()` to monitor ONLY 1 file

.github/actions/test/action.yml, .github/workflows/ci.yml, Cargo.toml, test/test.rs, test/test_mount.rs
As originally written by @kamalmarhubi in #231, these tests made clever use of Linux namespaces in order to run as unprivileged users. However, a subsequent kernel bug broke this functionality, and it hasn't been fixed even 6 years later.  The tests have been skipped ever since.
Get the tests to run again by removing the namespace stuff and requiring privileges instead.  Also, remove the custom test harness. Now Nix will be compatible with tools like cargo-nextest.
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1659087
Fixes the long-skipped mount tests so they can run again.
=> Fix the mount tests

test/test_unistd.rs
The linked [Clippy issue](https://github.com/rust-lang/rust-clippy/issues/9111) has been resolved, so let's remove this attribute.
=> test: clean clippy needless_borrow false positive issue

Cargo.toml
Try libc 0.2.153, and see if there is any target other than Hurd is broken.
=> chore(deps): try libc 0.2.153

.github/workflows/ci.yml, changelog/2311.fixed.md, src/unistd.rs, test/test_unistd.rs
=> fix: unaligned read panic on macos

src/errno.rs, src/fcntl.rs, src/sys/time.rs, src/unistd.rs, test/sys/test_select.rs, test/sys/test_signal.rs, test/sys/test_termios.rs
A couple imports have become redundant, let's clear them.
=> refactor: remove redundant imports to fix CI

RELEASE_PROCEDURE.md
1. Add docs on crates.io token.
2. Remove the last step as `cargo-release` will do it for you.
=> docs: update release doc[skip ci]

Cargo.toml, changelog/2322.changed.md
This fixes the following notice when running `cargo update` in any project that depends on the `nix` crate.
```console
$ cargo update
Updating crates.io index
note: pass `--verbose` to see 1 unchanged dependencies behind latest
$ cargo update --verbose
Updating crates.io index
Unchanged cfg_aliases v0.1.1 (latest: v0.2.0)
note: to see how you depend on a package, run `cargo tree --invert --package <dep>@<ver>`
$ cargo tree --invert --package cfg_aliases
cfg_aliases v0.1.1
[build-dependencies]
└── nix v0.28.0
└── faketty v1.0.15
```
Here is the changelog for `cfg_aliases` 0.2.0: https://github.com/katharostech/cfg_aliases/releases/tag/v0.2.0
The change related to `debug_assertions` appears to be the impetus for 0.2 to be released as a breaking change, but it does not affect `nix` as …
=> Update cfg_aliases dependency to 0.2

changelog/2287.added.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
Add socket option `Ipv6Ttl` for apple targets.
There is a test (`test_ttl_opts()`) for `Ipv4Ttl` and `Ipv6Ttl`, but the support of `Ipv4Ttl` for apple will be added in #2203, which means that I cannot enable that test in this PR, will do it when both of these PRs get merged.
=> feat: sockopt Ipv6Ttl for apple targets

src/dir.rs
Corrects a wrong doc comment.
The file descriptor won't be closed if `Dir::from_fd()` succeeds, it will be closed by `closedir(3)`, which will be involved when the returned `Dir` is dropped.
=> docs: correct a doc comment

changelog/2315.changed.md, src/pty.rs, test/test_pty.rs
Before this PR, our `ForkptrResult` was defined like this:
```rs
pub struct ForkptyResult {
pub master: OwnedFd,
pub fork_result: ForkResult,
}
```
The problem with this definition is that the `master` field won't be initialized (actually, it won't be accessed at all) within the forked child process, which means that our `forkpty()` was calling `OwnedFd::from_raw_fd(an uninitialized memory)`, if the dirty value stored in that uninitialized memory is not a valid value for a file descriptor (say -1), then this function will panic, making the child process panic.
This PR redefines the `ForkptyResult` type so that the `master` field is only present in the parent process.
cc @Xeom 
related to #2312
=> refactor: redefine ForkptyResult to avoid uninited master field

changelog/2324.changed.md, src/sys/ptrace/linux.rs
Fix #2323
Change the signature of `ptrace::write` and `ptrace::write_user` to make them safe
=> Change the type of data of ptrace::write to make it safe

changelog/2325.added.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
=> Add the UtunIfname sockopt (UTUN_OPT_IFNAME)

changelog/2328.added.md, src/sys/socket/addr.rs
- Add `Into<libc::sockaddr_in6> for SockaddrIn6`
- Add `Into<libc::sockaddr_in> for SockaddrIn`
My typical use case for these `Into` traits is when I am bridging from safe world into the world of pain (C). For example,  presently I have to go over `as_ref()` to access the underlying `sockaddr_inX` . This is a bit verbose for my liking, so I figured it would be great to have `into()` to do the job for me.  Usually `From` is preferred but I am not certain if we want that, hence I have implemented `Into` but can easily flip to `From` if that makes sense.
```diff
let addr_sa = SockaddrIn6::from(SocketAddrV6::new(addr, 0, 0, 0));
let mut req: in6_aliasreq = unsafe { mem::zeroed() };
-req.addr = *addr_sa.as_ref();
+req.addr = addr_sa.into();
```
I also noticed that `repr(transparent)` is set on …
=> Improve ergonomics between SockaddrIn and underlying libc type

src/sys/socket/addr.rs
Fix a clippy lint that happens in #2329
=> style: fix clippy lint clippy::mixed_attributes_style on nightly tier3

.github/workflows/ci.yml
Disable the tier3 DragonFlyBSD CI because the latest nightly rust toolchain is broken on it, see the upstream issue: https://github.com/rust-lang/rust/issues/122585
Nix issue: https://github.com/nix-rust/nix/issues/2337
=> ci: disable the DragonFlyBSD CI

changelog/2326.added.md, src/sys/signal.rs
Make SigAction repr(transparent) & can be converted to/from the libc raw type.
This is the first PR towards the goal described in this [comment](https://github.com/nix-rust/nix/issues/2319#issuecomment-1967988916), closes #2319.
I will handle the remaining ones in the future PRs.
refe: #2327
=> feat: make SigAction repr(transparent)&From<raw>&Into<raw>

changelog/2332.added.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
Allows to use `SO_REUSEPORT_LB` so incoming connections can be distributed to bound (up to 256) sockets in a Load-Balanced fashion.
=> sys::socket: adding freebsd's ReusePortLb constant.

src/sys/resource.rs
on Apple's devices. this field returns the value in byte. close #2331
=> sys::resource update max_rss accessor doc to reflect the unit per platform

test/sys/test_socket.rs
Fix the below clippy warning:
```sh
error: useless use of `vec!`
--> test/sys/test_socket.rs:2410:19
|
2410 |     let mut iov = vec![[IoSliceMut::new(&mut buffer)]];
|                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: you can use an array directly: `[[IoSliceMut::new(&mut buffer)]]`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_vec
= note: `-D clippy::useless-vec` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::useless_vec)]`
```
=> style: try fixing clippy warning

src/sys/statfs.rs, src/sys/time.rs
This PR ignores the false-positive warnings introduced by clippy lint: [duplicated_attributes](https://rust-lang.github.io/rust-clippy/master/index.html#/duplicated_attributes).
There is an issue for it, see https://github.com/rust-lang/rust-clippy/issues/12537.
=>  style: ignore false-positive lint clippy::duplicated_attributes

changelog/2340.added.md, src/net/if_.rs, test/test_net.rs
=> Added if_indextoname function.

CONVENTIONS.md, build.rs
While reviewing #2314, I found that it is easy for contributors to accidentally use cfg aliases that are ONLY for 1 operation system, this is something we don't like (see #2236 and [clippy::mismatched_target_os](https://rust-lang.github.io/rust-clippy/master/index.html#/mismatched_target_os) ), so let's document this.
=> docs: document we don't alias for ONLY 1 OS[skip ci]

changelog/2339.added.md, src/fcntl.rs, test/test_fcntl.rs
Adds support for openat2 on linux. Includes a new `ResolveFlag` struct to pass resolve flags, which is passed directly to the new `fcntl::openat2` function. `libc::open_how` isn't exposed in any way here, which will mean this API needs to change if there's an update that extends `libc::open_how` with new fields.
Given that the whole point of `libc::open_how` is that it's extensible, I'm not sure that this is the right way to go about adding this API. I could be convinced to go back and add something that looks more like the stdlib's `OpenOptions` that would allow adding more arguments to this function without a breaking change. I would love some input/direction here.
Fixes #1400.
=> Add support for openat2.

changelog/2349.added.md, src/unistd.rs
=> Add _PC_MIN_HOLE_SIZE for use with pathconf

src/lib.rs, src/mount/apple.rs, src/mount/linux.rs, src/sys/fanotify.rs
`with_opt_nix_path()` has been defined multiple times in our code, which introduces duplicate code, this PR moves the implementation to `lib.rs` and makes it a utility function.
=> refactor: make with_opt_nix_path() a util

CONVENTIONS.md
Document that one can use `Errno::result()` to do error handling in `CONVENTIONS.md`.
=> docs: document Errno::result() in CONVENTIONS.md

.github/workflows/ci.yml
Bring DragonFlyBSD and Haiku CI back
Closes #2337 
Closes #2350
=> ci: bring DragonFlyBSD and Haiku CI back

.github/actions/check_new_changelog/action.yml
Fix changelog checker by trimming the 'changelog/' prefix
=> ci: fix changelog checker by trimming the 'changelog/' prefix

changelog/2367.changed.md, src/sys/signalfd.rs, test/sys/test_signalfd.rs
Like with many other file descriptors, concurrent use of signalfds is safe. Changing the signal mask of and reading signals from a signalfd can now be done with the `SignalFd` API even if other references to it exist.
Fixes #2366.
=> Allow use of SignalFd through shared reference

.github/workflows/check_new_changelog.yml, .github/workflows/ci.yml
The changelog checker only works with PRs, so we should only execute it in PRs.
=> ci: only run changelog checker in PR

test/sys/test_sockopt.rs, test/test.rs
From this [post](https://forums.developer.apple.com/forums/thread/85473), the `utun` interface requires privilege, and this is exactly what happens on my mac:
```sh
$ cargo t --all-features test_utun_ifname -q
running 1 test
F
failures:
---- sys::test_sockopt::test_utun_ifname stdout ----
thread 'sys::test_sockopt::test_utun_ifname' panicked at test/sys/test_sockopt.rs:854:36:
called `Result::unwrap()` on an `Err` value: EPERM
```
This PR skips the test if the process is not privileged.
=> test: skip test_utun_ifname if unprivileged

test/test.rs
For `FORK_MTX` use the `Mutex` type from `parking_lot` rather than the std one for the feature of no poisoning.
Closes #2363
=> test: use parking_lot::Mutex for FORK_MTX

changelog/2044.added.md, src/sys/ptrace/linux.rs, test/sys/test_ptrace.rs
This is related to https://github.com/nix-rust/nix/pull/1695, but have many issues solved here:
- `{get,set}regset` now allows specifying which set of registers to read/write, as defined in `RegisterSet`. This should be the expected behavior.
- Also added `PTRACE_{GET,SET}REGS` for most platforms other than x86 using aforementioned implementation.
=> Add implementation of `PTRACE_{GET,SET}REGSET`

changelog/2379.added.md, src/unistd.rs
Add 
* `sync(2)` for `apple_targets/solarish/haiku/aix/hurd`
* `syncfs(2)` for `hurd` 
*  `fdatasync(2)` for `aix/hurd`
closes #2376
=> feat: sync APIs for more platforms

changelog/2378.added.md, src/sys/prctl.rs, test/sys/test_prctl.rs
to set a name for an `anonymous` region for Linux/Android.
=> sys::prctl: Adding set_vma_anon_name.

changelog/2380.added.md, src/unistd.rs
is not present in system headers, however the syscall is actually implemented.
=> unistd: fdatasync support for apple.

changelog/2374.added.md, src/fcntl.rs
=> Add O_SEARCH to all platforms supported by libc crate

test/sys/test_signal.rs
This test changes the process-wide signal handler so we should use a lock to serialize it with other tests.
cc @TheJonny
=> test: grab the SIGNAL_MTX lock in test_sigaction

changelog/2382.added.md, src/fcntl.rs
Add `fcntl::OFlag::O_PATH` for FreeBSD and Fuchsia.
Closes #2361
=> feat: OFlag::O_PATH for FreeBSD and Fuchsia

test/test_unistd.rs
=> test: initgroups: compare result group lists without order

test/mount/test_mount.rs, test/test.rs
fork() duplicates all open file descriptors, which then could prevent a successful umount().
So either when creating file descriptors or when requiring a file descriptor to be closed, we must make sure that no child processes have copies. since wile descriptors are created all over the place, It is more practical to wait for all child processes before unlock.
=> test: Grab FORK_MTX when unmounting or forking in the mount tests

src/sys/ptrace/linux.rs, test/sys/test_ptrace.rs
Previous implementations of `{get,set}regset` are incorrect when register set value is anything other than `NT_PRSTATUS`. This PR adds the ability to return corresponding struct to the value using type parameters `S: RegisterSet`, so the behaviour is correct.
Added `NT_PRSTATUS` as well as `NT_PRFPREG` types so we can also probe floating-point registers. Other register sets may be inspected as well, such as arch-specific vector registers, but I don't have a use case right now, and it is easy to implement afterwards with the framework in this PR.
This is an improvement over https://github.com/nix-rust/nix/pull/2044, so changelog remains the same.
=> feat: Use type parameters to allow `{get,set}regset` to use different register set structs

Cargo.toml, changelog/2388.added.md, src/unistd.rs
Added `PathconfVar::MIN_HOLE_SIZE` for apple_targets.
Ref #2349
=> feat: MIN_HOLE_SIZE for apple targets

build.rs
Support VisionOS, closes #2298.
target: https://doc.rust-lang.org/nightly/rustc/platform-support/apple-visionos.html
=> feat: Add VisionOS to apple_targets

changelog/2391.added.md, src/fcntl.rs
Add `OFlag::O_SEARCH` for apple targets
ref: #2374
=> feat: OFlag::O_SEARCH for apple targets

.github/workflows/ci.yml, build.rs, src/sys/signal.rs, test/common/mod.rs, test/sys/test_signal.rs, test/test.rs, test/test_fcntl.rs
This PR tries to fix the CI, there are 2 issues here:
1. New nightly toolchain added checks for cfg values, and they work pretty well
1. there are few typos in our cfg values (which is really unfortunate) `fushsia -> fuchsia`
2. `target_arch = x32` does not exist
2. For CI that are using our MSRV toolchain, the last step `before_cache_script` would fail with `Permission denied` because the files that it wants to delete are owned by root: https://github.com/nix-rust/nix/actions/runs/8958096003/job/24601956503?pr=2394
This is kinda weird because it didn't happen in the past, and for now, it only happens with our MSRV toolchain.
```
uid=1001(runner) gid=127(docker) groups=127(docker),4(adm),101(systemd-journal)
/home/runner/.cargo/registry/index
├── [root     root    ] …
```
=> ci: fix CI by correcting wrong cfg value & removing cache with sudo

src/sys/ptrace/linux.rs
For those types implementing `trait RegisterSet`, defining them with zero-variants enum rather than unit struct as we don't want our users to construct them, and an enum with 0 variants will never be constructed, so using it is more suitable than using unit struct here.
For more discussion, see this [thread](https://github.com/nix-rust/nix/pull/2373#discussion_r1573538488).
This is not an API change unless users are constructing those unit struct types, which should have no use cases, so no CHANGELOG needed.
=> refactor: use zero-variants enum for types that are RegisterSet

Cargo.toml
=> chore: bump libc to 0.2.154

changelog/2401.changed.md, src/sys/aio.rs, test/sys/test_aio.rs, test/sys/test_aio_drop.rs
Adds I/O safety to the sys/aio module.  Those methods now take `AsFd` arguments instead of `RawFd`.  And `struct Aiocb` now has a lifetime argument.
=> Added I/O safety to sys::aio

src/sys/aio.rs
=> Remove an unnecessary cast from aio_suspend's doc test

changelog/2404.added.md, src/fcntl.rs, src/sys/aio.rs
It first appeared in FreeBSD 13.0.
=> Enable O_DSYNC on FreeBSD with fcntl and aio_fsync

changelog/2407.added.md, src/fcntl.rs, test/test_fcntl.rs
It can upgrade or downgrade a lock.
Fixes #2356
Allows flock locks to be changed.
=> Add Flock::relock

Cargo.toml
libc 0.2.154 has been yanked, so we have to bump it to 0.2.155.
=> chore: bump libc to 0.2.155

src/sys/fanotify.rs
Correct the docs for 2 fanotify init limit flags, they only have hardcoded limit values before Linux kernel 5.13, after that, they can be changed via config file.
ref: [man 7 fanotify](https://man7.org/linux/man-pages/man7/fanotify.7.html)
=> docs: correct limit value of FAN_UNLIMITED_QUEUE and FAN_UNLIMITED_MARKS

changelog/2326.added.md, src/sys/signal.rs
`impl From<libc::sigaction> for SigAction` is unsafe since there is no guarantee on the values stored in `libc::sigaction`, revert the implementation added in #2326.
Issue #2327 still needs to be resolved, some thoughts on it:
1. impl TryFrom and check the values to ensure they are valid
2. Define unsafe traits like `unsafe trait UnsafeFrom/UnsafeInto`
cc @AzariasB
=> revert: impl From<sigaction> for SigAction

changelog/2399.fixed.md, src/sys/fanotify.rs, test/sys/test_fanotify.rs
`fanotify` returns events with the fd set to `FAN_NOFD` when the queue overflows. 
Trying to close it panics with `EBADF`, so don't bother.
=> fix: only close `fanotify` events with a valid fd

test/sys/test_statfs.rs
This PR removes the test of inode count in `test/sys/test_statfs.rs` since it sometimes fails the CI on macOS, see issue #2411.
We don't want to bother with the issue, and actually we don't need to since we only need to ensure the Rust binding is working, so remove it.
Closes #2411
=> test: remove test of inode count in test_statfs.rs

changelog/2413.changed.md, src/sys/socket/mod.rs, test/sys/test_socket.rs
If MSG_CTRUNC is set, it is not safe to iterate the cmsgs, since they could have been truncated. Change `RecvMsg::cmsgs()` to return a `Result`, and to check for this flag (an API change).
Update tests for API change. Add test for too-small buffer.
fixes #2400
=> recvmsg: Check if CMSG buffer was too small and return an error

changelog/2406.fixed.md, src/sys/socket/mod.rs
The kernel, since 5.0, process the segmentation offload with a signed int.
close #2403.
=> fix ControlMessageOwned::UdpGroSegments UDP packets processing type.

src/lib.rs, src/sched.rs, src/sys/socket/sockopt.rs, src/sys/timer.rs, src/sys/timerfd.rs
This PR
1. Fixes documents identification issue
2. Adds type annotations for one usage of `std::mem::transmute()`
3. Dead code analysis of the latest nightly toolchain has become smarter, there are some unused helper SetXXX/GetXXX types in `src/sys/socket/sockopt.rs`, this PR gates them with target and feature.
=> refactor: fix clippy & unused imports/helper type

src/env.rs
~~[`std::env::remove_var` has been made unsafe](https://github.com/rust-lang/rust/pull/124636). Due to lint `unsafe_op_in_unsafe_fn`, we need to wrap it in an unsafe block.~~
This PR is for the following CI failure (full log [here](https://github.com/nix-rust/nix/actions/runs/9330193674/job/25683513633?pr=2417)):
```rs
error[E0133]: call to unsafe function `std::env::remove_var` is unsafe and requires unsafe block
--> src/env.rs:52:17
|
52 |                 env::remove_var(name);
|                 ^^^^^^^^^^^^^^^^^^^^^ call to unsafe function
|
= note: for more information, see issue #71668 <https://github.com/rust-lang/rust/issues/71668>
= note: consult the function's documentation for information on how to avoid undefined behavior
note: an unsafe function restricts its caller, but its …
```
=> chore: ignore lint unsafe_op_in_unsafe_fn for usage of env::remove_var

.github/workflows/ci.yml
Bump GitHub action runner:
* `macos-14` -> `macos-latest`
Currently, `macos-latest` is `macos-14`, so no changes for now.
* `ubuntu-20.04` -> `ubuntu-latest`
Update:
For `cross` test, we would still use Ubuntu 20.04 due to this issue: #2418.
=> ci: bump GitHub action runner

.github/workflows/ci.yml, src/lib.rs
This allows the tests to continue compiling in new Rust versions, even if new warnings are added.
Fixes #2423.
=> Don't `deny(warnings)` outside of CI

src/sys/signalfd.rs
As requested by #2426, document `signalfd::siginfo`. Though I didn't explicitly say something like "this is not the siginfo_t type", the current document should make that pretty obvious.
Closes #2426 
cc @lolbinarycat
=> docs: document signalfd::siginfo[skip ci]

src/env.rs
Revert #2421 since the Rust issue has been fixed, and the fix should be available in the latest nightly, I guess?
=> revert: PR 2421 since the Rust issue has been fixed

test/sys/mod.rs, test/sys/test_memfd.rs
Following #2431, even though we cannot resolve the linking issue under QEMU, we can still test this syscall on FreeBSD.
=> test: test memfd_create() on FreeBSD

test/test_dir.rs
Clear a fixed false positive lint `clippy::unnecessary_sort_by`.
=> chore: clear a fixed false positive lint

changelog/2434.changed.md, src/dir.rs, src/fcntl.rs, test/sys/test_socket.rs, test/sys/test_termios.rs, test/test_dir.rs, test/test_fcntl.rs, test/test_pty.rs, test/test_stat.rs, test/test_unistd.rs
This PR adds I/O safety to `fcntl.rs` and `dir.rs`.
Ref: #1750 
For those `xxat()` interfaces, I didn't introduce a new trait to represent directory file descriptors, instead, I took the way how rustix implements it:
1. Define `AT_FDCWD: BorrowedFd<'static>`
2. Change the signature to `xxat<Fd: AsFd>(dirfd: Fd, ...)`
because:
1. rustix has been using this interface for a long time, which means it would work pretty well.
3. It is indeed unfortunate that we cannot catch some errors at compile time, but we will eventually get notified at runtime, e.g., when passing a fd that is not a directory to `dirfd`, or using `AT_FDCWD` with non-`xxat()` functions.
=> refactor: I/O safety for modules fcntl and dir

changelog/1936.changed.md, changelog/1936.removed.md, src/sys/signal.rs
1. Adds I/O safety for `sys/signal`.
=> feat: I/O safety for 'sys/signal'

.github/workflows/ci.yml
Rust std is broken on Haiku, we have to disable the Haiku CI until the issue is fixed.
Ref: #2441
=> ci: disable Haiku

changelog/2440.changed.md, src/fcntl.rs, src/poll.rs, src/pty.rs, src/sys/eventfd.rs, src/sys/fanotify.rs, src/sys/inotify.rs, src/sys/timerfd.rs, src/unistd.rs, test/sys/test_memfd.rs, test/sys/test_socket.rs, test/sys/test_termios.rs, test/sys/test_uio.rs, test/test.rs, test/test_fcntl.rs, test/test_sendfile.rs, test/test_unistd.rs
Add I/O safety to module unistd.
The safe interface for `dup2()` proposed in this PR looks like this:
```rs
pub fn dup2<Fd: AsFd>(oldfd: Fd, newfd: &mut OwnedFd) -> Result<()>
```
We take `newfd` by mutable reference so that we can ensure we have exclusive access. This interface stops users from specifying `newfd` with arbitrary fd values, `unsafe fn dup2_raw()` comes as a remedy:
```rs
pub unsafe fn dup2_raw<Fd1: AsFd, Fd2: IntoRawFd>(
oldfd: Fd1,
newfd: Fd2,
) -> Result<OwnedFd>
```
`dup2_raw()` is unsafe because when specifying a fd that is open, one has to ensure the returned `OwnedFd` is the ONLY owner of this fd, or a double close will happen.
Using the above `dup2()` interface for stdin/stdout/stderr redirection is troublesome, one has to construct an `OwnedFd` from …
=> refactor: I/O safety for unistd.rs

changelog/2452.removed.md, src/sys/epoll.rs, src/sys/eventfd.rs
1. Remove `EventFd::defuse()` because it is a no-op, `write(0)`ing to an event fd does nothing. While in the documentation, it says:
> a following call to `poll`, `select` or `epoll` will block.
which means that this method should reset the kernel counter to 0, but it won't.    
2. Remove `EventFd::arm()` for symmetry reasons.
Having `read()/write()` is already sufficient for usage. 
Closes #2422
=> refactor: remove EventFd::defuse() and EventFd::arm()

.github/workflows/ci.yml, Cargo.toml
The difference between -Zminimal-versions and -Zdirect-minimal-versions is subtle.  But the important point is that with the former, a new release published by one of our dependencies can cause our CI to fail. With the latter, it cannot.  That's why I think it's better to test with the latter.
=> Fix the build with -Zdirect-minimal-versions

changelog/2454.fixed.md, src/sys/signal.rs
This PR fixes building `nix` on sparc-linux by disabling unsupported signals.
The unsupported signals match those of sparc64-linux.
=> Disable unsupported signals on sparc-linux

changelog/2456.fixed.md, src/sys/socket/mod.rs
`target_env = "ohos"` (OpenHarmony) uses a musl based libc. Fixes a compilation failure when targeting `aarch64-unknown-linux-ohos`:
```
error[E0308]: mismatched types
--> /home/jschwender/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.29.0/src/sys/socket/mod.rs:1415:32
|
1415 |             (*cmsg).cmsg_len = self.cmsg_len();
|             ----------------   ^^^^^^^^^^^^^^^ expected `u32`, found `usize`
|             |
|             expected due to the type of this binding
```
=> Fix cmsg_len() return type on OpenHarmony

changelog/2113.added.md, src/sys/socket/sockopt.rs
`IPV6_PKTINFO` was missing from `sockopt` so I added it and the documentation for `IPV6_RECVPKTINFO` incorrectly said it was enabling the flag for `IPV6_PKTINFO` so I corrected that.
=> Add IPV6_PKTINFO, Correct documentationn for IPV6_RECVPKTINFO

changelog/2464.added.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
add socket option IP_TOS (`nix::sys::socket::sockopt::IpTos`) IPV6_TCLASS (`nix::sys::socket::sockopt::Ipv6TClass`) on Android/FreeBSD
=> feat: add socket option IP_TOS/IPV6_TCLASS on Android/FreeBSD

changelog/2465.changed.md, src/sys/socket/sockopt.rs
In #2425, we renamed `IpTos` to `Ipv4Tos`, this is a breaking change, to help our users migrate, let's add `IpTos` back and mark it deprecated.
=> chore: deprecate `IpTos` in favor of `Ipv4Tos`

src/sys/socket/sockopt.rs
In our most `getsockopt_impl!()` implementations, `match <$ty>::try_from()` will always succeed, making the `Err(_)` branch unreachable, however, we have to allow this because one exception: `SockType`.
For more information, see the code comments.
=> chore: allow unreachable pattern in macro getsockopt_impl

changelog/2473.added.md, src/unistd.rs
This PR adds `SeekData` and `SeekHole` to `Whence` for hurd and apple targets.
Corresponding constants were added to the `libc` crate in:
- Apple: https://github.com/rust-lang/libc/pull/2886, released `v0.2.133` (September 2022)
- Hurd: https://github.com/rust-lang/libc/pull/3325, released `v0.2.149` (October 2023)
=> Add `SeekData` and `SeekHole` to `Whence` for hurd/apple targets

src/sys/socket/mod.rs
The Ipv4Ttl control message has a different size on Linux than on FreeBSD, and needs to be cast differently.
=> Fix a clippy::unnecessary_cast lint on the latest nightly

changelog/2474.added.md, src/sys/socket/addr.rs
At the moment nix only offers conversions between `SockaddrIn` -> `SocketAddrV4` and `SockaddrIn6` -> `SocketAddrV6` but no conversions to the container type, `SocketAddr` itself.
While it's trivial to wrap either `SocketAddrV4` or `SocketAddrV6` into `SocketAddr`, I think having a shortcut would improve ergonomics and essentially align nix with std, which supports `From` conversions from `SocketAddrV{4,6}` to `SocketAddr`.
=> Add direct conversion from SockAddrIn(6) to SocketAddr

changelog/2475.added.md, src/lib.rs, src/spawn.rs, test/test.rs, test/test_spawn.rs
Add wrappers for posix_spawn related functions
Replaces #2007
Closes #1740
=> Add wrappers for posix_spawn related functions

src/mqueue.rs, src/sys/socket/sockopt.rs, src/unistd.rs, test/test.rs
Resolves the CI errors that occurred in #2477, which are mostly about the clippy rule [too_long_first_doc_paragraph](https://rust-lang.github.io/rust-clippy/master/index.html#/too_long_first_doc_paragraph).
=> docs: fix doc style & make clippy happy

changelog/2482.added.md, src/fcntl.rs
Enable/disable read ahead globally on the file descriptor. When on,
the os preemptively reads data in cache to anticipate future read
operations.
=> fcntl adding F_RDAHEAD for apple targets.

Cargo.toml
Bump the libc crate to its latest version 0.2.158.
=> chore: bump libc to 0.2.158

changelog/2393.added.md, src/fcntl.rs, test/test_fcntl.rs
=> fcntl adding apple F_PREALLOCATE flag.

src/lib.rs
`#![allow(clippy::too_long_first_doc_paragraph)]` as I don't think it really matters.
=> style: allow clippy::too_long_first_doc_paragraph

.github/workflows/ci.yml
Re-enable the CI for `armv7-unknown-linux-uclibceabihf` as the upstream issue is possibly fixed.
=> ci: enable armv7-unknown-linux-uclibceabihf CI

Cargo.toml, build.rs
With 0.2.1, there's no need to manually write rustc-check-cfg statements.
=> Use cfg_aliases 0.2.1

src/lib.rs
The default level for this lint is `warn`, let's deny it. Though I am not sure if this is only available since Rust 1.80, let's verify this in our CI.
=> style: deny(unexpected_cfgs)

src/sys/fanotify.rs
1. Corrects the invalid links in mod `fanotify`, I am actually surprised that they weren't detected in our CI.
2. Add more links to this module.
=> docs: correct invalid link in mod fanotify

src/sys/fanotify.rs, src/unistd.rs, test/sys/test_socket.rs
`libc::close(2)` will return `EBADF` when there is a double-close, so our Rusty wrapper does not need to be unsafe. I guess my mind was dizzy when I originally modified this interface.
No changelog is needed as this change has not been released yet.
=> refactor: `unistd::close()` does not need to be unsafe

src/spawn.rs
Many functions used for PosixSpawnFileActions were demanding fds passed implement the AsFd trait, but because these actions are meant to be taken in the child process, that trait doesn't offer much benefit and actually often leads to the caller needing to do an unsafe operation: instantiating an OwnedFd from a RawFd. All of these functions need a RawFd anyway, so just let the caller pass a RawFd directly rather than have to unsafely create an OwnedFd first, which itself could have unintended side effects like closing the FD in the parent when no parent-side actions were intended.
Followup to #2475, which added the API and has not been in a released version yet.
=> fix: allow safer PosixSpawnFileActions usage

changelog/2483.added.md, src/fcntl.rs, test/test_fcntl.rs
to get the current device address, in practice its current offset only.
=> fcntl adding F_LOG2PHYS* flags.

src/features.rs
The test function `test_parsing_kernel_version()` is public, which is unnecessary since it is under attribute `#[test]`. Also, it causes the CI failure in PR #2500:
```
error: missing documentation for a function
--> src/features.rs:95:5
|
95  |     pub fn test_parsing_kernel_version() {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
note: the lint level is defined here
--> src/lib.rs:121:12
|
121 |     #[deny(missing_docs)]
|            ^^^^^^^^^^^^
error: could not compile `nix` (lib test) due to 1 previous error
```
so let's make it private.
=> refactor: make test_parsing_kernel_version() private

changelog/2502.added.md, src/sys/ptrace/linux.rs, test/sys/test_ptrace.rs
I needed this specific API for packaging my project for Alpine Linux distribution:
- https://github.com/JakWai01/lurk/issues/4
- https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/71833
- https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/71875
I added support for `aarch64-unknown-linux-musl` for `getregs()` function and it builds fine now, but I don't have a way to test it.
Also, I'm not sure if this is the correct way to add support for this architecture - but should be fine!
Let me know what you think and I can try adding support for other functions (such as `setregs()`) as well.
BTW this is my first PR to the `nix` crate so please let me know if I'm doing something wrong :bear:
=> Add `getregs()`/`setregs()`/`getregset()`/`setregset()` for Linux/musl/aarch64

src/features.rs, src/unistd.rs
Fix failed to build for target `wasm32-unknown-emscripten` with `--features user` with this error:
```
error[E0432]: unresolved import `self::os`
--> src/features.rs:2:15
|
2 | pub use self::os::*;
|               ^^ could not find `os` in `self`
error[E0609]: no field `pw_class` on type `&passwd`
--> src/unistd.rs:3569:55
|
3569 |                 class: CString::new(CStr::from_ptr(pw.pw_class).to_bytes())
|                                                       ^^^^^^^^ unknown field
|
= note: available fields are: `pw_name`, `pw_passwd`, `pw_uid`, `pw_gid`, `pw_gecos` ... and 2 others
error[E0609]: no field `pw_change` on type `&passwd`
--> src/unistd.rs:3579:28
|
3579 |                 change: pw.pw_change,
|                            ^^^^^^^^^ unknown field
|
= note: available fields …
```
=> Feature `user` for emscripten

changelog/2499.added.md, src/sys/mman.rs
This pull adds two flags: MAP_SHARED_VALIDATE & MAP_SYNC implemented on https://github.com/rust-lang/libc
The MAP_SHARED_VALIDATE flag was added to linux since 4.15, its a flag that does two things: provide backwards compatibility with old mmap implementations that don't check for unknown flags, and allow new flags to be added.
MAP_SYNC, on the other hand, was added to allow mmap to utilize Direct Accses (DAX) on hardware that support it (non-volatile memory devices) or in general: any ram-shaped filesystem.
both flags are available on both linux and android. (Edit: The android kernel does not support the flags)
Notice:
mmap always returns ENOTSUPP when MAP_SYNC is used on filesystems that are not mounted with DAX enabled (normal everyday filesystems), this means that this kind of test …
=> Add MAP_SHARED_VALIDATE & MAP_SYNC

changelog/2505.fixed.md, src/sys/prctl.rs, test/sys/test_prctl.rs
The `ns` argument of function `nix::sys::prctl::set_timerslack()` [should have type `c_ulong`](https://man7.org/linux/man-pages/man2/PR_SET_TIMERSLACK.2const.html), before this PR, we are using an `u64`, which causes issue #2497.
This PR changes the type to `c_ulong`.
Closes #2497
=> fix: correct arg type of prctl::set_timerslack

src/sys/socket/mod.rs, test/sys/test_socket.rs
Makes it possible to call `Backlog::new(libc::SOMAXCONN)` without error.
In the case where I encountered this, a constant is passed to `Backlog::new`
and it just happens to be equal to `SOMAXCONN` on some platforms.
=> fix off-by-one error in range check of Backlog::new

.github/workflows/ci.yml, Cross.toml, README.md, test/sys/test_prctl.rs
This PR is the reimplementation of PR #2461. That will enable CI testing for `loongarch64-unknown-linux-gnu`.
=> Enable CI for Loongarch64

src/sys/socket/mod.rs
Fixes the Clippy error that happened in this PR: https://github.com/nix-rust/nix/actions/runs/11051131303/job/30700376034
```
error: empty lines after outer attribute
--> src/sys/socket/mod.rs:1799:1
|
1799 | / /// incoming ICMP packet.
1800 | |
1801 | | // On aarch64 linux using recvmmsg and trying to get hardware/kernel timestamps might not
1802 | | // always produce the desired results - see https://github.com/nix-rust/nix/pull/1744 for more
1803 | | // details
1804 | |
| |_
1805 |   #[cfg(any(linux_android, target_os = "freebsd", target_os = "netbsd"))]
1806 | / pub fn recvmmsg<'a, XS, S, I>(
1807 | |     fd: RawFd,
1808 | |     data: &'a mut MultiHeaders<S>,
1809 | |     slices: XS,
...    |
1814 | |     XS: IntoIterator<Item = &'a mut I>,
1815 | |     I: AsMut<[IoSliceMut<'a>]> + …
```
=> style: make clippy happy

.cirrus.yml, .github/actions/test/action.yml, CONTRIBUTING.md, Cargo.toml
https://github.com/nix-rust/nix/pull/2091 left developer experience in a bad state: as far as tools are concerned by default - the project is broken. `cargo test` fails with lots of bogus errors, `rust-analyzer` ignores majority of the code, etc. 
This PR tries to address this problem by explicitly enabling all the features for the `nix` crate in dev mode and making sure they will be added manually to the list by removing explicit `--all-features` from a few places.
According to [cargo docs](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html) path-only dev dependencies are allowed and will be ignored when publishing the crate.
With this change in place I can run tests with usual `cargo test`, `rust-analyzer` and other tools work as expected.
=> Developer experience - enable all the features when running tests by default

changelog/2520.changed.md, src/sys/socket/mod.rs
Made fields in `nix::sys::socket::UnknownCmsg` public.   
This change will allow user to implement custom parsing for unsupported message, such as `SOL_IP, IP_RECVORIGDSTADDR`.
=> Make fields in UnknownCmsg public

changelog/2524.changed.md, src/sys/socket/mod.rs
Instead of a Vec, to avoid forcing an allocation.
`cmsg_space!` now creates a zero initialized vec (instead of a zero-len vec with capacity): this way callsites do not need to be changed.
I tried to change `cmsg_space!` to create a fixed sized array (instead of a Vec) but run into:
```
error: constant expression depends on a generic parameter
--> test/sys/test_socket.rs:2907:26
|
2907 |         let mut cspace = cmsg_space!(libc::sock_extended_err, SA);
|                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Fixes #2523
=> recvmsg: take slice for cmsg_buffer

changelog/2526.added.md, src/sys/mman.rs
Same status as Linux, a no-op, but in the future can be useful for architectures which need this feature.
=> sys::mman: enables MAP_STACK flag for netbsd too.

Cargo.toml, changelog/2529.added.md, src/sys/socket/mod.rs, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
This adds a new API for `getsockopt` around `libc::LOCAL_PEERTOKEN` following https://github.com/rust-lang/libc/pull/3929. The return type definition is the low-level [`audit_token_t`](https://developer.apple.com/documentation/kernel/audit_token_t) as defined in [`osfmk/mach/message.h`](https://github.com/apple-oss-distributions/xnu/blob/8d741a5de7ff4191bf97d57b9f54c2f6d4a15585/osfmk/mach/message.h#L741) and taken from [`endpoint-sec-sys`](https://crates.io/crates/endpoint-sec-sys). A small test was added for it.
=> MacOS socket audit token

src/sys/epoll.rs
Corrects the deprecation message of `epoll_ctl()`, and closes #2531.
=> docs: correct epoll_ctl deprecation message

src/lib.rs
=> chore: fix typo in lib.rs

changelog/2476.changed.md, src/sys/event.rs, src/sys/memfd.rs, src/sys/signal.rs, test/sys/test_event.rs, test/sys/test_memfd.rs
=> Rename Flags EventFlag and MemFdCreateFlag

test/test_sendfile.rs
Fixes a clippy warning on the latest nightly
=> Clippy cleanup: needless as_bytes

changelog/2539.added.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
Adds the `TCP_FUNCTION_BLK` socket option, used to set or query a socket's TCP stack, on FreeBSD only
=> Add the TCP_FUNCTION_BLK socket option, on FreeBSD

changelog/2548.added.md, src/pty.rs, src/sys/eventfd.rs, src/sys/fanotify.rs, src/sys/inotify.rs, src/sys/signalfd.rs, src/sys/timerfd.rs
Implements `Into<OwnedFd> for x` (Actually, it is `From<x> for OwnedFd` due to the clippy rule [clippy::from_over_into](https://rust-lang.github.io/rust-clippy/master/index.html#from_over_into)) for types that are **simply owned file descriptors**.
Types like [Dir](https://docs.rs/nix/latest/nix/dir/struct.Dir.html), do not only contain a file descriptor, so they are not included in this PR.
=> feat: impl Into<OwnedFd> for owned fd types

.github/workflows/ci.yml, Cargo.toml, src/dir.rs, src/fcntl.rs, src/sys/mman.rs, src/sys/signal.rs, src/sys/socket/mod.rs, src/sys/termios.rs, src/syslog.rs, src/unistd.rs, test/sys/test_stat.rs, test/sys/test_termios.rs, test/test_pty.rs, test/test_sendfile.rs
Disables some tests for Solaris.
test/test_sendfile.rs:
Solaris, sendfilev() doesn't support AF_UNIX sockets. Instead, it expects an AF_INET or AF_INET6 sockets.
=> Solaris: fixes build and tests, adds CI

changelog/2556.added.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs, test/test.rs
This allows users to define their own sockopts, instead of needing to make a PR to Nix for every single one.
Fixes #577
=> Make sockopt_impl! public

changelog/2555.added.md, src/sys/mman.rs, test/sys/test_mman.rs
Is meant to be used with `MREMAP_MAYMOVE` and allow to not unmapping `old_address`.
=> sys::mman: adding `MREMAP_DONTUNMAP` flag for mremap on Linux.

changelog/2557.fixed.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
On FreeBSD, getsockopt appends a single NUL to the returned string.  On Linux, it pads the entire buffer with NULs.  But both of those behaviors may be version-dependent.  Adjust GetOsString to handle any number of NUL characters.
=> Exclude NUL characters from OSStrings returned by getsockopt

changelog/2558.added.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
to complete `TCP_FUNCTION_BLK` as to get the alias name, if existent, of the TCP stack.
=> sys::socket adding GetOnly `TCP_FUNCTION_ALIAS` for freebsd.

src/unistd.rs
I was reviewing some unsafe code using libc directly for these functions, and it took me some time to figure out what nix actually has wrappers from them so we can avoid using unsafe. These aliases would have made it much easier for me to discover these functions.
=> Add doc aliases for `getpw{nam,uid}`

changelog/2559.added.md, src/sys/mman.rs, test/sys/test_mman.rs
- `MADV_PAGEOUT` which reclaim the address range, swapping it out if the page is anonymous or written back to disk if it's backed up by a file.
- `MADV_COLD` which deactivate the address range but as a hint.
- `MADV_WIPEONFORK` after `fork()`, the address range is wiped out to avoid sharing sensible data between processes.
- `MADV_KEEPONFORK` disables `MADV_WIPEONFORK` workflow.
=> sys::mman: adding few madvise flags.

changelog/2563.added.md, src/sys/eventfd.rs
Allow creating an `EventFd` from an `OwnedFd` acquired from another process.
Fixes #2561
=> Add from_owned_fd constructor to EventFd

changelog/2565.added.md, src/sys/mman.rs
More specialised than MmapFlags::MAP_POPULATE, another difference being it does not silently fail.
- `MADV_POPULATE_READ` to pre-populate pages ahead of read accesses.
- `MADV_POPULATE_WRITE` to pre-populate pages ahead of subsequent writes.
=> sys::man adding `MADV_POPULATE_READ` and `MAP_POPULATE_WRITE`.

changelog/2566.added.md, src/pty.rs, src/sys/fanotify.rs, src/sys/inotify.rs, src/sys/signalfd.rs, src/sys/timerfd.rs
A PR that follows #2563, add:
```
impl Wrapper {
pub unsafe fn from_owned_fd(fd: OwnedFd) -> Self
}
```
For all the remaining `OwnedFd` wrapper types.
=> feat: add unsafe fn from_owned_fd() for owne fd wrapper types

changelog/2562.added.md, src/sys/socket/mod.rs
- Adds the `Sctp` variant to the `SockProtocol` enum, allowing the user to create SCTP sockets with either `SockType::Stream` or `SockType::SeqPacket`.
- (Linux Only) Expose `MSG_NOTIFICATION` through `MsgFlags` so that it won't be truncated when converting from `i32`.
`IPPROTO_SCTP` is defined in [RFC-6458](https://datatracker.ietf.org/doc/html/rfc6458), but it is not supported by all OSs.
I've cfg'd-out targets that failed in CI.
`MSG_NOTIFICATION` is Linux-specific, as far as I can tell, but is not exposed through Android's libc, so I've limited it to `linux` and not `linux_android`.
=> Add Sctp protocol and MSG_NOTIFICATION

changelog/2569.added.md, src/fcntl.rs, test/test_fcntl.rs
Set/clear the amount of read ahead for the file descriptor.
=> nix::fcntl add FcntlArg::F_READAHEAD for freebsd.

src/ifaddrs.rs
The existing code accidentally dropped the possibly already existing owned value.
=> Don't use `Cow::<str>::to_string`

changelog/2572.added.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
```c
#define SO_LINGER 0x0080 /* linger on close if data present (in ticks) */
#define SO_LINGER_SEC 0x1080 /* linger on close if data present (in seconds) */
```
=> sys::socket adding sockopt::LingerSec for Apple targets.

changelog/2573.added.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
Disallow multiple sockets to bind to an address/port combination.
=> sys::socket::sockopt, adding `ExclBind` for solarish systems.

changelog/2580.added.md, src/sys/ioctl/linux.rs, src/sys/ioctl/mod.rs, src/sys/mod.rs
Fuchsia now supports the linux-style ioctl api.
=> Add ioctl support for Fuchsia

changelog/2579.added.md, src/syslog.rs
This follows up https://github.com/nix-rust/nix/pull/2537 and refers to https://github.com/nix-rust/nix/issues/413.
cc @SteveLauC
=> Impl syslog::setlogmask

changelog/2581.added.md, src/sys/socket/mod.rs
Respectively `sys::socket::SockProtocol::EthIp`,
`sys::socket::SockProtocol::EthIpv6` and
`sys::socket::SockProtocol::EthLoop` if we want more refined filtering as opposed to the existing `sys::socket::SockProtocol::EthAll` which captures everything.
=> sys::socket adding Linux packet filtering on ipv4/ipv6/loopback traffics

changelog/2582.changed.md, src/unistd.rs, test/test_unistd.rs
Add a second type parameter to `linkat` to allow the two paths to have different backing types.
----
I'm unsure if this warrants additional tests, or if it qualifies as an API change. (I guess it technically is, but it doesn't change the usage in any way.)
LMK if I need to add either, or if there are other instances of this (unintentional(?) type parameter re-use) that I can clean up.
=> unistd: allow `linkat` to take multiple path types

src/sys/signal.rs, src/sys/statfs.rs
"extern" without an ABI is deprecated.  So we need to explicitly use "extern C".
=> Fix warnings on nightly regarding "extern" functions

.github/workflows/ci.yml
Disable MIPS CIs because they are broken, see #2593
=> ci: disable MIPS Linux CIs

src/sys/aio.rs, src/sys/ioctl/mod.rs, src/sys/socket/addr.rs, src/sys/socket/sockopt.rs
Clippy cleanup:
1. doc_overindented_list_items
* src/sys/aio.rs
* src/sys/socket/addr.rs
* src/sys/socket/sockopt.rs
2. macro_metavars_in_unsafe
* src/sys/ioctl/mod.rs
=> refactor: clippy cleanup doc_overindented_list_items and macro_metavars_in_unsafe

src/pty.rs, src/unistd.rs
Resolves the issue reported in [this comment](https://github.com/nix-rust/nix/issues/586#issuecomment-2620124046)
=> docs: doc that signal-unsafe fns can be called after execve

src/spawn.rs, test/test_spawn.rs
According to the POSIX man page:
> Otherwise, no child process shall be created, the value stored into the variable pointed to by a non-NULL pid is unspecified, and **an error number shall be returned as the function return value to indicate the error**.
`Error::result()` assumes the function returns -1 on error, so it won't work here.
Actually, this is my fault 🤦‍♂️, the implementation in PR #2007 handled this correctly, but my erroneous review comment led the PR in the wrong direction.
Also, since `posix_spawn()` uses `fork()` (can be other syscalls depending on the impl) under the hood, its tests should grab the `FORK_MTX` lock.
These 2 posx_spawn*() interfaces have not been released, so no changelog needed.
=> fix: posix_spawn returns errno on error, not -1

src/spawn.rs
The `path` argument of `posix_spawn()` is a path, we should use our `NixPath` trait here. Change its type from `&CStr` to `&P where P: NixPath + ?Sized`
This interface has not been released, so no changelog is needed.
=> refactor: change posix_spawn path arg to use NixPath

Cargo.toml, test/test_spawn.rs
1. Add tests for `posix_spawn()`. Before this PR, the tests only cover `posix_spawnp()`
2. Add negative tests cases (the binary to exec does not exist) for both `posix_spawn()` and `posix_spawnp()`
=> test: test posix_spawn() and add negative test cases

changelog/2587.fixed.md, src/lib.rs, src/sys/ioctl/linux.rs, src/sys/memfd.rs, src/sys/mman.rs, src/sys/mod.rs, src/sys/personality.rs, src/sys/ptrace/linux.rs, src/sys/statfs.rs, src/sys/time.rs, src/time.rs, src/ucontext.rs, test/sys/mod.rs, test/sys/test_aio_drop.rs, test/sys/test_pthread.rs, test/test.rs
This PR fix some compilation errors for OpenHarmony. I'll try to explain the following changes.
1. The basic c library for OpenHarmony is forked from musl(1.25), so it's reasonable for us to follow the musl condition compilation.
2. According to the [document](https://developer.huawei.com/consumer/en/doc/harmonyos-references-V5/musl-peculiar-symbol-V5), some symbols don't export. So `aio` and `mqueue` should be hidden for OpenHarmony.
3. OpenHarmony support more enum for `memfd`, the following code is the content of `memfd.h`:   
```c
/****************************************************************************
****************************************************************************
***
***   This header was automatically generated from a Linux kernel header
***   of the same name, to …
```
=> feat(ohos): fix some compilation errors and add some features

.github/workflows/ci.yml, README.md, changelog/2599.added.md
Add OpenHarmony target into CI and Update documents.
The official support:  arm64,arm and x86_64, so i add three targets:
- aarch64-unknown-linux-ohos
- armv7-unknown-linux-ohos
- x86_64-unknown-linux-ohos
=> feat(ci): add OpenHarmony CI and add it to tier2

src/poll.rs, src/sys/epoll.rs
`impl TryFrom<i16> for PollTimeout` uses a custom error (`PollTimeoutTryFromError`), but the error type is not public so handling this error is not really possible. All this PR does is making the type public.
Normally something complains when you try to use private type in a public interface, not sure why is it not happening here.
=> Reexport crate::poll_timeout::PollTimeoutTryFromError;

src/sys/mman.rs, test/sys/test_sockopt.rs
Clippy cleanup: https://rust-lang.github.io/rust-clippy/master/index.html#ptr_eq
=> chore: clippy cleanup ptr_eq

src/sys/signal.rs
Change to use `sa_sigaction` instead of `sa_union.__su_sigaction`, now that the `libc` crate implementation for AIX defines `sa_sigaction` as a direct member of `struct sigaction`, aligning it with implementations on other similar platforms. (https://github.com/rust-lang/libc/pull/4250).
=> Use sa_sigaction instead of sa_union.__su_sigaction for AIX

Cargo.toml, build.rs, src/dir.rs, src/errno.rs, src/fcntl.rs, src/features.rs, src/net/if_.rs, src/sys/mman.rs, src/sys/mod.rs, src/sys/resource.rs, src/sys/signal.rs, src/sys/socket/addr.rs, src/sys/socket/mod.rs, src/sys/socket/sockopt.rs, src/sys/statfs.rs, src/sys/termios.rs, src/sys/uio.rs, src/syslog.rs, src/unistd.rs, test/sys/mod.rs, test/sys/test_pthread.rs, test/sys/test_resource.rs, test/sys/test_socket.rs, test/sys/test_sockopt.rs, test/sys/test_stat.rs, test/sys/test_uio.rs, test/test_fcntl.rs, test/test_net.rs, test/test_unistd.rs
This PR adds cygwin target support.
Tracking:
=> feat: add cygwin support

changelog/2611.added.md, src/sys/socket/mod.rs, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
Respectively FIL_ATTACH/FIL_DETACH to bind/unbind a filter to a socket to for example delay connection acceptance until data (datafilt) is received.
=> socket::sockopt adding SOL_FILTER level options for illumos.

changelog/2603.added.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
Enables the TcpMaxSeg socket option for apple targets. I've tested this on MacOS, not sure about iOS but I imagine it would work just the same.
Here's some code I used to verify that it works:
```rust
use nix::sys::socket::{getsockopt, setsockopt, sockopt::TcpMaxSeg};
use std::{io::Write, net::TcpStream};
fn main() {
// Open a socket to somewhere
let mut socket = TcpStream::connect(("127.0.0.1", 1234)).unwrap();
// Set the MSS
setsockopt(&socket, TcpMaxSeg, &523).unwrap();
// Read the MSS
let maxseg = getsockopt(&socket, TcpMaxSeg).unwrap();
println!("maxseg: {maxseg}");
// Send a large amount of data and observe that the segments are not bigger than 523 bytes
socket.write_all(&[0x77; 2000]).unwrap();
}
```
=> Enable TcpMaxSeg `setsockopt` option for apple targets

Cargo.toml, test/sys/test_sockopt.rs, test/sys/test_uio.rs
Update test dependency `rand` to 0.9. I did this locally to test on cygwin previously, but now I decide to contribute it to upstream:)
- No APIs nodified.
=> test: update rand

changelog/2627.added.md, src/sys/ptrace/linux.rs, test/sys/test_ptrace.rs
to retrieve the very system call which stopped the process. Can be found the type of calls and their related informations. e.g. on exit we get the return value of the call.
=> sys::ptrace: adding ::syscall_info() for linux/glibc.

changelog/2620.added.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
The existing PeerCredentials (SO_PEERCRED) sockopt provides the PID of the process connected to a socket, but PIDs are inherently racy, leading to confused deputy problems. The pidfd mechanism solves this by using a FD to refer to a process which the kernel can keep proper track of.
This patch implements Get/Set<OwnedFd> to be able to receive a FD from getsockopt and implements sockopt::PeerPidfd (SO_PEERPIDFD) returning an OwnedFd representing the process connected to the socket.
=> Add sockopt::PeerPidfd (SO_PEERPIDFD) sockopt support to socket::sockopt

changelog/2621.added.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
Set a BPF program to the socket to set how packets are handled within the reuseport group.
=> socket::sockopt AttachReusePortCbpf for Linux addition.

.github/workflows/check_new_changelog.yml, .github/workflows/ci.yml, Cargo.toml, src/lib.rs, test/sys/test_prctl.rs
1. In our CI, pin libc to 0.2.171 on hurd to work around this issue: https://github.com/rust-lang/libc/issues/4421
2. Bump CI runner images, Ubuntu-20.04 is deprecated. 
3. Ignore test `test_prctl::test_set_vma_anon_name` under QEMU due to #2418
4. Allow `clippy::unwrap_or_default` as IMHO it is overly opinionated
=> ci: downgrade libc to 0.2.171 in CI for hurd

changelog/2631.removed.md, src/poll.rs
`PollFd` implementing `Copy` makes it easy to accidentally refer to the wrong object after putting one into an array.
This PR removes `Copy` from `PollFd`. This fixes #2630.
=> Remove Copy from PollFd

examples/getifaddrs.rs, src/sys/socket/addr.rs, test/sys/test_socket.rs, test/sys/test_sockopt.rs
Fixes a compiler warning with the latest nightly
=> Clippy cleanup: dangerous_implicit_autorefs

Cargo.toml, README.md
Fuchsia timeline:
- **nix &lt;0.20.0**: no support for fuchsia
- **nix 0.20.0 – 0.26.1**: successful docs for `x86_64-fuchsia`
- https://docs.rs/nix/0.20.0/x86_64-fuchsia/nix/index.html
- https://docs.rs/nix/0.26.1/x86_64-fuchsia/nix/index.html
- Rust 1.68.0 renames `x86_64-fuchsia` to `x86_64-unknown-fuchsia`
- https://github.com/rust-lang/rust/pull/106429
- https://github.com/rust-lang/rust/pull/106636
- **nix 0.26.2 – 0.29.0**: no build for `x86_64-fuchsia`, but successful for everything else
- failure: https://docs.rs/crate/nix/0.29.0/builds/1230030/x86_64-fuchsia.txt
> adding target x86_64-fuchsia for toolchain nightly
> running \`Command { std: CARGO_HOME="/home/cratesfyi/workspace-builder/cargo-home" RUSTUP_HOME="/home/cratesfyi/workspace-builder/rustup-home" …
=> Fix fuchsia target triple to unbreak docs.rs build

src/sys/mman.rs, src/sys/mod.rs
This fixes compilation of sys::mman on Redox and allows it to be enabled with the mman feature
=> Compile sys::mman on Redox

Cargo.toml, changelog/2642.removed.md, src/dir.rs, src/fcntl.rs, src/mqueue.rs, src/sys/aio.rs, src/sys/eventfd.rs, src/sys/fanotify.rs, src/sys/select.rs, src/sys/signal.rs, src/sys/signalfd.rs, src/sys/socket/mod.rs, src/sys/socket/sockopt.rs, src/sys/termios.rs, test/sys/test_signal.rs, test/test_fcntl.rs
* Fix the `test_fcntl::test_posix_fallocate::success` test with recent ZFS
* Remove the `PartialEq` and `Eq` implementations from `SigHandler`
* Clippy cleanup: mismatched_lifetime_syntaxes
* Fix a rustdoc warning on the latest nightly
* Suppress Clippy::doc_overindented_list_items
See individual commit messages for details
=> Address multiple CI failures

src/sys/signal.rs, test/sys/test_aio.rs
This test deliberately makes an invalid syscall.  Rust no longer allows us to even construct an invalid enum (even with `unsafe`), so alter the test to get EBADF instead of EINVAL.
=> Fix the sys::test_aio::aio_fsync::error test on recent rust nightly

changelog/2674.fixed.md, src/dir.rs
readdir_r does not work well on systems where {NAME_MAX} can vary.  The main reason to use it is for thread-safety.  However, POSIX 1003.1-2024 Issue 8 makes readdir_r obsolete and clarifies that readdir must be thread-safe except when concurrent calls are made to the same directory stream.  So all applications should prefer it now.  The original rationale for Nix using readdir_r[^1], in addition to thread safety, was that the Rust standard library used it.  But that is no longer the case.  So Nix should switch to plain readdir.
The second problem is that on some operating systems, libc::dirent is an
open-ended structure where the last field (d_name) has a size of 1 byte,
but additional data follow the end of the structure.  Nix currently
relies on copying the libc::dirent structure, …
=> fix two problems in the Dir module:

changelog/2653.fixed.md, examples/ptrace.rs, src/sys/ptrace/linux.rs
It fixes `ptrace::syscall_info`, which is currently broken (at least on Linux 6.12.31).
See the commit message for more details.
The following program panics when built against `master` and behaves correctly (i.e. it does not panic and prints valid syscall info) when built against this branch:
```rust
fn main() {
let pid = unsafe { nix::unistd::fork().unwrap() };
match pid {
nix::unistd::ForkResult::Child => {
nix::sys::ptrace::traceme().unwrap();
nix::sys::signal::raise(nix::sys::signal::Signal::SIGCONT).unwrap();
println!("I'm issuing a syscall!");
}
nix::unistd::ForkResult::Parent { child } => {
nix::sys::wait::waitpid(Some(child), None).unwrap();
nix::sys::ptrace::setoptions(child, nix::sys::ptrace::Options::PTRACE_O_TRACESYSGOOD)
.unwrap();
nix::sys::ptrace::syscall(child, …
```
=> Fix syscall_info

changelog/2655.fixed.md, src/sys/mman.rs
The AIX signature of `madvise()` differs from the POSIX specification, which expects `void *` as the type of the `addr` argument, whereas AIX uses `caddr_t` (i.e., `char *`). This patch casts `addr` inside the `nix` wrapper `madvise()` to smooth it out.
=> Cast the 'addr' argument of 'madvise()' for AIX
