nix-rust/nix

src/sched.rs, src/sys/signal.rs, src/sys/utsname.rs, src/unistd.rs, tests/unistd.rs
- Updated array syntax
- task_rng -> thread_rng
=> Track rust master

.travis.yml
To be sure everything is fine at least on Linux
=> Added travis tests

Cargo.toml, src/lib.rs
refs https://github.com/rust-lang/rust/pull/21254
=> Fix for `bitflags!`

src/unistd.rs, test/test_mq.rs, test/test_unistd.rs
Just some cleanups for the mq unit tests.
Next step is adding the missing mq functions and more tests.
=> cleaned up mq unit tests

src/errno.rs, src/fcntl.rs, src/features.rs, src/sys/ioctl.rs, src/sys/mman.rs, src/sys/mod.rs, src/sys/signal.rs, src/sys/socket/consts.rs, src/sys/termios.rs
Some of the tests are currently unrunnable, but the basic library is at least
buildable with this patch.
=> Basic OpenBSD support.

test/test_unistd.rs
Now a new PR hopefully without problems (I messed up my git repo somehow).
Just one line to make it compile and run tests successfully on Linux (I have Ubuntu 15.04.)
=> make execvpe unit test compile on  Linux

src/mqueue.rs, test/test_mq.rs
This is the 2nd attempt for mq_getattr which hopefully solves the broken stack problem.
Now again without Box and stack allocated.
I have added a c_long[4] array to the MqAttr as this is there on Linux systems. Without it the memory is corrupt and some unit tests result in an error with Signal 4 (which is very bad!).
See 
/usr/include/linux/mqueue.h
Again, please carefully review this. mq_open is now also changed to take varargs (...) which is how it works in Linux.
(/usr/include/mqueue.h)
If this is ok, added the remaining mqueue functions should be a lot easier and I will be able to complete the mqueue support for nix-rust.
=> added mq_getattr for Linux (2nd try)

src/sched.rs
In fact function returns pid of new process (or tid of new thread)
The signature of the function change, but it's only return value changed from returning nothing to `pid_t` so I believe that I believe that the amount of code it may break is low.
On the other hand I don't even understand how to use `clone` that does *not* return id of newly created process (may be useful for threads?)
=> Fix signature of linux `clone` function

src/lib.rs, src/mqueue.rs, src/unistd.rs
- add fsync, fdatasync
- fix some comments
- add implementations of `From` and `Error` for `nix::Error`
=> Add fsync, fdatasync; fix some comments

src/sys/select.rs, test/sys/test_select.rs
Part of #270, fixed according to @kamalmarhubi's comments.
=> select(2) fixes

nix-test/build.rs
Signed-off-by: Paul Osborne <osbpau@gmail.com>
=> test: clean up the test build script

src/sys/uio.rs
Refs https://github.com/nix-rust/nix/issues/264
=> uio: Use bindings from libc instead of our own

.travis.yml, ci/run-travis.sh
Signed-off-by: Paul Osborne <osbpau@gmail.com>
=> travis: only require sudo on docker/i686 builds

test/test_mount.rs
The mount test runner uses unprivileged user namespaces. Previously,
failure from `unshare(2)` to create the user namespace would fail the
test. This changes that to simply print an error and exit successfully.
Refs https://github.com/nix-rust/nix/pull/326
=> mount: Do not treat unshare(2) failure as test failure

.travis.yml
The problem in the repo line in the travis config, I guess it hasn't been updated since ownership was transferred. See: https://travis-ci.org/nix-rust/nix/jobs/131751025#L614
Should resolve #320 
Thanks!
=> Fix deployment of docs from travis.

CHANGELOG.md
As [requested by @fiveop](https://github.com/nix-rust/nix/pull/416#issuecomment-245709257)
=> Update CHANGELOG for pull request 416

CHANGELOG.md, src/sys/event.rs
This is a rebase of @asomers work on master to resolve a merge conflict so we can get things merged up.
=> Asomers kevent

CHANGELOG.md
Add note about CLONE_NEWCGROUP from pull request #457 to CHANGELOG.md.
Signed-off-by: Dylan Reid <dgreid@chromium.org>
=> Update CHANGELOD.md to include CLONE_NEWCGROUP

.travis.yml
=> Fail on beta builds again.

README.md
=> Add link to release documentation

CONVENTIONS.md, Cargo.toml, src/fcntl.rs, src/macros.rs, src/mount.rs, src/mqueue.rs, src/poll.rs, src/sched.rs, src/sys/epoll.rs, src/sys/event.rs, src/sys/eventfd.rs, src/sys/memfd.rs, src/sys/mman.rs, src/sys/quota.rs, src/sys/signal.rs, src/sys/signalfd.rs, src/sys/socket/consts.rs, src/sys/socket/mod.rs, src/sys/stat.rs, src/sys/statvfs.rs, src/sys/termios.rs, src/sys/wait.rs
=> Update bitflags to 0.7

src/sys/signal.rs
See: https://git.musl-libc.org/cgit/musl/tree/src/time/timer_create.c#n126
=> Fix unresolved name error when building with musl.

CHANGELOG.md, Cargo.toml, README.md
=> Release v0.8.0

README.md
Replaces #598.
cc @kamalmarhubi
=> Add gitter link to README

Cargo.toml
Bump the version to 0.9.0-pre
Update libc dependency to 0.2.25
=> Prepare for the 0.9.0 release

CHANGELOG.md
=> Add CHANGELOG entry for PR #661

CHANGELOG.md
Missed this when merging #672.
=> Fix changelog from bad merge

.gitattributes
see also: https://about.gitlab.com/2015/02/10/gitlab-reduced-merge-conflicts-by-90-percent-with-changelog-placeholders/
=> use better merge algorithm for CHANGELOG.md

CHANGELOG.md, src/fcntl.rs, test/test_fcntl.rs
=> Add support for 'fallocate'

src/errno.rs, src/sys/aio.rs
Blocking on rust-lang/libc#850 for Android support.
=> More libc ffi

CHANGELOG.md
Forgot to mention the big changes in #833 before it was merged.
=> Update CHANGELOG for #833

Cargo.toml
=> Start the next dev cycle

src/unistd.rs
Correct references to user ids to group ids. Fixes #945
=> Fix #945 - documentation fix

src/sys/socket/mod.rs
> Every great project needs great documentation
...one step at a time though :)
=> Add example for setsockopt

src/sys/socket/addr.rs, src/sys/socket/mod.rs, test/sys/test_socket.rs, test/test_mq.rs, test/test_poll.rs, test/test_stat.rs, test/test_unistd.rs
Fixes #992.
Don't merge this yet. I have more testing to do. I just am pushing it up for others.
=> Don't reference packed structs.

Cargo.toml
Also, bump the tempfile dependency so it will be using the same version
of rand.
Fixes #1026
=> Bump the rand dependency to 0.6

.travis.yml, Cargo.toml
Build test with -Zminimal-versions in CI.
=> Minimal versions

.cirrus.yml, bors.toml
=> Update the FreeBSD CI image to 11.3.

src/unistd.rs
From the man page linked in the description
=> Document O_DIRECT flag for pipe2

.cirrus.yml, bors.toml
And temporarily disable travis targets
=> Update the FreeBSD test image to 11.4-release

Cargo.toml, test/sys/test_sockopt.rs, test/sys/test_uio.rs, test/test_poll.rs
- Update rand to 0.8
- Update tempfile to 3.2.0
- Fix a non_fmt_panic warning with Rustc 1.52.0
=> Various maintenance stuff

src/sys/socket/mod.rs
Fixes https://github.com/nix-rust/nix/issues/1405
=> Allow cmsg_space! to be used in unit tests

src/lib.rs
The old problems with bitflags no longer apply
=> Forbid dead code again

.cirrus.yml
FreeBSD 11.4 will be EoL on 30-Sept
=> Update the FreeBSD CI image

src/sys/uio.rs
=> Fix typo in pread docs

src/sys/inotify.rs, src/sys/mman.rs, src/sys/mod.rs, src/sys/personality.rs, src/sys/reboot.rs, src/sys/timerfd.rs
Document the `inotify`, `mman`, `personality`, `reboot`, and `timerfd` modules.
=> Document inotify, mman, personality, reboot, timerfd

CHANGELOG.md, src/dir.rs
=> Impl `AsRawFd` for `OwningIter`

src/sys/ioctl/linux.rs, src/sys/statfs.rs
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> Fix complation on riscv32

src/sys/socket/addr.rs
=> [skip ci] better docs for SockaddrLike::from_raw

.cirrus.yml, test/sys/test_pthread.rs, test/sys/test_socket.rs, test/test_unistd.rs
=> Clippy cleanup in the tests.

src/dir.rs, src/lib.rs, src/mqueue.rs
Add doc comments for the `dir` and `mqueue` modules.  Also, delete dead code in `mqueue`
=> More docs for dir and mqueue

src/unistd.rs
=> fix '<newline>' being interpreted as html

CHANGELOG.md, src/sys/socket/sockopt.rs, test/sys/test_sockopt.rs
Added socket option wrappers for DiffServ related parameters on Linux
=> Adds IP_TOS, IPV6_TCLASS and SO_PRIORITY sockopt wrappers for Linux

src/sys/select.rs, test/sys/test_select.rs
1. Adds I/O safety for module `sys/select`.
=> feat: I/O safety for 'sys/select'

src/sys/signal.rs
Signed-off-by: Xiaobo Liu <cppcoffee@gmail.com>
=> fix: linux+mips+uclibc unreachable pattern

src/sys/socket/mod.rs
=> fix: clippy::size_of_ref

README.md
Put targets into a table.
<table>
<tr><th>Before</th><th>After</th></tr>
<tr><td><img alt="image" src="https://user-images.githubusercontent.com/16856679/208483287-e39c218c-0a5c-4cf8-9fc2-b9ab5408ce28.png"></td><td><img alt="image" src="https://user-images.githubusercontent.com/16856679/208483421-53743623-e43b-40d4-8b36-83e570326b56.png"></td></tr>
</table>
=> Target table

src/mount/linux.rs
Also, deprecate a few flags that should not be used by userland.
=> Document the mount.linux module

src/unistd.rs
=> setgroups type mismatches on Solaris #1986

Cargo.toml
Updates memoffset to version 0.9
=> Update memoffset to 0.9

CHANGELOG.md
=> Update CHANGELOG for patch release 0.26.2

Cargo.toml, src/macros.rs, src/mount/bsd.rs, src/mount/linux.rs, src/mqueue.rs, src/sys/event.rs, src/sys/stat.rs, src/sys/statvfs.rs, src/sys/termios.rs, src/sys/time.rs, src/unistd.rs, test/sys/test_socket.rs
This is a new major version and requires some code changes.
=> Update to bitflags 2.2.1.

.cirrus.yml, Cargo.toml, src/dir.rs, src/sys/socket/mod.rs, src/sys/uio.rs
Clippy found some const-correctness issues in internal APIs, but nothing user-facing.
=> Clippy cleanup

Cargo.toml
https://github.com/Stebalien/tempfile/issues/246
=> Fix Haiku build by updating tempfile to 3.7.1

Cargo.toml
=> Enable all features when building on docs.rs

README.md
=> Add a maintenance-status badge to the README

CONTRIBUTING.md
=> Updated CONTRIBUTING.md with correct test command

.github/workflows/ci.yml
Try fixing the merge queue issue stated in [this comment](https://github.com/nix-rust/nix/pull/2138#issuecomment-1807458160)
=> CI: fix merge queue

src/sys/termios.rs
Apply the cfg aliases for sys/termios.rs
Ref: #2188
=> refactor: cfg for termios.rs

src/unistd.rs
Apply the cfg aliases for unistd.rs
Ref: #2188
=> refactor: cfg for unistd.rs

src/sys/ioctl/mod.rs, src/sys/ptrace/bsd.rs, src/sys/ptrace/mod.rs
Apply the cfg aliases for
* sys/ioctl/*.rs
* sys/ptrace/*.rs
Ref: #2188
=> refactor: cfg for ioctl/* & ptrace/*

src/sys/socket/addr.rs
=> refactor: cfg for socket/addr.rs

build.rs
=> Adds `netbsdlike` as cfg alias

.github/workflows/ci.yml
https://github.com/nix-rust/nix/issues/2306
=> Temporarily disable CI on GNU hurd

CONVENTIONS.md
Update the example code block in `CONVENTIONS.md` to use cfg alias.
=> docs: update code block in CONVENTIONS.md to use cfg alias[skip ci]

.github/workflows/ci.yml
=> Temporarily disable CI on Haiku

changelog/2355.added.md, src/pty.rs, test/test_pty.rs
=> feat: impl AsFd for PtyMaster

src/sys/statfs.rs, src/sys/time.rs
Revert #2344 since [the upstream issue](https://github.com/rust-lang/rust-clippy/issues/12537) has been fixed.
=> style: revert #2344 as the issue has been fixed

RELEASE_PROCEDURE.md
Updates the release procedure.
=> docs: update release procedure[skip ci]

src/fcntl.rs, src/sys/stat.rs, src/unistd.rs
Update the documents of those `xxat()` functions.
=> docs: update docs of xxat() fns

.github/workflows/ci.yml
The std build issue has been fixed, it should work now.
Closes #2441
=> ci: enable haiku CI

src/sys/eventfd.rs, src/sys/mod.rs
Document module `sys/eventfd`.
=> docs: document sys/eventfd

.github/workflows/ci.yml
Try enabling the Hurd CI to see if the problem is fixed or not.
=> ci: enable hurd CI

.github/workflows/ci.yml
=> ci: diable hurd ci

src/fcntl.rs
=> Fix a doc comment typo
