nix-rust/nix

src/errno.rs
src/fcntl.rs
src/lib.rs
src/sys/mman.rs
src/sys/stat.rs
src/unistd.rs
src/utils.rs

- ToCStr removal
- split of `Show` and `String` traits 
- `globs` feature is enabled by default

ToCStr removal fallout

---

src/errno.rs
src/fcntl.rs
src/lib.rs
src/mount.rs
src/sys/mman.rs
src/sys/stat.rs
src/sys/utsname.rs
src/unistd.rs
src/utils.rs

I checked out the cstr-fallout [branch](https://github.com/carllerche/nix-rust/pull/44)  by @vhbit but I found a few more things needed to be updated, like src/mount,   also src/sys/utsname.rs's to_str needed to be reworked because those functions don't exist anymore.

more cstr-fallout

---

src/sys/ioctl.rs
src/sys/mod.rs

I'm using the same approach as [fcntl](https://github.com/carllerche/nix-rust/blob/da900c6932254fa5e3b2a44b3ac9160fd275d261/src/fcntl.rs#L93) (which I found to be extremely interesting).
The following code prints the correct size when running on an interactive shell on Mac and Linux.
```rust
extern crate nix;
use nix::sys::ioctl;
fn main() {
let mut ws = ioctl::Winsize { ws_row: 0, ws_col: 0, ws_xpixel: 0, ws_ypixel: 0 };
ioctl::ioctl(0, ioctl::TIOCGWINSZ(&mut ws)).unwrap();
println!("{:?}", ws);
}
```

Add `ioctl`. Only supports the `TIOCGWINSZ` request right now.

---

src/fcntl.rs
src/mount.rs
src/sys/stat.rs
src/unistd.rs
src/utils.rs

The build is currently broken on nightly due to the introduction of the new Path API (which doesn't yet support conversion to `&[u8]` as far as I can see).
This fixes the build by continuing to use the old Path API.
(This should become unnecessary if #56 is merged).

path -> old_path

---

src/unistd.rs

This PR fixes the [current compilation error][current-gist] as seen on `rustc 1.0.0-nightly (522d09dfe 2015-02-19) (built 2015-02-20)`. It uses `std::marker::PhantomData` to stop the compiler from complaining that `ToRead` and `ToWrite` are never used.
[current-gist]: https://gist.github.com/teotwaki/75131a4fa281d1b28e88

Mark T as Phantom in Iovec

---

src/sys/signal.rs

This is done because interrupted execution has soundness bugs regarding
thread-local storage. Fixes #90.

Make `sigaction` unsafe

---

src/sys/ioctl.rs

Two problems were fixed:
1. All of the comments for the module were prefixed with `///!` instead
of just `//!`
2. There was no newline before lists which is required in markdown, so
they were not rendering correctly.

docs: fix module documentation for ioctl

---

src/sys/socket/consts.rs
src/sys/socket/mod.rs

libc::funcs::bsd43::shutdown is used

Add socket::shutdown function

---

src/sys/epoll.rs

A timeout of -1 makes epoll block indefinitely, a usize timeout means we can't specify this behavior; using isize fixes this.

Change epoll_wait to use isize timeout_ms.

---

src/sys/uio.rs
test/sys/test_uio.rs

This adds pread and pwrite. I'm unsure if these should take a `RawFd` or
a `&File`. The latter has the benefit that the user can't accidentally pass
e.g. a fd representing a pipe or a socket, but it complicates things if the
caller only has a RawFd and no associated `File` object. What do you think?

Add pwrite and pread

---

Cargo.toml

libc::TCP_KEEPIDLE is not defined for linux in libc v0.1.4, so this bump will alleviate that issue.

Bump libc dependency up to version 0.1.8

---

src/sys/signal.rs

Fixes #140  This current implementation follows the struct definition for __sigaction in [include/sys/signal.h](http://www.opensource.apple.com/source/xnu/xnu-2782.1.97/bsd/sys/signal.h).  This changes it to the implementation to ```sigaction``` expected by the sigaction function in include/signal.h.

Remove sa_tramp from macos sigaction

---

test/sys/test_uio.rs

Fix the boundary condition so that we never call
Rng::gen_range(64, 64).
Helps #144

Fix off-by-one error calling Rng::gen_range

---

test/test_stat.rs

$ stat baz
File: ‘baz’
Size: 0         	Blocks: 16         IO Block: 4096   regular empty file
Device: 26h/38d	Inode: 6835152     Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/ posix4e)   Gid: ( 1000/ posix4e)
Access: 2015-07-10 11:11:21.846851777 -0700
Modify: 2015-07-10 11:11:21.846851777 -0700
Change: 2015-07-10 11:11:21.846851777 -0700
Birth: -

Fix unit tests as blank files can still have blocks

---

Cargo.toml
src/fcntl.rs

Adds basic support for calling flock().
I could see going further and adding the equivalent of std::sync::Mutex's MutexGuard for automatic unlocking at the end of scope. Not sure if that would fit with the rather low-level nature of Nix, though.

Add flock(2) support

---

.travis.yml
nix-test/src/const.c
src/sys/socket/consts.rs
src/sys/socket/ffi.rs
src/sys/socket/mod.rs
test/sys/test_socket.rs

The best specification for control message layout appears to be [RFC 2292, section 4](https://tools.ietf.org/html/rfc2292#section-4), despite this not being a wire protocol. These definitions have also been checked against glibc 2.19 <bits/socket.h> and Linux 4.0 <linux/socket.h>, and tested on Debian 8.1 and FreeBSD 10.2 x86_64.
The API differs a bit from the cmsg(4) API for type-safety reasons (and also because the cmsg(4) API is terrible). See test/sys/test_socket.rs for an example.
Only supports SCM_RIGHTS at the moment.
Fixes #88.

Add support for sendmsg(2), recvmsg(2), and cmsg(4)

---

nix-test/src/const.c
src/sys/socket/consts.rs
src/sys/socket/ffi.rs
src/sys/socket/mod.rs
test/sys/test_socket.rs

I've confirmed that the following changes fix the reported Valgrind problem with PR #179, on both Linux and OS X 10.8.5 amd64:
```patch
@@ -122,3 +122,3 @@ struct cmsghdr {
pub cmsg_type: c_int,
-    cmsg_data: [size_t; 0]
+    cmsg_data: [type_of_cmsg_len; 0]
}
@@ -286,4 +286,6 @@ impl<'a> ControlMessage<'a> {
pub fn sendmsg<'a>(fd: RawFd, iov: &[IoVec<&'a [u8]>], cmsgs: &[ControlMessage<'a>], flags: SockMessageFlags, addr: Option<&'a SockAddr>) -> Result<usize> {
+    let mut len = 0;
let mut capacity = 0;
for cmsg in cmsgs {
+        len += cmsg.len();
capacity += cmsg.space();
@@ -317,3 +319,3 @@ pub fn sendmsg<'a>(fd: RawFd, iov: &[IoVec<&'a [u8]>], cmsgs: &[ControlMessage<'
msg_control: cmsg_buffer.as_ptr() as *const c_void,
-        msg_controllen: cmsg_buffer.len() as size_t,
+ …
```

Add support for sendmsg(2), recvmsg(2), and cmsg(3), take 2

---

src/sys/socket/mod.rs

This is unfortunate, but some socket types (ie netlink on linux) require protocol argument to be set.
See #202

socket(): add protocol argument (breaking change)

---

src/sched.rs
src/sys/signal.rs
src/sys/syscall.rs

I would like to get aarch64 support merged in. It compiles successfully when targeting `aarch64-unknown-linux-gnu` Also tested through a project using mio which I have actually run on a machine using this architecture.

add aarch64 support

---

src/lib.rs

This is a stop gap improvement until the NixPath reform is figured out.
refs #221

Implement NixPath for str and OsStr

---

Cargo.toml
src/lib.rs
src/mount.rs
test/test_mount.rs

Fixes https://github.com/carllerche/nix-rust/issues/85

Bring back mount

---

src/sched.rs
src/sys/mman.rs

More bitflags

---

src/sys/mman.rs

Fixes building nix for platforms like ARM
See https://github.com/rust-lang-nursery/libc/blob/33bfefe027b7ccc67225428cfd8203dc380515f4/src/unix/notbsd/linux/mod.rs#L319

cfg out MAP_32BIT on non-x86

---

src/sys/signal.rs

This will fix the build on pre-1.6.0 Rust.

signal: Allow raw_pointer_derive on SigAction struct

---

src/mqueue.rs
test/test_mq.rs

Part of https://github.com/nix-rust/nix/pull/270, fixed according to @kamalmarhubi's comments.

mqueue: change types to allow more cases

---

src/unistd.rs

New syscalls

---

CONTRIBUTING.md

This gives us a place to point new contributors, as well as to document
our project practices.

Add a document with contribution guidelines

---

Cargo.toml

Bumped bitflags version to 0.4 and removed warning about derive with raw pointer

Bumped bitflags version to 0.4 and removed warning

---

CONVENTIONS.md
README.md

I have added new sections to the file. I would like the usual suspects to read them critically and offer critique.
When have agreed to add certain versions I will add Issues to track our progress in getting the code to follow the conventions. For two of the sections they already exist in #254 and #264.

Add introduction/constants/enumeration/uninitialized to CONVENTIONS.

---

src/lib.rs

On currently nightly I got an error regarding the public export of libc in sys::ioctl. It now requires us to import the extern crate publicly.

Make crate libc import public.

---

src/sys/signal.rs

Use libc constants in sys/signal.rs.

---

.travis.yml

Currently, several of the tests are failing intermittently.  After
some research it appears that these failures only occur when thread
parallelism is enabled (as is the case by default).  To test, I just
ran the failing tests over and over.  I would consistently see errors
when running the following:
$ while true; do target/debug/test-7ec4d9681e812f6a; done
When I forced single threaded execution, I no longer saw failures:
$ while true; do RUST_TEST_THREADS=1 target/debug/test-7ec4d9681e812f6a; done
I was mostly looking at the test_unistd failures which make calls out
to fork() and then make subsequent calls to wait().  In that case there
is one parent and the wait() called could (and frequently does) get some
random child pid back because it just happened to terminate.  That is
why when …

testing: increase stability by removing thread parallelism

---

Cargo.toml
src/lib.rs
src/unistd.rs

Refs https://github.com/nix-rust/nix/issues/264

unistd: Use bindings from libc instead of our own

---

CONTRIBUTING.md

Initial ideas for these will be E-good-first-bug and E-mentor.

Add E-prefixed issue labels for level of experience

---

Cargo.toml
src/unistd.rs
test/test_unistd.rs

I tested this under linux, and I noticed that this seems to also be built for OSX. It would be appreciated if someone could test this under OSX.
I'm not familiar enough with rust to know if there is a way of integrating this without creating a sub-crate.

Add gettid

---

src/sys/signal.rs

After #292 was merged, this flakiness remained. I observe it only on
Darwin, hence the targetted disabling until there's been more
investigation.

tests: Disable test_sigwait on apple platforms

---

src/sched.rs
src/sys/syscall.rs

Add support for MIPS targets

---

src/lib.rs

With rust 1.7, the following warning was being emitted by the compiler:
warning: `pub extern crate` does not work as expected and should
not be used. Likely to become an error. Prefer `extern crate` and
`pub use`.
Based on https://github.com/rust-lang/rust/issues/26775 it appears that
this change is the current best approach for properly exporting the
libc dependency so it may be used outside of nix.
Signed-off-by: Paul Osborne <osbpau@gmail.com>

libc: re-export libc properly

---

src/sys/signal.rs

Some left over ffi function that can be replaced now that we have libc 2.8.

Use sigwait function from libc instead of own ffi function.

---

src/sys/termios.rs

This fixes an import that was missed in the upgrade from libc 0.1 series
to 0.2 series.
Refs https://github.com/nix-rust/nix/issues/298

android: Fix reference to libc::ioctl

---

src/sys/signal.rs

Rename flags to conform to conventions.

---

.travis.yml
CONTRIBUTING.md
Cargo.toml
README.md
ci/README.md
ci/cargo-config
ci/run-all.sh
ci/run-docker.sh
ci/run-travis.sh
ci/run.sh

These commits contain the first portion of new infrastructure that will allow us to build for and test on a much larger set of platforms.  Nix and the tests are *not* compiling on many platforms right now, but I believe at this point that most of those problems are issues with nix (or libc) rather than the test infrastructure.
I want to get this out there so we can start filing issues and other people can start doing testing and development to resolve the issues popping up on various platforms.  None of this is integrated in with travis at this point -- that will be phase 3.  Phase 2 will be getting qemu going to run the tests for non-host platforms (this might be tricky when running in a container as `/dev/kvm` might need to be passed through).
This is based on the testing infrastructure …

Docker cross test infrastructure

---

ci/run-all.sh

Somewhere in the last set of changes, a few references to
`test_nix` were not removed.  Since that function doesn't exist,
the tests would never be run on those targets.
This script is only used when testing locally right now.
Signed-off-by: Paul Osborne <osbpau@gmail.com>

testing: remove refs to test_nix in run-all.sh

---

CONVENTIONS.md
src/lib.rs
src/macros.rs
src/sys/mman.rs

We define many bitflags types with values from the libc crate. Currently
these look like this:
bitflags!{
flags ProtFlags: libc::c_int {
const PROT_NONE      = libc::PROT_NONE,
const PROT_READ      = libc::PROT_READ,
const PROT_WRITE     = libc::PROT_WRITE,
const PROT_EXEC      = libc::PROT_EXEC,
#[cfg(any(target_os = "linux", target_os = "android"))]
const PROT_GROWSDOWN = libc::PROT_GROWSDOWN,
#[cfg(any(target_os = "linux", target_os = "android"))]
const PROT_GROWSUP   = libc::PROT_GROWSUP,
}
}
There's some repetition which is tedious. With the new macro, the above
can instead be written
libc_bitflags!{
flags ProtFlags: libc::c_int {
PROT_NONE,
PROT_READ,
PROT_WRITE,
PROT_EXEC,
#[cfg(any(target_os = "linux", target_os = "android"))]
PROT_GROWSDOWN,
#[cfg(any(target_os = "linux", …

Add libc_bitflags convenience macro

---

src/lib.rs
src/sys/mod.rs
src/ucontext.rs

The module wraps context handling related functions and structs.

Add context module.

---

.travis.yml
ci/run-all.sh
ci/run.sh

See the individual commit message for more detail.  ARM is now passing (but we don't run mount tests any more when in the docker container).  For x86_64/i686, there were some changes in the posborne/rust-cross stuff.

Fix arm and x86 ci

---

src/sys/epoll.rs

EPOLLEXCLUSIVE flag is available in Linux4.5.

epoll: Add EPOLLEXCLUSIVE flag.

---

src/sys/socket/addr.rs
test/sys/test_socket.rs

socket: Respect IPv6 flowinfo and scope_id in InetAddr::from_std

---

src/unistd.rs
test/sys/test_wait.rs
test/test_mq.rs
test/test_unistd.rs

This changes the name of the enum returned by `fork()` to `ForkResult`,
and changes the `Parent` variant to be struct-like.
The result can be matched like
use nix::unistd::ForkResult::*;
match fork().unwrap() {
Parent { child } => { ... }
Child => { ... }
}
using the shorthand matching syntax for struct-like enum variants.
This is a breaking change.

unistd: Redesign the enum returned by fork()

---

Cargo.toml
build.rs
src/sys/signal.rs

This commit adds a small build script to detect if we need to
`#[allow(raw_pointer_derive)]` and makes the attribute conditional.
Refs #337

Fix raw_pointer_derive warning

---

src/features.rs
src/mqueue.rs
src/sys/ptrace.rs
src/sys/socket/addr.rs
src/unistd.rs

Just a few style nits. Hope it'll be useful anyway :smile:

fixed a few clippy warnings

---

src/mount.rs

Ref #264
Changing internal usage of `ffi::mount` and `ffi:umount` to make use of libc.

mount: Use bindings from libc instead of our own

---

src/sched.rs

This is necessary because of compiler changes. For further information
look at rust-lang/rust#19925.
This solves #346.
I know that there are other problems with the affected function. We are thinking about how to best pass the arguments to the function and we don't want to define the ffi's ourselves. However, I would like to get the warning out of our tree as soon as possible. We do not need to wait for our polish.

Cast function item to function pointer in order to appease compiler.

---

src/sys/stat.rs

Also reordered just because I wasn't sure where to insert the new ones.

Add some missing SFlags

---

src/sched.rs

This is my suggestion on how to fix #343.

Allow to specify signal when calling clone.

---

src/fcntl.rs

**Un-finished** and looking for help. As #264 was tagged "mentor, good first bug"
Ref #264
I couldn't find `F_GET_SEALS`, or `F_ADD_SEALS` in libc.
Is this a case where I should be making a PR over there? I'm not sure where exactly to address it in libc.

fcntl: Use bindings from libc instead of our own

---

Cargo.toml
src/lib.rs
src/unistd.rs

Indicates that these methods cannot return successfully. This does introduce a new dependency; an empty enum could be used instead but then you would lose the convenience `unreachable` methods exposed by the `void` crate, and standardizing on one type, etc...

Use Void in exec return type

---

src/sys/socket/mod.rs

Add support for converting AF_NETLINK  sockaddr_nl addresses to
Sockaddr::Netlink(). This lets socket::recvmsg() work on netlink
sockets.

Support sockaddr_nl in sockaddr_storage_to_addr().

---

src/sys/socket/consts.rs
src/sys/socket/sockopt.rs

In Linux, the SO_ORIGINAL_DST socket option can be used to get the original destination, which can be needed if the connection is translated by a NAT, i.e. iptables. In C, this information can be obtained by ``getsockopt(fd, SOL_IP, SO_ORIGINAL_DST, &remote, &remote_len)`` and returns a ``sockaddr_in`` struct. I've added a binding for this option.
Thanks!

Add SO_ORIGINAL_DST

---

src/unistd.rs

This fixes an warning made error on nightly builds.

Use Wrapping for intended underflow of unsigned integer value.

---

src/sys/signal.rs

In preparation of turning them into an enumeration.

Add missing signals.

---

.travis.yml

Fix a typo in the target name for the config of ``mipsel-unknown-linux-gnu``. Build will probably still fail though, but will hopefully get further :wink:
Thanks!

Fix a typo in travis config.

---

src/ucontext.rs

It looks like ``libc`` doesn't provide ``libc::getcontext`` or ``libc::setcontext`` when targeting musl, so I've excluded the ``ucontext`` module from being built when targeting musl which allows the module to be built successfully.
Thanks!

Exclude UContext::get(),set() on musl, not available from libc.

---

src/unistd.rs
test/test_unistd.rs

I have added lseek and seek64 to unistd, the last one targeting Linux/Android only. I wasn't sure where to place the Whence enum, or if it's a nice of doing, I am quite fresh to Rust.

Added lseek and seek64

---

src/sys/signal.rs
src/sys/wait.rs

This is work in progress. I post this pull request as a request for discussion. I mark the lines I have doubts or ideas about.
Ignore the first commit. It is the same as PR #361, which I wanted to base this change off.

Signal enum

---

src/ucontext.rs

musl target needs std::mem now

---

Cargo.toml
src/sys/wait.rs

My understanding is that this flag is required by POSIX, so all systems should allow for it

Add missing wait flag WUNTRACED for non-Linux systems

---

src/sys/eventfd.rs

This commit revamps to eventfd to follow nix conventions:
- drop in-crate FFI definitions
- rename EventFdFlag to EfdFlags
Additionally, it changes the initval argument to be a libc::c_uint,
matching the actual type.

eventfd: Follow nix conventions

---

Cargo.toml

As mentioned by @fiveop in #363,
> We should use the Github version of libc for development and a fixed version for releases.
So this changes the required libc version to GitHub's master.
The dependency is supposed to be manually changed to a fixed version when doing a release, out of the GitHub repository (i.e. nix's master always tracks libc's master).

Use git master as libc version

---

src/sys/mod.rs
src/sys/reboot.rs

This adds support for calling [reboot(2)](http://linux.die.net/man/2/reboot) on Linux (useful for implementing PID 1!).
* **Testing**: I can't imagine how this could be tested other than manually, which is what I did to ensure it works.
* **libc**: for some reason libc includes neither `reboot()` function, nor `RB_*` constants, so I had to hack-define them here. Should I open a bug/PR against the libc crate?
* **API**: I went with `reboot()` function for restarting, powering off, halting, etc. and an additional `set_cad_enabled()` function for enabling/disabling Ctrl-Alt-Delete, which still corresponds to `reboot()` C call, but has different semantics and return type. (But I'm open to suggestions here -- maybe it would be better to separate each action into its own function, i.e. …

Add reboot() support on Linux

---

CHANGELOG.md
CONTRIBUTING.md
CONVENTIONS.md
RELEASE_PROCEDURE.md

- Added initial CHANGELOG.md with Changes from Version 0.6.0 and the
upcoming changes for version 0.7.0.
- Added RELEASE_PROCEDURE.md detailing what changes should be made
to CHANGELOG.md during a release.
- Added sections about CHANGELOG.md in CONVENTIONS.md and
CONTRIBUTIONS.md.

Introduce CHANGELOG.md

---

.travis.yml

Since tempdir is broken on Rust 1.1 I propose to push the minimum supported Rust version to 1.2.

No longer support Rust 1.1

---

ci/run.sh

Newer version of docker no longer have the /.dockerinit file present
when the container is executing, so that is no longer an option.
When executing in a container, we do know that we will be executing
as pid 1 -- this is probably not ever the case on the host system.
r? @fiveop

ci: fix docker container check

---

src/fcntl.rs

https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man2/fsync.2.html

Add FcntlArg::F_FULLFSYNC

---

CHANGELOG.md
src/sched.rs

Not exporting `CpuMask` anymore, should be the only API change of this PR. Since the type is not used in any other exported signature or type, I think it is fine to no longer export it.
r? @kamalmarhubi @posborne

Replace parts of ffi module by libc functions ind sched.rs

---

CHANGELOG.md
src/poll.rs
test/test_poll.rs

I'll add a change log commit, once this is reviewed.

Use libc in poll.rs

---

CHANGELOG.md
src/lib.rs
src/mqueue.rs
test/test_mq.rs

This is almost finished. I still need to check if I introduced any breaking changes by changing signatures. I would want to record this in the change log, however, for that we still need to merge #391.

Replace ffi module by libc functions in mqueue.rs

---

src/unistd.rs
test/test_unistd.rs

As a (late) followup of [this withdrawn PR](https://github.com/rust-lang/libc/pull/326) I have added getcwd (wrapper around `libc::getcwd`) and mkdir (wrapper around `libc::mkdir`) and added testing.
A few notes:
- I'm new to rust so I would appreciate some pair of eyes testing the code, plus I'm open for revision of code or general remarks about my coding style
- I have run the tests both on OSX as on Linux (Ubuntu)
- I've run `clippy` to see if my code is well formatted, however clippy issues many warnings about the project. I think I didn't add any more warnings
- the methods in unistd are not documented so I also left out the documentation of `getcwd` and `mkdir`, although I think it'd probably be good to add some documentation, especially some example code how to use the methods
- …

add unistd::getcwd and unistd::mkdir

---

RELEASE_PROCEDURE.md

Mention the libc version changes in RELEASE_PROCEDURE.md

---

RELEASE_PROCEDURE.md

I decided against adding a line for a local test of the commit, because we have the full build in the CI and you might miss something locally anyway.

Small fixes to RELEASE_PROCEDURE.md

---

src/sys/epoll.rs

In order to get @kubo39's PR #384 forward, I cleaned up the commit history a bit and added `EpollEvent` back.
Since this module is used by mio, maybe @carllerche could comment on these changes.

Add epoll_create1

---

CHANGELOG.md
src/unistd.rs

A first shot at fixing https://github.com/nix-rust/nix/issues/414. This approach keeps the old implementation for platforms other than `notbsd`, because `libc` only exposes `pipe2` in the `notbsd` module.
I've tested this by hand on my Linux machine in a couple ways:
- Create a toy program that opens a pipe and passes it to `cat`, which hags if `O_CLOEXEC` doesn't get set properly. Confirm that it doesn't hang, but that it does if I pass `0` as the flags to `libc::pipe2`.
- Delete the new implementation entirely, and delete the `cfg` guards on the old implementation, and confirm that above is still true.
I haven't actually tested a cross compilation build though. Is there a standard way to do that?

call pipe2 directly on Linux

---

src/sys/signal.rs

This is the only failing error when cross compiling to Tessel, which is a MIPS-based architecture. 
Apparently libc does not have SIGSTKFLT (Term Stack fault on coprocessor) on this system, and indeed it does not have a coprocessor.
This commit should preserve the semantics for all other architectures. Potentially this can be inverted in the future if more platforms are added to only *whitelist* ARM, x86, x86_64, but I thought this conditional would suffice.

Removes SIGSTKFLT when cross-compiling to MIPS.

---

.travis.yml

@kamalmarhubi @posborne, is that alright with you? I would let the Issue #435 open, till this is reverted, once we have a working beta again.

Temporarily allow beta failures till 1.13.0-beta.3 or later is released

---

.travis.yml
CHANGELOG.md
Cargo.toml

Supporting older versions of rust is causing CI to fail and is
a somewhat constant support burden with questionable value.  1.7.0
is the oldest I have seen that people have had a requirement on
supporting in recent history.
It may make sense to work toward a more official policy on
what version of rust we will support in the future.  Users of
older version of rust are, of course, welcome to use older versions
of nix and everything else in the ecosystem.
r? @kamalmarhubi @fiveop

ci: drop official support for rustc < 1.7.0

---

test/sys/test_uio.rs

Use tempfile in test_pwrite so as not to pollute the source directory.

use tempfile in test_pwrite

---

test/test_mount.rs

Looks like Travis allows bind mounts in their container infra now.

mount: Run test_mount_bind in CI

---

CHANGELOG.md
src/unistd.rs

These were both recently added to libc, add wrappers.
Signed-off-by: Dylan Reid <dgreid@chromium.org>

Add setresuid and setresgid

---

CHANGELOG.md
src/unistd.rs

Add a `getpgid` function to nix.
Argument is required, either pass in `None` or `Some(pid_t)`. It should have the same behavior
as the `libc` one.

add getpgid call

---

src/lib.rs
src/unistd.rs

This series of commits starts to fill in documentation that was not previously present for various calls, mostly in unistd for this pass.
r? @kamalmarhubi

Documentation improvements

---

src/unistd.rs

This is a second round of doc additions.  There are also some funcitonal changes to APIs for getting/setting hostname that need to be reviewed.
r? @nix-rust/nix-maintainers

Additional documentation additions

---

src/sched.rs

This is a new option to clone added earlier this year.  It was already added to rust/libc.

Add CLONE_NEWCGROUP

---

CHANGELOG.md
src/sys/signal.rs
test/sys/mod.rs
test/sys/test_signal.rs
test/sys/test_wait.rs

Make signal argument to kill optional

---

test/sys/test_uio.rs
test/test_mount.rs

Cleans up after 0fa7250b9575a2746519a854d0138c4c8255f109 and 40351db00da6ee8c904f47599ee692a85e3d96ef.

Get rid of a few test compilation warnings

---

CHANGELOG.md
src/sys/event.rs

This matches NetBSD's C definitions.  Other operating systems define
it as void*, despite not really being a pointer, but none actually
define it as uintptr_t.  Better to be right on NetBSD and wrong
everywhere else than wrong everywhere.  Plus, it's what mio expects.
Please include this PR in nix 0.8.0

Change KEvent to treat udata as an intptr_t instead of a uintptr_t.

---

CHANGELOG.md
src/sys/signal.rs

Addresses #459.
This is a breaking change.
Should SigFlags be renamed to something more sensible?

Change SigFlags into an enum.

---

test/sys/test_select.rs

Sometimes, on a heavily laden system, select would timeout and the test would
fail.  Fix it by removing the timeout.

Fix intermittency in test_select

---

.travis.yml

Libraries we depend on need newer versions of Rust. The current
stable release is 1.13.
This also disables the CI for the platforms/architectures MIPS, ARM
and Android. This cannot be helped as long as the test infrastructure
only runs on 1.7.

Allow failures of 1.7 builds

---

CHANGELOG.md
src/sched.rs

The current implementation assumes that the array passed by the caller is word aligned (which I don't think Rust guarantees for [u8]) and a multiple of the word size.

Ensure child stack passed to clone is 16 byte aligned.

---

src/sys/socket/mod.rs

Since rust-lang/rust#23425 is closed, we no longer need the special
case.

Always use libc's socketaddr_storage

---

src/sys/socket/mod.rs

copy_bytes updates dst so that it points after the bytes that were just
copied into it. encode_into did not advance the buffer in the same way
when encoding the data.
See #473

Fix ControlMessage::encode_into when encoding multiple messages

---

CHANGELOG.md
src/unistd.rs

These changes have been previously discussed some with #452 but we decided it made sense to separate things out a bit more.
r? @kamalmarhubi @fiveop

Gethostname sethostname updates

---

CHANGELOG.md
src/unistd.rs
test/test_unistd.rs

This introduces a wrapper for fchdir(2), allowing a process to change
directory based on an open file descriptor.
The underlying function is available in libc crate since 0.2.20.

unistd: add fchdir(2)

---

CHANGELOG.md
src/sys/aio.rs
src/sys/mod.rs
src/sys/signal.rs
src/sys/time.rs
test/sys/mod.rs
test/sys/test_aio.rs

POSIX AIO is a standard for asynchronous file I/O.  Read, write, and
fsync operations can all take place in the background, with completion
notification delivered by a signal, by a new thread, by kqueue, or not
at all.
The SigEvent class, used for AIO notifications among other things, is
also added.

Add POSIX AIO support

---

src/sys/wait.rs

Adds new WaitStatus value `PtraceEvent`. Implementation of #273 that only affects Linux/Android.

wait: Support ptrace events for Linux

---

CHANGELOG.md
src/sys/stat.rs

It appears that the previous `mkdev` was based on the kernel headers (https://github.com/torvalds/linux/blob/v4.7/include/linux/kdev_t.h#L6) which (I guess) is the internal kernel dev_t. Scrolling down the file you can see some bitshifting operations to do conversions.
The new implementation(s) are based on [musl](http://git.musl-libc.org/cgit/musl/tree/include/sys/sysmacros.h?id=dbbb3734d8c0176feabd6c46e2e85bbc3b8a60af) and [glibc](https://github.molgen.mpg.de/git-mirror/glibc/blob/20003c49884422da7ffbc459cdeee768a6fee07b/sysdeps/unix/sysv/linux/sys/sysmacros.h#L38), which are in agreement about how dev_t should be handled.
(as it happens I suspect we could omit the shift by 32 since I don't see that in the kernel headers, but doesn't hurt to take the conservative route and mimic the …

Implement major/minor macros, correct mkdev

---

CHANGELOG.md
src/fcntl.rs
src/lib.rs
src/mount.rs
src/sys/epoll.rs
src/sys/event.rs
src/sys/mman.rs
src/sys/quota.rs
src/sys/signal.rs
src/sys/signalfd.rs
src/sys/stat.rs
src/sys/wait.rs

Prefer `libc_bitflags!` over `bitflags!`. Prefer `libc::CONSTANTS` over
writing the constant manually.
This makes #501 unnecessary, since upstream now contains the `O_TMPFILE` constant.

Fix the style for bitflags!

---

README.md

I think this is important for 2 reasons:
1) Users know if they can use this library
2) Developers know what Rust features they can use in merge requests
What this doesn't do is establish any kind of policy for raising the Rust requirements, which is something  worth addressing in the near-future.

Specify Rust minimum version requirements

---

src/sys/epoll.rs

This is possible now that EPOLLEXCLUSIVE was added to libc in
https://github.com/rust-lang/libc/pull/526

epoll: Use libc_bitflags for EpollFlags

---

src/sys/epoll.rs
src/sys/signal.rs

With this nix builds for mipsel-unknown-linux-gnu.

Remove EPOLLWAKEUP and SIGEV_THREAD_ID when cross-compiling to MIPS.

---

CHANGELOG.md
src/poll.rs

This will currently fail CI, as the necessary changes haven't hit libc yet. That is tracked in rust-lang/libc#537. This does build on my computer using the changes tracked on that PR, so I'd appreciate any visual review of this code as it should be "done".
I also wanted to get this submitted so hopefully it'd be in the queue for the 0.8 release.

Add ppoll()

---

src/sys/termios.rs

Addresses nix-rust/nix#531
`speed_t` definition for bsd now aliases `libc::speed_t`
This should let CI pass for `x86_64-unknown-freebsd`.
Further changes should be implemented for `linux` and all other constants defined in `libc`.  I can continue on with those changes here or create a new issue/pull request.

Switched bsd speed_t def. to libc::speed_t

---

src/sys/event.rs
src/sys/termios.rs

Passes on `x86_64-unknown-netbsd`: https://travis-ci.org/berkowski/nix/jobs/205609553

Fixes nix-rust/nix#532

---

README.md

This is largely because of features used in `tempfile` from 1.8 and 1.9. This was tested locally, so we'll see what CI says.
This does bring up the issue of the CI testing in the `ci` folder. That specifies the rust version as 1.7.0, but then when I looked at the docker images they seemed to only support 1.10, so maybe someone can comment on whether anything should be done about those things.

Update minimum rust version to 1.9.0

---

CHANGELOG.md
src/sys/aio.rs
src/sys/signal.rs
test/sys/test_aio.rs

- Turn most `aio_*` functions into `AioCb` methods
- Add runtime checks to `AioCb` methods
- Implement `Drop` for `AioCb`

Improve AIO API

---

CHANGELOG.md
src/fcntl.rs

This allows importing them directly from `nix::fcntl` which is more
ergonomic than needing to use them via `FcntlArg`.

fcntl: Expose FcntlArg variants at the module level

---

CHANGELOG.md
src/poll.rs
test/test_poll.rs

I could've used a `0i16`here as well but I liked the better semantics of `empty()`.

Remove revents from PollFd::new

---

CHANGELOG.md
src/sys/mman.rs

The nix::sys::mman::mmap documentation says
> Calls to mmap are inherently unsafe, so they must be made in an unsafe
block.
however, the function was not actually marked unsafe.
* `munmap` should also be `unsafe` for obvious reasons.
* `madvise` should be `unsafe` because of the `MADV_DONTNEED` flag.
* `mlock` was already marked `unsafe`
* `munlock` and `msync` don't strictly need to be `unsafe` despite
taking pointers AFAICT, but are marked `unsafe` for consistency and in
case they add additional flags in the future.
[breaking-change]

Actually mark mmap and related functions as `unsafe`

---

Cargo.toml

My previous pull request was merged too early and contained
my own libc fork with outstanding pull requests. As the pull requests
are now merged, this commit restores the libc git repo.

Cargo.toml: restore upstream libc remote

---

CHANGELOG.md
src/sys/socket/consts.rs
src/sys/socket/sockopt.rs
src/sys/syscall.rs
src/sys/termios.rs

Addresses nix-rust/nix#534
One test failing:
```
failures:
---- sys::test_select::test_select stdout ----
thread 'sys::test_select::test_select' panicked at 'assertion failed: `(left == right)` (left: `1`, right: `0`)', test/sys/test_select.rs:45
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failures:
sys::test_select::test_select
test result: FAILED. 57 passed; 1 failed; 0 ignored; 0 measured
error: test failed
```
This failure is consistent.  I suspect it may stem from the `nix` implementation of `fd_set`, but nothing immediate jumps out as a cause.

Compile on all travis platforms

---

.travis.yml
CONTRIBUTING.md
bors.toml

@homu has served us well, but is unmaintained. @bors will serve us in
its stead.
Fixes https://github.com/nix-rust/nix/issues/580

Replace homu with bors-ng

---

Cargo.toml
test/sys/test_aio.rs
test/test.rs

Adds a mutex to protect access to SIGUSR2 signal handlers by the AIO
tests.
Fixes #578

tests should protect concurrent access to signal handlers

---

CHANGELOG.md
src/sys/aio.rs
test/sys/test_aio.rs

The existing AioCb constructors work for simple programs where
everything is stored on the stack.  But in more complicated programs the
borrow checker can't prove that a buffer will outlive the AioCb that
references it.  Fix this problem by introducting
AioCb::from_boxed_slice, which takes a reference-counted buffer.
Fixes #575

Add AioCb::from_boxed_slice

---

CONTRIBUTING.md
ci/script.sh

This adds `--cfg=travis` to builds under CI, allowing tests to be
conditionally ignored by marking them with
#[cfg_attr(travis, ignore)]
refs #568

ci: Allow skipping tests when running under CI

---

CHANGELOG.md

v0.8.1 was released to fix the broken build on FreeBSD. It is v0.8.0
with a859ee3 cherry-picked.                                                                                                                                                                                     
refs #567

Add v0.8.1 to changelog

---

CHANGELOG.md
src/sys/select.rs

The method does not change anything, so I updated the type signature. Tests pass.

select.rs FdSet: method `contains' should not mutate anything

---

bors.toml

The timeout is, by default, one hour. `nix` builds take about that long,
sometimes longer, sometimes shorter, making builds flaky.

Raise the bors timeout to four hours

---

CHANGELOG.md
src/lib.rs
src/pty.rs
test/test.rs
test/test_pty.rs

* grantpt
* posix_openpt
* ptsname/ptsname_r
* unlockpt
I've refactored my code to use these functions and they work correctly at least in the non-error case. Only issue is what to do for failure in `ptsname` when converting strings. This should effectively never happen. I think maybe adding an `Unknown` to the `Error` type and returning that might be useful.

Add various pty functions

---

CHANGELOG.md
src/sys/signal.rs

I want to inspect the old SigAction after installing a new one. This adds getter methods for handler, flags and mask. Returning the old SigAction isn't very useful if we can't read its fields.

Add SigAction getters

---

.travis.yml
README.md
bors.toml

* Gate Bors on the FreeBSD 11 build
* Remove the testless FreeBSD build from Travis
* Promote x86_64-unknown-freebsd to Tier 1
Fixes #603

Integrate the FreeBSD BuildBot

---

.travis.yml
README.md
ci/install.sh
test/sys/test_aio.rs
test/sys/test_select.rs
test/test_mq.rs

These should be issues with QEMU itself and not problems on the actual hardware, but I want to get some upstream tickets filed before merging this. I'm also not sure if this syntax is correct on the `#cfg`, so this is testing that as well.

Skip failing tests for Linux/MIPS/PowerPC

---

CHANGELOG.md
src/pty.rs
test/test.rs
test/test_pty.rs

Lemme know if anything needs to be fixed

Add openpty

---

CHANGELOG.md
src/lib.rs
src/sys/ptrace.rs

Some ptrace functions return structures through the data argument. This commit adds utilities to return data through this mechanism and function specialisations for a few of these functions (getting event messages or the siginfo_t struct). Once the next version of libc is released these utilities will be expanded to include the fpregs and user_regs structs.
Due to the need to use unsafe blocks to utilise these ptrace features I feel these are good candidates for inclusion into rust-nix

Added ptrace utilities.

---

CHANGELOG.md
src/sched.rs

I might be missing something as to why this argument was made `isize`, but there's nothing obvious from the commit history, and other calls that work with thread IDs in this library return `pid_t`, so hopefully this is a nit and not noise.

Change sched_setaffinity's PID argument to pid_t

---

src/fcntl.rs

Those two OSes cannot be together since the following FreeBSD flags aren't available on OpenBSD.
- `O_DIRECT`
- `O_EXEC`
- `O_TTY_INIT`

Separate OpenBSD and FreeBSD in fcntl.rs

---

.travis.yml
README.md
src/sys/ioctl/platform/linux.rs
src/sys/syscall.rs
test/sys/test_ioctl.rs

The test_ioctl values are computed using ioctl-test.c

Support powerpc64

---

test/test_mount.rs

Some versions of that kernel have a known bug with tmpfs in namespaces.
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1659087
Fixes #610

Skip the mount tests on kernel 4.4.0

---

test/test_pty.rs

Some pty tests would fail intermittently because read(2) occasionally
returns less data than requested.

Handle short reads in pty tests

---

.travis.yml
README.md

Add all Android targets as Tier 3 platforms

---

src/sys/socket/consts.rs

Not all values are upstreamed, but this covers the vast majority of them.

Rely on libc for more socket constants

---

.travis.yml
Cross.toml

I actually couldn't find a reference to CARGO_TEST_THREADS in the
current cargo codebase, but RUST_TEST_THREADS is definitely correct.
This should reduce some spurious failures on some platforms.

Use single threads for testing

---

.travis.yml
README.md
ci/install.sh

With this and #639, then we have at least basic testing recurring for all mobile platforms (note that this is more than the `libc` currently tests, so we may have trouble moving the non-x86 targets to Tier2 until that happens).

Add iOS as a Tier 3 platform

---

.travis.yml
CHANGELOG.md
README.md
src/errno.rs
src/macros.rs
src/sys/signal.rs
src/sys/socket/consts.rs
src/sys/socket/mod.rs
src/sys/termios.rs

Allow nix to compile on android

---

CHANGELOG.md
src/sys/ioctl/mod.rs

The kernel expects that the values are passed by value and not by pointer for writing ioctls.

Use pass by value for write ioctls

---

.travis.yml
README.md

I don't know why these weren't added originally. They should work with `cross`.

Add arm/musl, mips64, and s390x linux targets to Tier3

---

.travis.yml
README.md
src/sys/ioctl/platform/linux.rs
src/sys/signal.rs
src/sys/syscall.rs

This handles the low-hanging fruit. rust-lang/libc#654 needs to land and there's a bit of work necessary for the syscall and ioctl errors.

Fix tier3s

---

CHANGELOG.md
src/sys/mod.rs
src/sys/ptrace.rs
test/sys/mod.rs
test/sys/test_ptrace.rs

Nothing that nix currently binds is architecture-specific, and Android
supports ptrace just as much as non-Android Linux.

Enable ptrace on all Linux platforms

---

test/test.rs
test/test_pty.rs
test/test_unistd.rs

std::fs::File closes the underlying file descriptor on Drop, without
checking for errors.  test_lseek and test_lseek64 also manually close
the file descriptor.  That works for single threaded test runs.  But for
multithreaded runs, it causes EBADF errors in other tests.  Fix the
tests by consuming the File with into_raw_fd(), so its drop method will
never be called.

Fix double close bugs in test_lseek and test_lseek64

---

CHANGELOG.md
src/sys/socket/mod.rs
test/sys/test_socket.rs

On macOS, trying to call `sendmsg` with a zero entry cmsgs buffer, e.g.:
sendmsg(fd, [IoVec::from_slice(buf)], &[], MsgFlags::empty(), None)
...fails with `EINVAL`.  This occurs due to the pointer value for zero capacity `Vec`s being 0x1 rather than 0x0, to distinguish allocated-but-zero-size from nullptr.  The [kernel validates](https://github.com/opensource-apple/xnu/blob/dc0628e187c3148723505cf1f1d35bb948d3195b/bsd/kern/uipc_syscalls.c#L1304) both the `msghdr.msg_control` and `msghdr.msg_controllen` fields and rejects `msghdr.msg_control == 0x1` as invalid.
This doesn't show up on Linux because the [kernel validates](https://github.com/torvalds/linux/blob/9705596d08ac87c18aee32cc97f2783b7d14624e/net/core/scm.c#L139) `msghdr.msg_controllen` first and ignores the value of …

Fix sendmsg on macOS when passing a zero entry cmsgs array.

---

.travis.yml
CHANGELOG.md
README.md
src/macros.rs
src/pty.rs
src/sys/mod.rs
src/sys/termios.rs
test/sys/test_termios.rs
test/test_pty.rs

We'll see how this tests on other platforms, but it's supported on BSDs and Linux supposedly.

Add cfmakeraw/cfsetspeed

---

.travis.yml

* Remove sudo: required
* Remove rust=beta build on OSX
* Remove rust=nightly builds

Make Travis faster

---

Cargo.toml
src/pty.rs
src/unistd.rs
test/test_pty.rs
test/test_ptymaster_drop.rs

PtyMaster::drop should panic on EBADF

---

src/pty.rs
test/sys/test_termios.rs

* Make test_tcgetattr deterministic.  The old version behaved
differently depending on what file descriptors were opened by the
harness or by other tests, and could race against other tests.
* Close some file descriptor leaks
Fixes #154

Fix some bugs in the termios tests

---

test/sys/test_aio.rs
test/sys/test_wait.rs
test/test.rs
test/test_mq.rs
test/test_unistd.rs

Fix thread safety issues in aio, chdir, and wait tests
They have four problems:
* The chdir tests change the process's cwd, which is global.  Protect them all with a mutex.
* The wait tests will reap any subprocess, and several tests create subprocesses.  Protect them all with a mutex so only one subprocess-creating test will run at a time.
* When a multithreaded test forks, the child process can sometimes block in the stack unwinding code.  It blocks on a mutex that was held by a different thread in the parent, but that thread doesn't exist in the child, so a deadlock results.  Fix this by immediately calling `std::process:;exit` in the child processes.
* My previous attempt at thread safety in the aio tests didn't work, because anonymous MutexGuards drop immediately.  Fix this by naming …

Make aio, chdir, and wait tests thread safe

---

.travis.yml
README.md

Move `powerpc-unknown-linux-gnu` to Tier 2. And attempt a fix for the epoll tests that seem to fail reliably now.
cc @asomers

Fix testing

---

src/sys/ptrace.rs
test/sys/test_ptrace.rs

In #614 we added specializations of `ptrace()` that added more type safety. As part of this, the `UnsupportedOperation` error was introduced for the requests that are covered by specialized versions so they couldn't be used with the general `ptrace()`. Unfortunately, no tests were added with this PR and so it slipped through that you could not do those operations at all anymore: `ptrace()` reported `UnsupportedOperation` for them and `ptrace_*` called `ptrace`, not `ffi::ptrace` and so also reported `UnsupportedOperation`! Whoops!
This minimally-invasive surgery corrects this by adding tests that call all the specialized `ptrace_*` ignoring the return value save checking for `UnsupportedOperation`. It also changes the functions calls to use `ffi::ptrace()` directly to fix the bug.
As this …

Fix special ptraces

---

Cargo.toml

It's just a (redundant) link to the repo, not a real homepage. According
to the [API
guidelines](https://github.com/brson/rust-api-guidelines#cargotoml-includes-all-common-metadata-c-metadata),
this shouldn't be set in this case.

Remove `homepage` from Cargo.toml

---

test/sys/test_termios.rs
test/test.rs
test/test_pty.rs

ptsname(3) returns a pointer to a global variable, so it isn't
thread-safe.  Protect it with a mutex.

Fix thread safety issues in pty and termios tests

---

CHANGELOG.md
src/sys/wait.rs
test/sys/test_wait.rs

The recommended way to trace syscalls with ptrace is to set the
PTRACE_O_TRACESYSGOOD option, to distinguish syscall stops from
receiving an actual SIGTRAP. In C, this would cause WSTOPSIG to return
SIGTRAP | 0x80, but nix wants to parse that as an actual signal.
Add another wait status type for syscall stops (in the language of the
ptrace(2) manpage, "PTRACE_EVENT stops" and "Syscall-stops" are
different things), and mask out bit 0x80 from signals before trying to
parse it.
Closes #550

Add WaitStatus::PtraceSyscall for use with PTRACE_O_TRACESYSGOOD

---

src/unistd.rs
test/sys/test_wait.rs
test/test_unistd.rs

Some tests were invoking non-async-signal-safe functions from the child
process after a `fork`. Since they might be invoked in parallel, this
could lead to problems.
cc #586

Document safety of `fork()` and fix tests

---

test/sys/test_pthread.rs
test/test_net.rs
test/test_unistd.rs

I tested the crate on an Android emulator and quite all the tests passed. Only 6 were failing.
> failures:
> 
> ---- sys::test_pthread::test_pthread_self stdout ----
> 	thread 'sys::test_pthread::test_pthread_self' panicked at 'assertion failed: tid > 0', test/sys/test_pthread.rs:6
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> 
> ---- sys::test_socket::test_getsockname stdout ----
> 	thread 'sys::test_socket::test_getsockname' panicked at 'bind failed: Sys(EACCES)', /checkout/src/libcore/result.rs:859
> 
> ---- sys::test_socket::test_unixdomain stdout ----
> 	thread 'sys::test_socket::test_unixdomain' panicked at 'bind failed: Sys(EACCES)', /checkout/src/libcore/result.rs:859
> 
> ---- sys::test_termios::test_local_flags stdout ----
> 	thread 'sys::test_termios::test_local_flags' …

fix some tests for Android

---

src/lib.rs

On semi-recent Rust versions (I think 1.8+) this now works properly.
Closes #655

Remove workaround for `pub extern crate`

---

.travis.yml
README.md
test/sys/test_aio.rs
test/sys/test_ioctl.rs
test/test_mq.rs

All of the necessary constants should have been merged in upstream libc, so I wanted to file this PR pre-emptively to check that all constants have been accounted for.

Check tier 3s

---

CHANGELOG.md
src/lib.rs
src/poll.rs
test/test.rs

`poll` functions are defined in Android as well.
libc is missing some constant, but once rust-lang/libc#663 is merged, it'll be good to merge here.
Closes #711

add poll module in Android

---

CHANGELOG.md
src/unistd.rs

Fixes #717 
This PR enables `setresuid` and `setresgid` on FreeBSD and OpenBSD. These functions are not present on NetBSD, macOS, and iOS as far as I can tell.

Enable setresuid/setresgid on FreeBSD and OpenBSD

---

CHANGELOG.md
src/sys/statvfs.rs

* Use upstream libc FFI declarations and constants
* Use more Rust-y interface of returning entire struct versus passing it as an
argument to (f)statvfs.
* Replace field accesses with accessor methods
* Flatten vfs module into parent
* Remove all non-libc-based interfaces for working with the statvfs struct

Refactor statvfs module

---

src/sys/ptrace.rs

This might fail on Mac because of how libc defines ptrace on that platform, but we'll see!

Use upstream libc ptrace FFI

---

.travis.yml

The main issue is that all iOS builds are in a block and there are only 5
simultaneous builds allowed by our Travis CI plan. So if there's a backlog
of iOS builders, then the entire build process stalls. So instead of having
them all clumped together, distribute the Mac and iOS builds throughout the
build pipeline.
Addresses part of #669.

Reorder builds to improve build times

---

src/sched.rs
src/sys/quota.rs
src/sys/signal.rs
src/sys/socket/addr.rs
src/sys/socket/mod.rs
src/sys/socket/sockopt.rs
test/sys/test_socket.rs

Most could be replaced by simple raw pointer casts (or even perfectly
safe coercions!).
cc #373

Get rid of a lot of transmutes

---

CONVENTIONS.md
src/fcntl.rs
src/macros.rs
src/mount.rs
src/mqueue.rs
src/poll.rs
src/sched.rs
src/sys/epoll.rs
src/sys/event.rs
src/sys/eventfd.rs
src/sys/mman.rs
src/sys/quota.rs
src/sys/select.rs
src/sys/signal.rs
src/sys/signalfd.rs
src/sys/socket/mod.rs
src/sys/stat.rs
src/sys/termios.rs
src/sys/utsname.rs
src/sys/wait.rs

Also update a couple of constant declarations while we're at it.

Match syntax of libc_bitflags! with bitflags!

---

CHANGELOG.md
src/unistd.rs
test/test.rs
test/test_unistd.rs

This adds fexecve(). It is available in libc since 0.2.29.
Ref: http://pubs.opengroup.org/onlinepubs/9699919799/functions/fexecve.html

unistd: add fexecve()

---

CHANGELOG.md
src/sys/mod.rs
src/sys/utsname.rs

* Exposes `utsname` on all platforms
* Expose `signalfd` on Android
Closes #607.

Support features across more platforms

---

src/sys/wait.rs

Not certain if these are all correct yet, but we can reuse a ton of logic from `libc` within the `wait` module.

Use libc definitions for wait module

---

CHANGELOG.md
src/pty.rs
test/test_pty.rs

On some platforms, `ptsname()` mutates global variables and mutating
global variables is always considered `unsafe` by Rust.
Reference:
https://github.com/nix-rust/nix/pull/742#issuecomment-324385919

Mark and document pty::ptsname() as unsafe

---

CHANGELOG.md
src/macros.rs
src/sys/ptrace.rs
test/sys/test_ptrace.rs
test/sys/test_wait.rs

Reopening of #734 hence the branch name, changelog will be updated once the pr number of this new pull request is known.

Moved ptrace constants into enum types plus minor additions

---

src/sys/socket/mod.rs
src/sys/socket/sockopt.rs
test/sys/test_socket.rs

Getting this up there to get some CI run on it. Replacing the `msghdr`, `cmsghdr`, and other FFI function declarations will be a little more involved so I wanted to run this through first.

Replace socket FFI with libc versions

---

CHANGELOG.md
Cargo.toml
src/sys/aio.rs
test/sys/test_aio.rs
test/sys/test_aio_drop.rs

Fixed error handling in `AioCb::fsync`, `AioCb::read`, and `AioCb::write`
Previously, the `AioCb`'s `in_progress` field would erroneously be set
to `true`, even if the syscall had an error
Fixes #714
AioCb::Drop will now panic for in-progress AioCb
Printing a warning message to stderr isn't really appropriate, because
there's no way to guarantee that stderr is even valid.  Nor is
aio_suspend necessarily an appropriate action to take.

Fix multiple issues with POSIX AIO

---

CHANGELOG.md
src/sys/socket/mod.rs
src/sys/socket/sockopt.rs

This was implemented as part of my employment, and I have received permission to submit it upstream under my own name.
I implemented this with a bit of copy+pasting from the SCM_RIGHTS implementation, and it appeared to be functional when originally implemented on top of 13deb619c3e0bdf490511cedd848e60633ca3b2d (tagged v0.8.0).

Add support for SO_TIMESTAMP

---

src/mqueue.rs
src/poll.rs
src/pty.rs
src/sys/pthread.rs
src/sys/select.rs
src/sys/signal.rs
src/sys/socket/mod.rs
src/unistd.rs

But leave in place Linux links for non-standard functions.  Also, add
brief docs for some functions that were lacking them.

Replace most Linux man page links with Open Group man page links

---

CHANGELOG.md
src/unistd.rs
test/test_unistd.rs

Since libc has mkfifo already I have just copied mkdir and adapted to mkfifo. I have tested that on MacOS only.

#602 added unistd::mkfifo

---

README.md

We effectively made it Tier1 back in
ec6fe0629df87d8355cbdba8b7a0855934a5ac9e, but never updated the README.

Promote i686-unknown-freebsd to Tier1 in the README

---

src/sys/memfd.rs

This will fail because rust-lang/libc#836 is not merged yet, but just getting it staged for when it is.

Migrate memfd constants to libc

---

CHANGELOG.md
src/sys/ptrace.rs

It is a somewhat newer option -- it requires Linux 3.8. Is there a
more precise way to specify that?

ptrace: add PTRACE_O_EXITKILL option

---

src/sys/aio.rs
src/sys/event.rs
src/sys/reboot.rs
src/sys/signal.rs

Some enums which use different names for values than libc still set the
discriminators manually.
closes #254

Use libc_enum! where possible

---

src/sys/wait.rs

OpenBSD doesn't have `WEXITED`, `WSTOPPED`, or `WNOWAIT`, so omit those
from that platform.

Omit invalid waitpid flags on OpenBSD

---

deploy.sh

No bash-specific feature is used, so deploy script will work
in every POSIX OS, even when bash isn't installed.

Use sh as interpreter

---

CHANGELOG.md
src/sys/socket/addr.rs
test/sys/test_socket.rs

This introduces an `as_abstract()` getter to `UnixAddr` in order to
retrieve the name of an abstract unix socket.
This also adds tests around abstract addresses and clarify docs,
adding explicit semantics.

sys/socket: add UnixAddr abstract name getter

---

CHANGELOG.md
src/unistd.rs
test/test_unistd.rs

This adds execveat() to `nix::unistd`. It uses the execveat(2) Linux
kernel syscall, which is available since 3.19.
This is a Linux-specific extension which is not covered by POSIX and
does not have any userland libc wrapper.
Ref: http://man7.org/linux/man-pages/man2/execveat.2.html

unistd: add execveat() on Linux and Android

---

.travis.yml
src/sys/epoll.rs

Seems to have occurred within a Rust release after 1.13, so let's test all of them since then!

Fix epoll bug in release mode on Rust 1.20+

---

.travis.yml
Cargo.toml
README.md
src/macros.rs
src/mqueue.rs
src/pty.rs
src/sys/event.rs
src/sys/quota.rs
src/sys/signal.rs
src/sys/signalfd.rs
src/sys/socket/mod.rs
src/sys/termios.rs
src/unistd.rs
test/sys/test_aio.rs
test/sys/test_epoll.rs
test/sys/test_ptrace.rs
test/sys/test_socket.rs
test/sys/test_termios.rs
test/sys/test_uio.rs
test/sys/test_wait.rs
test/test_fcntl.rs
test/test_mount.rs
test/test_mq.rs
test/test_poll.rs
test/test_pty.rs
test/test_ptymaster_drop.rs
test/test_unistd.rs

The libc_bitflags! macro was replaced with a non-recursive one supporting
only public structs. I could not figure out how to make the old macro work
with the upgrade, so I reworked part of the bitflags! macro directly to suit
our needs, much as the original recursive macro was made. There are no uses
of this macro for non-public structs, so this is not a problem for internal code.
Closes #766.

Upgrade to Bitflags 1.0

---

src/ifaddrs.rs
src/lib.rs
src/net/if_.rs
src/sys/socket/addr.rs

Here's a first attempt at a rustian interface for `getifaddrs`, please review.
Changes for the changelog:
- Added `nix::ifaddrs::{getifaddrs, InterfaceAddressIterator,
InterfaceAddress and InterfaceFlags}`
Closes #650.
Closes #764.

Add support for getifaddrs.

---

CHANGELOG.md
src/unistd.rs
test/test_unistd.rs

FreeBSD added pipe2(2) in version 10.0.

Use the real pipe2(2) on most targets

---

.travis.yml
ci/install.sh
ci/script.sh

Reduce ios builds

---

CHANGELOG.md
src/sys/wait.rs
test/sys/test_wait.rs

Expose `decode` on `WaitStatus` and make it return a `Result`

---

src/sys/aio.rs
src/sys/mman.rs
src/sys/quota.rs
src/sys/select.rs
src/unistd.rs

With the impending switch to Pulldown as the default doc generator, warnings
have been enabled for incompatible syntax. This fixes all of said warnings.

Cleanup all doc warnings

---

Cargo.toml
build.rs
src/errno.rs
src/errno_dragonfly.c
src/fcntl.rs
src/sys/socket/ffi.rs
src/unistd.rs
test/sys/mod.rs
test/test_unistd.rs

This commit replaces pull request https://github.com/nix-rust/nix/pull/684. It fixes building `nix` on DragonFly. All tests pass. This requires most recent libc to build: https://github.com/rust-lang/libc/pull/851.

Fix nix on Dragonfly

---

CHANGELOG.md
src/ifaddrs.rs
src/sys/socket/addr.rs
src/sys/socket/mod.rs

1. Add `EtherAddr` .
2. impl `Debug` for `InterfaceAddress` and `SockAddr`.
Closes #809

Support `EtherAddr` and impl `Debug` for `InterfaceAddress/SockAddr`

---

CHANGELOG.md
src/unistd.rs
test/sys/test_wait.rs

Follow up on https://github.com/nix-rust/nix/pull/829, since that repo is now unknown to GitHub.

Remove return value from `pause`

---

CHANGELOG.md
Cargo.toml
src/lib.rs
src/sys/aio.rs
test/sys/test_aio.rs
test/test.rs

`Rc<[u8]>` isn't a very good buffer type to use for aio.  For one thing, it lacks interior mutability.  For another, a single `Rc<[u8]>` can't be carved up into smaller buffers of the same type.  `Bytes` and `BytesMut` fix both problems.  This PR removes the ability to construct an `AioCb` from `Rc<[u8]>` and adds the ability to construct one from `Bytes`, `BytesMut`, or raw pointers (for consumers who need even more flexibility).  At this stage, the PR has the following warts:
1. A hack is necessary to force small `Bytes` buffers to allocate on the heap.  I plan to fix this with an enhancement to the bytes crate.
2. The `AioCb::buffer` method is necessary due to a deficiency in the tokio-core crate.  Once I fix that, then only `AioCb::into_buffer`will need to be public.

Change AioCb to primarily use Bytes instead of Rc<[u8]>

---

CHANGELOG.md
src/sys/socket/sockopt.rs

Add socket options for implementing a transparent proxy.
Sources:
[Linux](https://www.kernel.org/doc/Documentation/networking/tproxy.txt)
[OpenBSD](https://man.openbsd.org/setsockopt.2#SO_BINDANY)
[FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=ip&manpath=FreeBSD+11.1-RELEASE)
Thanks!

Add socket options for IP_TRANSPARENT / BIND_ANY

---

CHANGELOG.md
src/sys/termios.rs
test/sys/test_termios.rs

Support arbitrary baud rates on BSDs

---

Cargo.toml

Those are pretty useful for distributions to verify that crate actually work.

Cargo.toml: don't exclude test files

---

CHANGELOG.md
src/fcntl.rs
src/features.rs
src/lib.rs
src/mqueue.rs
src/net/mod.rs
src/poll.rs
src/pty.rs
src/sched.rs
src/sys/aio.rs
src/sys/epoll.rs
src/sys/event.rs
src/sys/mman.rs
src/sys/mod.rs
src/sys/ptrace.rs
src/sys/quota.rs
src/sys/select.rs
src/sys/signal.rs
src/sys/socket/addr.rs
src/sys/socket/mod.rs
src/sys/statvfs.rs
src/sys/termios.rs
src/sys/time.rs
src/sys/uio.rs
src/sys/utsname.rs
src/sys/wait.rs
src/ucontext.rs
src/unistd.rs

Gonna run this through CI and see what breaks on non-Linux-x64 platforms.
These changes are minor cleanups, but improve our doc story and should help with future submitted PRs.

More cleanups and enable some more compiler lints

---

src/lib.rs

Mistakingly removed in d1be45d8405.
Fixes #855.

Re-add ifaddrs module

---

CHANGELOG.md
src/unistd.rs
test/test_unistd.rs

Added `getsid` in `::nix::unistd`

---

CHANGELOG.md
src/sys/ptrace.rs

Added step function to ptrace, this follows the same form as the PTRACE_CONTINUE by advanced the tracee by a single step!
Found when I was updating to nix 0.10.0 that this function had been missed out. Minor addition as `SINGLESTEP` works the same as `CONTINUE`

Add step function to ptrace

---

src/sys/socket/sockopt.rs

In this PR I've added docs to that macros and exported them.
I've also made related structs/traits to be public as well.
Hope I didn't forget anything :)
Reference issue: #577.

Export socket options related macros

---

CHANGELOG.md
src/sys/event.rs
src/sys/socket/mod.rs
src/sys/termios.rs

Depends on: https://github.com/rust-lang/libc/pull/887

FreeBSD: cfmakesane, EVFILT_*

---

src/sys/signal.rs
test/sys/test_signal.rs

On Linux, if the signal trampoline code is in the C library, sigaction
sets the SA_RESTORER flag (0x04000000) in the sa_flags field of old
sigaction (see sigreturn(2)).
This is not intended for application use and is missing from SaFlags,
therefore from_bits fails and unwrapping panics the user program.
This fix just drops the bits that are not defined in SaFlags.

Change SigAction::flags to use from_bits_truncated

---

CHANGELOG.md
src/sys/socket/sockopt.rs

SO_MARK allows traffic to be filtered by a "tag" using fwmark (see: https://www.linux.org/docs/man8/tc-fw.html).
Tested on Linux as root - the test will skip over when not being run as root, as I noticed a few other tests do this in the suite already.

add SO_MARK SetSockOpt for Linux

---

CHANGELOG.md
src/sys/mman.rs

add mlockall and munlockall

---

CHANGELOG.md
Cargo.toml
src/lib.rs
src/sys/aio.rs
test/sys/test_aio.rs
test/sys/test_lio_listio_resubmit.rs

The new LioCb structure allows us to control the exact arguments passed
to lio_listio, guaranteeing that each call gets a unique storage
location for the list argument.  This prevents clients from misusing
lio_listio in a way that causes events to get dropped from a kqueue
Fixes #870

Change sys::aio::lio_listio to sys::aio::LioCb::listio

---

CHANGELOG.md
src/sys/uio.rs

This addresses issue #690.
It exposes the `preadv` and `pwritev` functions on supported BSDs (not including Apple platforms).

Expose `preadv` and `pwritev` on BSDs

---

src/poll.rs
test/test_poll.rs

This is useful when using printf-style debugging to observe the variables and
of the program.
This is discussed in issue #885.

Implement Debug trait for PollFd (Fixes #885)

---

CHANGELOG.md
src/sys/ptrace.rs

The cfg condition of ptrace::Request seems to be different from libc.
For example, PTRACE_GETREGS is defined by libc to i686-unknown-linux-gnu target, but it is not defined in ptrace::Request.
I tried to change the cfg condition to the same as libc's condition.
I thinks this change covers the definitions under src/unix/notbsd directory in libc repository.

Fixed ptrace::Request cfg conditions

---

CHANGELOG.md

Updated changelog to contain #869

Update changelog for #869

---

CHANGELOG.md
src/net/if_.rs

nix currently doesn't compile on openbsd because `IFF_NOTRAILERS` isn't found. This PR fixes the openbsd build again (tested on 6.3). It seems it was changed in this commit:
https://github.com/openbsd/src/commit/beb8b0dd5985e55a615b52e593da6e75bab33f3f

Remove IFF_NOTRAILERS for openbsd

---

src/sys/socket/mod.rs

libc fixed `bind()` for Android 64-bit targets, so change our
code to match.
PRs are failing (like #901) so let's get this merged.
CC @asomers @morrowa

Fix bind() on Android 64-bit

---

CHANGELOG.md
src/sys/mod.rs
src/sys/sendfile.rs
test/test.rs
test/test_sendfile.rs

This PR exposes the `sendfile` system call on libc's supported BSD-likes:
* FreeBSD
* Darwin (macOS/iOS)
DragonFly could be supported in the future, but I was unable to build rustc to test.
Note that NetBSD has no equivalent system call.

Implement sendfile on FreeBSD and Darwin

---

CHANGELOG.md
src/sys/socket/mod.rs
test/sys/test_socket.rs

Rather than using the native implementation of these constants
on supported platforms, the native implementation was instead
emulated. This was also hidden from the user even though this
could result in data races and the functionality being broken.
Native functionality is, however, not support on macos/ios.
Rather than enable this emulation solely for this platform, it
should be removed as this is a dangerous abstraction.
This is a replacement for #863. There is much previous discussion there which I recommend you read to familiarize yourself with this decision.
I'm looking to push this through rather quickly as it's the last thing blocking our next 0.11.0 release.
cc @aomser @kristate

Remove emulation of FD_CLOEXEC/O_NONBLOCK

---

Cargo.toml
RELEASE_PROCEDURE.md

Needed to do this for the v0.11.0 release, but I missed it on my first pass through. Also updated the release notes to hopefully prevent this error in the future.

Specify bytes version

---

CHANGELOG.md
src/sys/mod.rs
src/sys/sysinfo.rs
test/sys/mod.rs
test/sys/test_sysinfo.rs

Closes #505
Returned values were also inspected manually to be correct.

Add a sysinfo wrapper

---

CHANGELOG.md
src/sys/socket/mod.rs
test/sys/test_socket.rs

Fixes #464
Closes #874 because it's incorporated here
Closes #756 because it adds the test from that issue (with fixes)

Fix passing multiple file descriptors / control messages via sendmsg

---

CHANGELOG.md
src/sys/socket/mod.rs
src/sys/socket/sockopt.rs

These were disabled for ARM way back in 0db6ed1a28b4fb4d408cd9b7c4dba0a79bccf1f7 and 09c00ed7d9d92db2a79baa3ed212e7e239edceb9. Try to enable them for all arches and Android as well, since the removal wasn't really explained and I see no reason why this shouldn't work.

Get `SO_PEERCRED` working on all Linux targets

---

src/sys/select.rs

They pass at least on my machine with QEMU, so the underlying bugs might
have been fixed.

Enable the select tests on powerpc and mips

---

CHANGELOG.md
src/sys/socket/mod.rs
src/sys/socket/sockopt.rs
src/unistd.rs
test/sys/test_socket.rs

While https://github.com/nix-rust/nix/pull/918 fixed the *encoding*, the *decoding* done by the `CmsgIterator` still remained broken when multiple messages are received. However, since nix didn't support any control message that could reliably be sent twice in one `sendmsg` call, this couldn't be tested properly.
This PR addresses this by adding `SCM_CREDENTIALS` support and testing all of this by passing both an `SCM_CREDENTIALS` and a `SCM_RIGHTS` message at the same time.
I've also verified that the resulting encoding is the same as for roughly equivalent C code.

Fix control message *decoding* and add support for `ScmCredentials`

---

.travis.yml
CHANGELOG.md
Cargo.toml
README.md
src/sys/socket/mod.rs
src/unistd.rs
test/sys/test_socket.rs
test/sys/test_uio.rs
test/test.rs
test/test_fcntl.rs
test/test_mount.rs
test/test_stat.rs
test/test_unistd.rs

Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

deps: update tempfile to 3

---

CHANGELOG.md
src/dir.rs
src/lib.rs
test/test.rs
test/test_dir.rs

Fixes #915 
This is a lower-level interface than `std::fs::ReadDir`. Notable differences:
* can be opened from a file descriptor (as returned by `openat`, perhaps
before knowing if the path represents a file or directory). Uses
`fdopendir` for this, available on all Unix platforms as of
rust-lang/libc#1018.
* implements `AsRawFd`, so it can be passed to `fstat`, `openat`, etc.
* can be iterated through multiple times without closing and reopening the
file descriptor. Each iteration rewinds when finished.
* returns entries for `.` (current directory) and `..` (parent directory).
* returns entries' names as a `CStr` (no allocation or conversion beyond
whatever libc does).

new dir module

---

CHANGELOG.md
src/sys/signal.rs

This implements both ALLCAPS and lowercase full name (including SIG) and short
name.
This matches what `kill` accepts in many shells, and it also allows the `Debug`
representation of `Signal`, which means it can be round-tripped, if desired.

impl FromStr for sys::Signal

---

CHANGELOG.md
Cargo.toml
src/kmod.rs
src/lib.rs
src/pty.rs
test/sys/test_aio.rs
test/sys/test_select.rs
test/sys/test_signal.rs
test/sys/test_signalfd.rs
test/sys/test_termios.rs
test/sys/test_uio.rs
test/sys/test_wait.rs
test/test.rs
test/test_kmod/hello_mod/Makefile
test/test_kmod/hello_mod/hello.c
test/test_kmod/mod.rs
test/test_pty.rs
test/test_unistd.rs

- init_module and finit_module to load kernel modules
- delete_module to unload kernel modules

Add wrapper for linux kernel module loading

---

CHANGELOG.md
src/sys/stat.rs
test/test_stat.rs

Hello again!
Let's see how this looks like. I don't think there is any other way of doing this via the standard library, though I see there is a `filetime` crate in the Rust nursery to add this missing functionality. Not sure what your policy for adding features into `nix` is.

Add wrappers for futimens(2) and utimesat(2)

---

CHANGELOG.md
src/sys/stat.rs
test/test_stat.rs

PR #944 added wrappers for the more-modern futimens(2) and utimesat(2),
but unfortunately these APIs are not available on old-ish systems.
In particular, macOS Sierra and below don't implement them, making the
new APIs unusable.  Whether we should care about such "old" systems is
debatable, but the problem is that, at the moment, this is the only
macOS version usable on Travis to test kexts and, thus, to test FUSE
file systems.

Add a wrapper for utimes(2)

---

CHANGELOG.md
src/sys/socket/addr.rs

Hi!
I work on a [crate](https://github.com/levex/network-bridge-rs) where it would make sense to use `AF_UNSPEC` in place of `AF_INET`, since that's the API most bridge libraries use. Unfortunately, it seems that `nix` is missing a representation for `AF_UNSPEC`. This PR adds `Unspec` to `AddressFamily`, so we can now represent `AF_UNSPEC`.

socket: add AF_UNSPEC to AddressFamily

---

CHANGELOG.md
src/sys/stat.rs

This allows using e.g. sys::stat::Mode::from_bits() without having to
pull the mode_t type from libc (which is ugly if a project is trying
to use nix exclusively to avoid libc's unsafety).
This change mimics dev_t which was already exposed as public.

Make sys::stat::mode_t public

---

src/sys/ioctl/mod.rs

Currently the docs claim ioctl_param_type to always be libc::c_int which is not the case on linux.
Also removes an unused import that was triggering a warning.

Document ioctl_param_type

---

CHANGELOG.md
src/unistd.rs
test/test_unistd.rs

This also adds a test for truncate (obviously) but, while doing so, also
adds a test for the already-existing ftruncate.

Add a truncate(2) wrapper

---

CHANGELOG.md
src/sys/mod.rs
src/sys/ptrace/bsd.rs
src/sys/ptrace/linux.rs
src/sys/ptrace/mod.rs
test/sys/mod.rs
test/sys/test_ptrace.rs

This PR adds support to the ptrace API for BSDs to close #947. It also adds a read and write method for reading and writing to a traced processes memory. The ptrace API created for linux offers this via a deprecated function so I added this so they can be feature equivalent without replicating a deprecated part of the API.
Due to the differences in ptrace on BSD and linux I've made a ptrace module to keep things readable.
Still to do - revert travis config to remove my feature branch and update the changelog.

ptrace support for BSDs

---

CHANGELOG.md
src/unistd.rs
test/test_unistd.rs

This PR aims to add a nix wrapper for acct(2).

Add wrapper for acct(2)

---

CHANGELOG.md
src/sys/ptrace/linux.rs

This was added to the BSD ptrace API and probably should have been added to the linux API to make it easier to write code for both platforms without the user having to reexport the types to their own crate.
I went to use the latest nix myself and found that having this added would improve usability for nix users.
Could potentially add a type for what they return (BSDs: `c_int`, linux: `c_long`). Data input might be trickier as linux is `*mut c_void` and BSD just takes data as `c_int`.

Added AddressType type to ptrace::linux + peek/poke user fix

---

.travis.yml
CHANGELOG.md
Cargo.toml
README.md

`lazy_static` as of 1.2 requires Rust 1.24.1, so make that our minimum required. This was discovered when I looked into the failures of #965.
@asomers if you agree with this change, could you update the buildbots here too?

Require Rust 1.24.1

---

CHANGELOG.md
src/sys/time.rs

This allows handling the return values of other public functions
(such as TimeVal's tv_sec and tv_usec) without having to pull in
these types from libc (which is ugly if a project is trying to
use nix exclusively to avoid libc's unsafety).

Make sys::time::{time_t, suseconds_t} public

---

CHANGELOG.md

PR #884 added changelog entry in section for 0.11.0, which has been already released, instead of in the [Unreleased] section (which wasn't present yet). Moved the entry where it belongs.

CHANGELOG: move entry from #884 from 0.11.0 to [Unreleased]

---

CHANGELOG.md
src/unistd.rs
test/test_unistd.rs

Add execvpe support, conditional on platform

---

CHANGELOG.md
src/sys/stat.rs
test/test_stat.rs

PR #944 added wrappers for the more-modern futimens(2) and utimesat(2),
but unfortunately these APIs are not available on old-ish systems.
In particular, macOS Sierra and below don't implement them, making the
new APIs unusable.  Whether we should care about such "old" systems is
debatable, but the problem is that, at the moment, this is the only
macOS version usable on Travis to test kexts and, thus, to test FUSE
file systems.
This should have been part of PR #946, which added a wrapper for
utimes(2) following this same rationale, but missed lutimes(2) because
I simply didn't notice it existed.

Add a wrapper for lutimes(2)

---

CHANGELOG.md
src/lib.rs
test/test_unistd.rs

Add Error::as_errno
This method is useful when it can be statically determined that a nix::Error be an errno, which I find to be very common.
Also, fix some recently introduced compiler warnings.

Error as i32

---

src/sys/aio.rs
src/sys/ptrace/bsd.rs
src/sys/ptrace/linux.rs
src/sys/signalfd.rs
src/sys/stat.rs
src/sys/termios.rs
src/unistd.rs

I previously advocated for the latter syntax on stylistic grounds.  But
it generates less efficient code, because it creates a new lambda
function for each usage.  The optimizer does not combine them.  This
change saves about 6KB of code.

Prefer `map(drop)` to `map(|_| ())`

---

CHANGELOG.md
src/sys/socket/sockopt.rs
test/sys/test_sockopt.rs

Implementation proposal for support of TCP_CONGESTION param for `setsockopt`and `getsockopt` with the CString type.

Add support of TCP_CONGESTION for setsockopt

---

src/fcntl.rs
src/mount.rs
src/mqueue.rs
src/net/if_.rs
src/sys/mman.rs
src/sys/quota.rs
src/sys/signal.rs
src/sys/signalfd.rs
src/sys/socket/addr.rs
src/sys/socket/mod.rs
src/sys/socket/sockopt.rs
src/sys/stat.rs
src/sys/statfs.rs
src/sys/statvfs.rs
src/sys/termios.rs
src/sys/time.rs
src/sys/wait.rs
src/unistd.rs

try! is not available in Rust 2018.  It would be premature to convert the entire project to Rust 2018, since that would bump the minimum compiler to 1.31.0.  But his change will help us when we do convert it eventually.

Replace try! with ?

---

CHANGELOG.md
src/sys/socket/mod.rs
src/sys/socket/sockopt.rs
test/sys/test_socket.rs

Replaces #891 and attempts to address all previous concerns.

Add cmsg PKTINFO for IPv4 and IPv6.

---

.cirrus.yml
bors.toml

This change does the following:
1) Adds a CI build on cirrus-ci.com
2) Switches FreeBSD's CI from a jail to a full VM
3) Switches FreeBSD i386's CI from a 32-bit jail to simply using a
cross-compiled binary on a 64-bit VM.
4) Switches FreeBSD i386's CI from using stable rust to 1.24.1 (back
when I added buildbot, rustup didn't support i686-unknown-freebsd)
5) Switches bors to gate on cirrus-ci rather than buildbot
This change does _not_ disable buildbot.  That must happen outside of
git.
Fixes #996

Switch FreeBSD CI builds from BuildBot to cirrus-ci.com

---

src/sys/socket/mod.rs

The old test made assumptions about the responsiveness of the test
environment.  The new test does not, and it's simpler too.

Make ScmTimestamp's doc test more robust

---

CHANGELOG.md
src/sys/ptrace/linux.rs

I needed `ptrace`'s `getregs` and `setregs` for a project I was working on, so I added them! First time contributor, so let me know if I should change / fix anything. Things work fine in my project which uses both functions, let me know if further testing is needed.

Added `ptrace::{getregs, setregs}`

---

CHANGELOG.md
src/errno.rs
src/sys/signal.rs
test/sys/test_signal.rs

This implements `nix::sys::signal::signal` and adds corresponding documentation and tests.
Closes #476

Implement nix wrapper for libc::signal

---

CHANGELOG.md
src/sys/stat.rs
src/unistd.rs
test/sys/test_aio_drop.rs
test/test_stat.rs
test/test_unistd.rs

First of all, I'm not a rust developer so please be gentle :)
I'm using https://github.com/jwilm/alacritty on OpenBSD. I'm trying to track the latest versions of both OpenBSD and alacritty so I'm recompiling alacritty fairly often. However the latest version of alacritty updated some of it's nix dependencies to v0.12.0 and that doesn't build on OpenBSD anymore:
```bash
user1 ~/ALACRITTY/nix $ sysctl kern.version
kern.version=OpenBSD 6.4-current (GENERIC.MP) #529: Tue Dec 18 22:36:49 MST 2018
deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/GENERIC.MP
user1 ~/ALACRITTY/nix $ rustc -vV
rustc 1.31.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-openbsd
release: 1.31.0
LLVM version: 6.0
user1 ~/ALACRITTY/nix $ cargo build
Updating crates.io index …
```

Make nix build again on OpenBSD 6.4-current

---

CHANGELOG.md
src/sys/mman.rs

It doesn't look like there's an existing test suite for `mmap` and friends, so this is regrettably untested.

Add `mman::mprotect`

---

CHANGELOG.md
src/poll.rs
test/test_poll.rs

I tried to grep and replace for #317. Please let me know if I need to fix something else as well but in my search I saw that most were fixed earlier.

Fix for #317 - Some event flags renaming

---

CHANGELOG.md
src/sys/socket/mod.rs
src/sys/time.rs
test/sys/test_socket.rs

This PR fixes multiple bugs in the cmsg code.
Fixes #994 
Fixes #999 
Fixes #1013

Major cmsg cleanup

---

CHANGELOG.md
src/sys/event.rs
src/sys/signal.rs
src/unistd.rs

Several symbols are now marked as deprecated on OSX.

Fix the tests with libc 0.2.49 and Rust 1.33.0

---

CHANGELOG.md
src/sys/inotify.rs
src/sys/mod.rs
test/sys/mod.rs
test/sys/test_inotify.rs

Hi !
I needed inotify bindings and noticed that nix did not have any so here is a PR to add it.
There was another PR from 2015 to add support for inotify that was never merged. I took some of the feedback and applied it here.

Added inotify bindings.

---

CHANGELOG.md
src/sys/signal.rs
test/sys/test_signal.rs

It's seem that #644 is inactively about 1 year. But I really want this API that can land in nix.
Actually I not really understand how to check the availability of an API for other platform except Linux. But I saw that this API in `libc` is wrapping inside a `#[cfg(unix)]`. So I don't need to add any `#[cfg]` on this API, am I right?
Resolved #644

Add killpg

---

CHANGELOG.md
src/errno.rs

While ENOTSUP is defined as equal to EOPNOTSUPP on these platforms,
exposing the ENOTSUP symbol (as libc does) allows for writing portable
code that may want to reference this error code.

Add ENOTSUP to Linux and Android

---

CHANGELOG.md
src/errno.rs

It looks like OpenBSD added several new errno values in 6.2, and they've already been added to `libc`, so this should allow any crates using those to build on OpenBSD.

Add several errno values for OpenBSD

---

CHANGELOG.md
src/sys/socket/addr.rs

These were commented out in 2b60633c8bdd5359c317bb74e698777106befb85, apparently because `std::net::IpAddr` had been removed from the standard library. However, `IpAddr` has since been re-added to the standard library (https://github.com/rust-lang/rust/pull/23711) and stabilized (https://github.com/rust-lang/rust/pull/31438), so it seems there is no reason to keep them commented out.

Uncomment to_std and from_std methods for IpAddr

---

CHANGELOG.md
src/sys/ioctl/bsd.rs
src/sys/ioctl/mod.rs

~This PR adds the `$crate::` prefix to all uses of helper macros, which will allow users of the 2018 edition to import the macros without needing to also import their helpers.~
See https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html#macros-with-crate-prefix for more info.
~While this is a cleaner solution than using `#[macro_export(local_inner_macros)]`, it also requires bumping the minimum supported compiler version to 1.30. If this is acceptable, I'll add a commit to update the Travis configuration and docs.~
This PR now uses `local_inner_macros` to preserve compatibility with the current minimum Rust version.

allow importing macros without helpers in the 2018 edition

---

CHANGELOG.md
src/unistd.rs

This is for the benefit of those platforms that do not provide setresuid
nor setresgid, like macOS.

Add unistd::{seteuid,setegid}

---

src/unistd.rs

nix current compiles on 1.34.0 stable but not on 1.36.0 nightly because of duplicate use statements. This trivial change removes the duplicates so it compiles and the tests run successfully on 1.36.0 nightly (33fe1131c 2019-04-20)

Remove duplicate use statements on macOS.

---

src/sys/socket/mod.rs
test/sys/test_socket.rs

This pull request restores the `bytes` field on the `RecvMsg` structure in order to be able to know the amount of bytes read during a call to `recvmsg`.

Restored the bytes field on RecvMsg

---

src/sys/ptrace/linux.rs

libc just removed some symbols on linux/arm32 and linux/s390x that never
should've been defined in the first place.
https://github.com/rust-lang/libc/commit/24f8972b8d2d915b1687fc8197e1ed95e349a82e
https://github.com/rust-lang/libc/commit/d2695436ba5072078796c76f727a296e0f43caa6

Fix build on arm and s390x after recent libc changes

---

CHANGELOG.md
src/sched.rs

This adds the `sched_yield` function, which is part of POSIX:
http://pubs.opengroup.org/onlinepubs/9699919799/functions/sched_yield.html
and widely implemented on Unix-family platforms.

Implement `sched_yield`.

---

CHANGELOG.md
src/sys/ioctl/linux.rs

Finish off the work started in 8c9ac5a70 allowing the use of macros
without needing to import local inner macros for Linux targets.

Allow import of Linux macros in Rust2018

---

Cargo.toml
src/sys/inotify.rs
src/sys/mman.rs
src/sys/signal.rs
src/sys/socket/addr.rs
src/sys/socket/sockopt.rs
test/sys/test_pthread.rs

The `libc` crate now uses rust types in some places where previously types like `libc::uint8_t` had been defined. This PR adjusts nix's code to reflect these simplifications.

Fix libc deprecations

---

CHANGELOG.md
src/sys/socket/mod.rs

MSG_WAITALL can be useful with recv() to wait the full amount of data requested.

socket: expose MSG_WAITALL in MsgFlags

---

CHANGELOG.md
src/ifaddrs.rs
src/lib.rs

Support under bionic/android is the same as under Linux for what is exposed
by this code.

ifaddrs: add ifaddrs support for android

---

CHANGELOG.md
src/fcntl.rs
test/test_fcntl.rs

This should fix the problems with #971 and #1008.

Implement copy_file_range()

---

CHANGELOG.md
src/sys/stat.rs
test/test_stat.rs

See: https://github.com/CraneStation/wasi-common/issues/16
https://linux.die.net/man/2/mkdirat
My first contribution to this repo. Tests were probably overkill...
Also, out of curiosity, is there any reason why `mkdir` is located in `unistd`? The documentation I read mentioned the function definition also being located in `sys/stat.h`.

sys/stat: implement mkdirat

---

CHANGELOG.md
src/sys/mod.rs
src/sys/statfs.rs

Fix for [#926](https://github.com/nix-rust/nix/issues/926)

Wrap libc::statfs

---

Cargo.toml

tempfile release 3.0.9 raised the MSRV without a minor version bump.
See https://github.com/Stebalien/tempfile/issues/100

Restrict tempfile to < 3.0.9

---

CHANGELOG.md
src/lib.rs
src/sched.rs

Currently, `sched` module is compiled only for linux-like hosts. However, the recently added syscall `sched_yield` is universal to all *nixes. This PR pulls all linux-like functionality into a private `sched_linux_like` module which is enabled only for android and linux hosts, while `sched_yield` and `sched` modules are now compiled for all *nixes, thus, correctly exposing `sched_yield` to other non-linux hosts.

Expose sched_yield on non-linux-like hosts

---

CHANGELOG.md
src/fcntl.rs
test/test_fcntl.rs

See: 
https://github.com/CraneStation/wasi-common/issues/16
http://man7.org/linux/man-pages/man2/posix_fadvise.2.html
Conditional compilation derived from corresponding libc conditions:
Fuchsia:
https://github.com/rust-lang/libc/blob/0b02c4060a750983cebcccdf1f35a5ec4cdcf516/src/fuchsia/mod.rs#L3807
https://github.com/rust-lang/libc/blob/0e702c1b4e2e56788e8b67d3efd9c242807c3d4b/src/lib.rs#L104-L109
uClibc:
https://github.com/rust-lang/libc/blob/11c762c535cb43dda3d9d87a0845c55201a905fb/src/unix/uclibc/mod.rs#L1676
https://github.com/rust-lang/libc/blob/ce7e3a7e866dd7109a971b694a2bf58bd08f101a/src/unix/mod.rs#L1141-L1143
https://github.com/rust-lang/libc/blob/0e702c1b4e2e56788e8b67d3efd9c242807c3d4b/src/lib.rs#L116-L121
Linux, android, emscripten: …

implement posix_fadvise

---

CHANGELOG.md
src/sys/socket/addr.rs
src/sys/socket/mod.rs
test/sys/test_socket.rs

This patch adds the support of AF_VSOCK in the socket module.
VSOCK is present since Linux 3.9.

socket: add support for AF_VSOCK

---

.cirrus.yml
.travis.yml
CHANGELOG.md
README.md
src/features.rs
src/lib.rs
src/sched.rs
src/sys/aio.rs
src/sys/socket/mod.rs
test/sys/test_socket.rs
test/test.rs

* Replace obsolete range syntax "..." with inclusive range "..="
* Use dyn Trait syntax instead of Box<Trait>
* Raise MSRV to 1.27.0 (for dyn Trait syntax)
* Test with nightly again

Fix warnings on Rust 1.37.0

---

CHANGELOG.md
src/fcntl.rs
src/unistd.rs
test/test_unistd.rs

This adds the unlinkat function, which is part of POSIX:
http://pubs.opengroup.org/onlinepubs/9699919799/functions/unlinkat.html
and widely implmented on Unix-family platforms.

Implement unlinkat

---

CHANGELOG.md
Cargo.toml
README.md

It's important to release fairly soon, because rustc 1.38.0 will deprecate std::mem::uninitialized.

Release v0.15.0

---

CHANGELOG.md
src/fcntl.rs
test/test_fcntl.rs
test/test_unistd.rs

Currently readlink returns `ENAMETOOLONG` when the bufferSize is equal to the result size.  
Consider the below case
```c++
int main(int argc, const char * argv[]) {
std::string filename = "/tmp/test-dir/target";
size_t bufferSize = 9;
char* buffer = new char[bufferSize];
size_t rc = readlink (filename.c_str(), buffer, bufferSize); 
// Since `readlink's` output depends on the `bufferSize`. If the`bufferSize` is 9 or greater than 
// 9 then it will return 9 or else it will return `bufferSize` as the value of `rc`. 
return 0;
}
```

fix readlink/readlinkat to return too long only when it is long

---

.cirrus.yml
.travis.yml
CHANGELOG.md
README.md
test/sys/test_ioctl.rs

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

Raise minimum supported Rust version to 1.36.0

---

CHANGELOG.md
src/dir.rs
src/errno.rs
src/fcntl.rs
src/ifaddrs.rs
src/lib.rs
src/macros.rs
src/mqueue.rs
src/poll.rs
src/pty.rs
src/sys/aio.rs
src/sys/event.rs
src/sys/select.rs
src/sys/sendfile.rs
src/sys/signal.rs
src/sys/socket/addr.rs
src/sys/socket/mod.rs
src/sys/socket/sockopt.rs
src/sys/time.rs
src/sys/wait.rs
src/unistd.rs

This is preparation for several changes relating to raising the MSRV, most importantly eliminating `mem::uninitialized`.

Clippy cleanup

---

.travis.yml
CONVENTIONS.md
src/dir.rs
src/ifaddrs.rs
src/mqueue.rs
src/pty.rs
src/sys/ptrace/linux.rs
src/sys/quota.rs
src/sys/select.rs
src/sys/signal.rs
src/sys/signalfd.rs
src/sys/socket/addr.rs
src/sys/socket/mod.rs
src/sys/stat.rs
src/sys/statfs.rs
src/sys/statvfs.rs
src/sys/sysinfo.rs
src/sys/termios.rs
src/sys/utsname.rs
src/ucontext.rs
src/unistd.rs
test/sys/test_aio.rs
test/sys/test_ptrace.rs

Only two instances remain:
* For the deprecated sys::socket::CmsgSpace::new.  We should probably
just remove that method.
* For sys::termios::Termios::default_uninit.  This will require some
more thought.

Replace most instances of mem::uninitialized with mem::MaybeUninit

---

CHANGELOG.md
src/sys/socket/addr.rs
test/sys/test_socket.rs

NULL bytes have no special significance in an abstrace address, and the
length of the address is solely decided by the length member. If the
length is set to sun_path.len(), all the NULL bytes will be considered
part of the address.
Tests are updated accordingly.
Closes #1119
Signed-off-by: Yuxuan Shui <yshuiv7@gmail.com>

Fix length of abstract socket address

---

src/sys/event.rs
src/sys/socket/mod.rs
src/sys/socket/sockopt.rs
src/sys/termios.rs
test/sys/test_aio.rs
test/test_mq.rs
test/test_pty.rs
test/test_stat.rs
test/test_unistd.rs

`assert_eq!` gives more debug info when the test fails by default than `assert!`. This should help make debugging easier.

Where relevant, replace equality checks in assert! with assert_eq!

---

Cargo.toml

The minimum supported Rust version was bumped in #1108 so these restrictions are no longer necessary.

Relax some dependency versions

---

src/unistd.rs

We now have a `reserve_double_buffer_size` method which reserves the
double of buffer, up to a limit, allowing it to be reused on other
methods in future.
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

unistd: getcwd: Double the buffer when need, up to PATH_MAX as limit

---

CHANGELOG.md
src/fcntl.rs
test/test_fcntl.rs

This PR add [`posix_fallocate`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/posix_fallocate.html), which is available on
- Linux
- FreeBSD
- Android
- Emscripten
- Fuchsia
- WASI
Here is a question: for some reason, `posix_fallocate` returns `EBADF` instead of `EPIPE` if a FIFO file descriptor is passed in on Linux 4.19.64. In the test `EBADF` is used for now, but I would like to know if such behaviour is expected.

posix_fallocate support

---

src/unistd.rs

The buffer resize logic can be simplified reusing the
`reserve_double_buffer_size` method.
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

unistd: getgrouplist: Rework code to use `reserve_double_buffer_size`

---

CHANGELOG.md
src/unistd.rs
test/test_unistd.rs

This adds the `mkfifoat ` function, which is part of POSIX [https://pubs.opengroup.org/onlinepubs/9699919799/functions/mkfifoat.html](https://pubs.opengroup.org/onlinepubs/9699919799/functions/mkfifoat.html)
test cases are copied from `mkfifo`

Implement mkfifoat 

---

CHANGELOG.md
src/sys/socket/mod.rs

Because of the use of MaybeUninit::uninit, the padding fields in msghdr,
which only present on musl builds, are not initialized. Causing garbage
data to be sent to the kernel. This change ensures the paddings are
always zeroed.

Properly initialize msghdr when using musl

---

.cirrus.yml

Fix CI on FreeBSD after rustup 1.20.0.

Rustup minimal

---

src/unistd.rs

- docstring now matches the actual `getegid()` call

Fix typo in Gid::effective() docstring

---

CHANGELOG.md
src/sys/socket/mod.rs
test/sys/test_socket.rs

recvfrom(2) only returns the sender's address for protocols that provide
it.  Usually, that means it returns the sender's address for datagram
sockets but not for stream sockets.
Fixes #1144

Fix sys::socket::recvfrom for TCP sockets

---

CHANGELOG.md
src/sys/signal.rs

Currently string representation of signal can be obtained with AsRef<str> impl.
But it has downside: returned string's lifetime is bound to lifetime of signal, so &str must be converted to String. This allocation is avoidable, because as_ref() only returns static strings. To fix this problem, my PR adds Signal::as_str() method, which returns static string.

Add Signal::as_str() to get representation as static string

---

src/sys/termios.rs

On sparc64, glibc defines VMIN as VEOF and VTIME as VEOL for
termios, so we need to inherit these alias definitions for
nix-rust as well.
Fixes #1149

sys: termios: Define VMIN and VTIME as VEOF and VEOL on sparc64

---

CHANGELOG.md
src/unistd.rs

This was a collaborative work between Johannes Schilling
<dario@deaktualisierung.org>, Fredrick Brennan <copypaste@kittens.ph>
and myself.
This PR is a split-off from #864 so we merge ready parts first. Next, we work on the iterators.
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

Add `Users` and `Group` related functions

---

src/mqueue.rs

The latest compiler warns about unnecessary parentheses in a position
that previous compilers ignored.

Fix a warning with the latest nightly compiler

---

src/sys/termios.rs

The fix for #1149 has the logic for the [cfg()] conditional inverted
so that the aliases for VMIN and VTIME are defined on targets that
are not linux-sparc64.

sys: termios: Fix inverted logic for [cfg()] conditional for sparc64

---

CHANGELOG.md
src/fcntl.rs
src/unistd.rs
test/test_unistd.rs

This adds the linkat function which is part of POSIX:
http://pubs.opengroup.org/onlinepubs/9699919799/functions/linkat.html
and widely implmented on Unix-Family platforms.

Implment linkat

---

CHANGELOG.md
src/sched.rs
test/test.rs
test/test_sched.rs

Hello,
I found the function `sched::sched_setaffinity()` but I also needed to get the process affinity and I did not find the function `sched::sched_getaffinity()`
So I added the function which maps [sched_getaffinity(2)](https://linux.die.net/man/2/sched_getaffinity) which "get a process's CPU affinity mask" to the sched.rs file.
I hope the code match your guidelines (returned `Result<CpuSet>` instead of pointer parameter)
If that's not the case, tell me, I will fix asap.
I hope this will help !
Thanks,
Thibaut

Implement sched::sched_getaffinity()

---

CHANGELOG.md
src/sys/ptrace/bsd.rs
src/sys/ptrace/linux.rs
test/sys/test_ptrace.rs
test/sys/test_wait.rs

Fixes #1049
Should I add tests for this functionality?
By the way, I noticed that the BSD module doesn't have `ptrace::syscall`. I couldn't find a reason behind this in #949. Should we add it?

Allow signal injection in ptrace::syscall and ptrace::detach

---

CHANGELOG.md
src/sys/socket/mod.rs

This eliminates one of the last remaining uninitialized memory accesses
in Nix.
Fixes #1142

Remove the deprecated CmsgSpace

---

src/lib.rs
src/sys/termios.rs
test/sys/test_ioctl.rs
test/test.rs

Replace it with mem::zeroed.  It isn't perfect, but it's better than it
was.
Issue #1115

Remove the last use of mem::uninitialized

---

CHANGELOG.md
src/sys/termios.rs

The old From implementation was actually falliable, and would panic on
failure.

impl TryFrom<libc::speed_t> for BaudRate

---

CHANGELOG.md
src/sys/aio.rs
src/sys/socket/mod.rs
src/sys/termios.rs
test/sys/test_socket.rs

Fix various minor TODOs and FIXMEs in the code.

Various minor fixups

---

test/sys/test_aio.rs

I suspect that the segfault is due to a stack overflow on musl's signal
stack, but I can't reproduce the failure locally.
Fixes #1169

Skip test_aio_cancel_all on musl

---

CHANGELOG.md
src/sys/statfs.rs

We were assuming the wrong types for f_iosize and f_ffree in struct
statfs on OpenBSD.
Fixes #1125

Fix the build on OpenBSD.

---

CHANGELOG.md
src/errno.rs
src/lib.rs

`Error::description` has been documented as soft-deprecated since 1.27.0 (17 months ago). It is going to be hard-deprecated soon.
This PR:
- Removes all implementations of `description` in all error types
Related PR: https://github.com/rust-lang/rust/pull/66919

Remove deprecated Error::description

---

CHANGELOG.md
src/unistd.rs

http://man7.org/linux/man-pages/man3/sysconf.3.html says that the
corresponding variable is obsolete, but I think that just means the
constant defined in limits.h is obsolete. Checking the value using
sysconf is still valid.

Add CLK_TCK to SysconfVar

---

src/sys/ioctl/mod.rs

The file documenting ioctl number assignment in the Linux kernel has been converted to ReStructuredText (see https://lwn.net/Articles/705224/ for some background), the file extension has naturally changed.

ioctl: Fix broken link to the kernel documentation

---

CHANGELOG.md
Cargo.toml
src/env.rs
src/lib.rs
test/test_clearenv.rs

Maybe closes #481.
"Maybe" for a couple reasons that are discussed on that issue:
* The issue mentions adding the other environment-variable-related functions (`setenv`, `getenv`, etc.), but I omitted those because they're already covered by `std::env` AFAICT, plus they're wildly unthreadsafe. It looks like `std::env` avoids the thread unsafety via a library-level lock and a warning to be careful when using ffi functions that might modify the environment concurrently.
* I opted to return `Error::UnsupportedOperation` in the (impossible?) case of `libc::clearenv()` returning non-zero instead of having the function return a `Result<(), ()>`. The latter seems like it would be onerous (since every other possibly-failing function in nix returns a `nix::Result`), but if you'd prefer a different …

Provide clearenv()

---

CHANGELOG.md
src/sys/statfs.rs

Currently, `FsType` API is limited. In fact, only operation is supports is comparison with one of well-known IDs.
But:
* This list is incomplete. For example, it misses cgroupfs and cgroup2fs.
* This approach doesn't work with custom FSs.

Make FsType's raw type public

---

CHANGELOG.md
src/unistd.rs
test/test_unistd.rs

I noticed that the filesystem checks API `setfsuid` and `setfsgid` where missing (while available in `libc`). This PR adds the implementation for both of them.

Add setfsuid and setfsgid implementation for filesystem checks

---

CHANGELOG.md
src/unistd.rs

Derive `Ord`, `PartialOrd` for `Pid`

---

CHANGELOG.md
src/fcntl.rs

Fix fallocate signature

---

CHANGELOG.md
src/sys/ptrace/linux.rs

Hi, I needed `ptrace::getregs` in my project. I noticed that they're only enabled on glibc while they can be compiled with musl. This PR enables getregs/setregs on x86_64 musl libc environment.

Enable getregs/setregs on x86_64 musl

---

CHANGELOG.md
src/unistd.rs

Functions such as Group::from_anything use reserve_double_buffer_size
in a loop, expecting it to return ERANGE if the passed limit is
reached.
However, the returned vector is passed as pointer to a libc function
that writes data into memory and doesn't update the length of the
Vec. Because of this, the previous code would never return ERANGE and
the calling loops would never exit if they hit a case where the
required buffer was larger than the maximum buffer.
This fixes the problem by checking the capacity rather than the
length.
Signed-off-by: Steven Danna <steve@chef.io>

unistd: avoid infinite loop caused by reserve_double_buffer_size

---

CHANGELOG.md
Cargo.toml
src/fcntl.rs
test/test_fcntl.rs

Hello
This PR updates libc to 0.2.68, which adds the `F_OFD_*` fcntl commands, and uses them in `nix::fcntl::fcntl`.

Implement open file descriptor locks in fcntl

---

CHANGELOG.md
src/sys/socket/sockopt.rs

The old code tried to zero-initialize an enum for which 0 is not a valid
value.  That worked for older compilers, but triggers a panic with Rust
1.44.0.  The correct technique is to use mem::MaybeUninit.
Fixes #1212

Fix UB in getsockopt

---

CHANGELOG.md
src/sys/socket/mod.rs

Casting a pointer to `cmsg_data` to `af_alg_iv` is incorrect since it's not properly aligned. As of the [`cmsg` man page](http://man7.org/linux/man-pages/man3/cmsg.3.html) "Applications should not cast it to a pointer type matching the payload, but should instead use memcpy(3) to copy data to or from a suitably declared object."

Fix unaligned casting of cmsg data to af_alg_iv

---

CHANGELOG.md
src/sys/select.rs

To be more consistent with most Rust APIs and enable cloning of the iterator, I made `FdSet::contains` operate on an immutable borrow instead of a mutable one by copying the set. If this is not desirable, I can roll that back from this PR and focus purely on the `fds()` method.

Add select::FdSet::fds() method

---

test/sys/test_ioctl.rs

Somehow I didn't noticed these in PR #1158, probably because they're
only built on Linux.

Remove a few more cases of mem::uninitialized in the tests

---

src/pty.rs
test/test_pty.rs

`PtyMaster` acts like an owned file descriptor, even closing on `Drop`.
Implementing `io::Read` and `io::Write` lets it be used directly in
standard I/O operations.

impl io::{Read,Write} for PtyMaster

---

src/sys/ptrace/linux.rs

Don't try to use PTRACE_[GS]ETREGS, PTRACE_[GS]ETFPREGS or
PTRACE_[GS]ETFPXREGS on riscv64, they are legacy-only.

Fix RISC-V support

---

CHANGELOG.md
Cargo.toml
src/sys/socket/mod.rs
src/sys/socket/sockopt.rs
test/sys/test_socket.rs
test/test.rs

This PR implements support for UDP GSO and GRO on Linux. It provides the way to send/receive UDP payloads bigger than interface MTU. The goal is to improve UDP performance. 
GSO was introduced in Linux 4.18, GRO in 5.3

Support UDP GSO and GRO on linux

---

CHANGELOG.md
src/sys/socket/mod.rs
src/sys/time.rs
test/sys/test_socket.rs

This pull request adds `sendmmsg` and `recvmmsg` functions. They are used to send and receive multiple messages per one call. Additionally, `AsMut` implemented for both `TimeSpec` and `TimeVal`. 
This is still WIP, because we need to find the best way on how to pass multiple values to *mmsg functions. Current approach with iterators doesn't seem ergonomic.

Support sendmmsg/recvmmsg

---

CHANGELOG.md
src/sys/socket/addr.rs

This function never should've been public, since it's basically
impossible to use directly.  It's only public due to an oversight from
PR #667 .

Remove sys::socket::addr::from_libc_sockaddr from the public API

---

test/test.rs

Fix an "unused macro" warning on non-Linux platforms

---

.travis.yml

This commit reverts eba3b516f7f76465e2fbe1c16724786144f01e8e, which
worked around a Travis CI bug that has since been fixed.  The effect is
to resume testing on the latest Rust stable.

Test on Rust stable again

---

CHANGELOG.md
Cargo.toml
src/sys/socket/mod.rs
test/sys/test_socket.rs

This allows working with `SCM_CREDS` messages, which are like `SCM_CREDENTIALS` on Linux, but slightly different (always overwritten by the kernel, contain a bit more info — euid and groups).
With this PR, it is possible to write portable code that would use the appropriate message for the platform, but one remaining quirk is that `PassCred` thing still has to be present and `cfg`'d to Linux.
Adding the `SCM_CREDS` constant to libc: https://github.com/rust-lang/libc/pull/1740

Add UnixCredentials support on FreeBSD/DragonFly

---

test/sys/test_socket.rs

Fix an "unused import" warning on FreeBSD in test_scm_credentials

---

CHANGELOG.md
src/sys/socket/sockopt.rs
test/sys/test_sockopt.rs

This is available only on Linux as far I know, [socket(7)](https://linux.die.net/man/7/socket) has some information
about the `SO_BINDTODEVICE` sockopt. In simple words it binds a socket
to an specific network device (specified as an string like "wlo1",
"eth0", etc.), to only process packets from that device.
Note: this is untested (for now, i'll test it today), but should work out of the box.

Add SO_BINDTODEVICE sockopt

---

CHANGELOG.md
src/fcntl.rs

This is in response to issue #1178.
The new logic uses the following approach.
- At any time, if `readlink` returns an error, or a value ≥ 0 and < (not ≤!) the buffer size, we're done.
- Attempt to `readlink` into a `PATH_MAX` sized buffer. (This will almost always succeed, and saves a system call over calling `lstat` first.)
- Try to `lstat` the link. If it succeeds and returns a sane value, allocate the buffer to be that large plus one byte. Otherwise, allocate the buffer to be `PATH_MAX.max(128) << 1` bytes.
- Repeatedly attempt to `readlink`. Any time its result is ≥ (not >!) the buffer size, double the buffer size and try again.
While testing this, I discovered that ext4 doesn't allow creation of a symlink > 4095 (Linux's `PATH_MAX` minus one) bytes long. This is in spite of Linux …

Add support for reading symlinks longer than `PATH_MAX` to `readlink` and `readlinkat`

---

CHANGELOG.md
src/poll.rs
src/sys/epoll.rs
src/sys/socket/mod.rs
src/sys/time.rs
src/sys/uio.rs

repr(transparent) is required in order to safely cast between an FFI
type and its NewType.  This commit applies that attribute to PollFd,
EpollEvent, IpMembershipRequest, Ipv6MembershipRequest, TimeVal, and
IoVec.
Fixes #1241

Apply `repr(transparent)` to several FFI types

---

CHANGELOG.md
src/sys/ptrace/linux.rs

It always should've been unsafe, because it dereferences a user-provided
pointer.

Make ptrace::write unsafe on Linux

---

CHANGELOG.md
src/lib.rs
src/mount.rs
src/sys/quota.rs

Most Nix functions that accept `NixPath` arguments can't do anything
useful with `None`.  The exceptions (`mount` and `quotactl_sync`)
already take explicitly optional arguments.
Also, this changes the behavior of `mount` with `None` arguments.
Previously, it would call mount(2) with empty strings for those
arguments.  Now, it will use null pointers.

Don't implement `NixPath` for `Option<&P> where P: NixPath`

---

CHANGELOG.md
Cargo.toml
src/lib.rs
src/sys/reboot.rs
src/unistd.rs

[`std::convert::Infallible`](https://doc.rust-lang.org/stable/std/convert/enum.Infallible.html) has been available since Rust 1.34 and nix currently targets Rust 1.36 or later so this should not cause problems.
Fixes #1238

Replace void crate with Rust standard lib Infallible type

---

.travis.yml
Cargo.toml
README.md
src/dir.rs
src/errno.rs
src/fcntl.rs
src/features.rs
src/lib.rs
src/macros.rs
src/poll.rs
src/sys/ioctl/mod.rs
src/sys/mod.rs
src/sys/signal.rs
src/sys/stat.rs
src/sys/statvfs.rs
src/sys/termios.rs
src/sys/wait.rs
src/unistd.rs
test/sys/mod.rs
test/sys/test_pthread.rs
test/sys/test_signal.rs
test/sys/test_uio.rs
test/sys/test_wait.rs
test/test.rs
test/test_fcntl.rs
test/test_stat.rs
test/test_unistd.rs

Some things are not implemented yet in redox, so a lot of annotations were added to remove functions when compiling for redox. Those functions will hopefully be added in time, but for now it's better to have partial support than none.
Blocked by https://github.com/rust-lang/libc/pull/1438

Add Redox support for most of the modules

---

CHANGELOG.md
src/sys/event.rs
src/sys/socket/mod.rs
test/sys/test_socket.rs

This pull request:
- Adds `EV_DISPATCH` and `EV_RECEIPT` to `EventFlags`. OpenBSD supports these now. 
c379d1a
- Fixes a regression that caused `nix` to be unable to build on OpenBSD since #1208. 
dd0a990
- Makes a change to avoid a deprecation warning from `libc` crate, which breaks tests. 
0f9fcbd
Since I know y'all don't have OpenBSD in CI right now, I've attached the results of a `cargo test` run on OpenBSD 6.7.
Thanks for your time!
[testresults.txt](https://github.com/nix-rust/nix/files/4684597/testresults.txt)
Fixes #1251

Add EV_DISPATCH, EV_RECEIPT items for EventFlags, and fix build on OpenBSD

---

CHANGELOG.md
src/sys/termios.rs
test/sys/test_termios.rs

Limit internal termios API to pub(crate)

---

CHANGELOG.md
src/unistd.rs
test/test_unistd.rs

Mentioned [in #1029](https://github.com/nix-rust/nix/issues/1029#issuecomment-622972782).

Add fchown(2) wrapper

---

CHANGELOG.md
src/sys/event.rs
src/sys/ptrace/linux.rs
src/unistd.rs
test/test_unistd.rs

* `unistd::daemon` on Apple
* `unistd::pipe2` on Apple
* `sys::event::FilterFlag::NOTE_EXIT_REPARENTED` on Apple
* `sys::event::FilterFlag::NOTE_REAP` on Apple
* `sys::ptrace::ptrace` on Android and Linux
All have been deprecated for more than two releases and one year.

Remove several deprecated constants and functions

---

CHANGELOG.md
src/sys/socket/mod.rs
test/sys/test_socket.rs

This adds Ipv4PacketInfo and Ipv6PacketInfo to ControlMessage, allowing these to be used with sendmsg/sendmmsg.

Add Ipv{4,6}PacketInfo support to ControlMessage for send{m,}msg.

---

.travis.yml

It's unreliable.  It frequently hangs starting the Docker image, before
Cargo gets involved.  Instead, use cargo to do a cross-build for Redox.
Do it manually, since rust-embedded/cross doesn't support Redox.
https://github.com/nix-rust/nix/issues/1258
https://github.com/rust-embedded/cross/issues/427

Don't run redoxer in CI

---

.travis.yml
CHANGELOG.md
README.md

The build is failing due to no fault of Nix.  Even rust-embedded/cross
has given up on fixing it, so there's no hope for us.
Fixes #1267
See also https://github.com/rust-embedded/cross/pull/440

Drop support for powerpc64-unknown-linux-gnu

---

CHANGELOG.md
src/unistd.rs
test/test_unistd.rs

this fixes #1204.
i know this at least works on linux, but i'm not super sure about other platforms - happy to add conditionals if it makes sense.

implement ttyname and ttyname_r

---

src/sys/statfs.rs

`CGROUP_SUPER_MAGIC` and `CGROUP2_SUPER_MAGIC` are not supported currently.
Signed-off-by: Kenta Tada <Kenta.Tada@sony.com>

Add FsType for cgroupfs

---

CHANGELOG.md
src/sys/socket/mod.rs

The commit https://github.com/nix-rust/nix/pull/1222 added the very
useful Ipv4PktInfo to allow `sendmsg` to define the origin of the ip.
Unfortunattely, it didn't add the struct to Android target devices as
well. This commit adds the `target_os = "android"` and `target_os =" ios"` checks on the same
place to allow the compilation to work for the following archs tested:
- `cross build --target aarch64-linux-android`
- `cross build --target x86_64-linux-android`
- `cross build --target armv7-linux-androideabi`
- `cross build --target aarch64-apple-ios`
- `cross build --target x86_64-apple-ios`

Expose IP_PKTINFO Control Message on Android and iOS

---

CHANGELOG.md
src/sys/mod.rs
src/sys/time.rs
src/sys/timerfd.rs
test/sys/mod.rs
test/sys/test_timerfd.rs

Hello,
I have encountered a situation where I needed to use timerfd in addition to other fd with nix implementation of epoll. 
Here is a basic implementation of this feature, I also added some documentation and tests.
Note: currently testing works by pausing for 1-3 seconds. Obviously it is pretty bad if we want tests to run quickly but that was my best idea at the time. Feel free to suggest any other way.
Thank you!

Adding an implementation for timerfd.

---

src/sys/stat.rs

fchmod should be fchmodat
Signed-off-by: ed neville <ed@s5h.net>

doc typo in fchmodat

---

test/sys/test_termios.rs
test/test_pty.rs

The pseudo-terminal device handling tests in some places make
tcgetattr(3C) and tcsetattr(3C) calls using the control/manager file
descriptor rather than the subordinate terminal descriptor.  This works
on some systems, but not all; others such as illumos (and presumably
Solaris) are more strict and require the termios requests be made
against the terminal descriptor only.

use subordinate terminal device for termios calls

---

CHANGELOG.md
Cargo.toml
src/lib.rs
src/sys/time.rs
src/time.rs
test/test.rs
test/test_time.rs

Picked up #1100 and added `clock_getcpuclockid` call as well. Credits to @kevinwern for the initial version.
https://www.man7.org/linux/man-pages/man2/clock_gettime.2.html
https://www.man7.org/linux/man-pages/man3/clock_getcpuclockid.3.html
Closes #1275

Added clock_gettime, clock_getres, clock_settime, clock_getcpuclockid

---

CHANGELOG.md
src/unistd.rs
test/sys/test_ptrace.rs
test/sys/test_uio.rs
test/sys/test_wait.rs
test/test_unistd.rs

Fix tests. No change in documentation.
Resolves #1030.
Don't forget to bump major version number to `0.19`.

Mark nix::unistd::fork as unsafe.

---

CHANGELOG.md
src/sys/ptrace/linux.rs

Closes #1249.  
I think @jabedude was working on this, but as there was no progress since May I went ahead and implemented it myself.
I'm not completely sure about the cfg gates. Could we enable the functions for more targets?
I'm also open for suggestions of better names for the new functions.

Add PTRACE_SYSEMU and PTRACE_SYSEMU_SINGLESTEP support

---

Cargo.toml
build.rs
src/errno.rs
src/errno_dragonfly.c

Dragonfly recently (in Dfly 5.8) added an `__errno_location()` function to make it easy to access the thread-local `errno` variable. This has been exposed in rust-libc as of 0.2.77. This PR uses that functionality instead of the locally compiled C language shim, which the PR removes. One issue is backwards compatibilty. It requires 0.2.77 libc and DragonFly 5.8. Not sure how to gracefully handle older DragonFly versions, although I'm also not sure doing so is worth it.

DragonFlyBSD: use __errno_location now provided by the libc crate

---

CHANGELOG.md
Cargo.toml
src/sys/socket/addr.rs
src/sys/socket/mod.rs
test/sys/test_socket.rs

This change depends on rust-lang/libc#1905 so can't be merged until that is merged and released.

Support vsock on Android as well as Linux.

---

src/sys/socket/mod.rs

The relevant bug was fixed in 11.3-RELEASE
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222039

Renable the ScmTimestamp test on FreeBSD i386

---

CHANGELOG.md
Cargo.toml
README.md

I'd like to get a new version of the crate released including #1301 so that I can get the vsock crate building on Android, and get both imported into the Android tree.

Release v0.19.0.

---

README.md

I couldn't find the build status of this repo for any BDSs very easily - I had to look through some issues. I thought this badge would be a nice addition.

add Cirrus CI badge to readme

---

CHANGELOG.md
src/sys/mman.rs
test/sys/test_mman.rs

Add wrapper for mremap

---

test/test.rs

test code breaks on fc333
```
$ cargo test
failures:
---- sys::test_socket::recvfrom::udp_offload::gro stdout ----
thread 'sys::test_socket::recvfrom::udp_offload::gro' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError("Extra junk after valid version: _64")', test/sys/test_socket.rs:292:13
```
this is due underscore in release string( arch/x86_64), which is not supported by semver.
```
$ uname -r
5.8.14-300.fc33.x86_64
```

update require_kernel_version string to handle "_" in version string

---

src/sys/socket/sockopt.rs

Without this commit, nix doesn't currently compile on OpenBSD. Some keepalive settings can be set globally, but not per-socket (see e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=970550 for some digging into this). Since it seems that NetBSD and DragonflyBSD have these settings, it makes more sense to only exclude them on OpenBSD rather than include them on (pretty much every) other operating systems.

KEEPCNT/KEEPINTVL aren't available on OpenBSD.

---

src/sys/socket/mod.rs
src/sys/time.rs

See individual commits.
This PR is an alternative to #1329.
@asomers

Suppress temporary libc deprecations

---

Cargo.toml

ref: https://blog.rust-lang.org/2020/03/15/docs-rs-opt-into-fewer-targets.html
Makes sense to build docs for all supported OSes (BSD, Redox) rather than completely empty docs for Windows :)

Add docs.rs target list

---

src/sys/socket/mod.rs
test/sys/test_socket.rs

There were two problems discovered with the `recvmmsg(2)` implementation
that this changeset attempts to fix:
1. As mentioned in nix-rust/issues/1325, `recvmmsg(2)` can return fewer
messages than requested, and
2. Passing the return value of `recvmmsg(2)` as the number of bytes in
the messages received is incorrect.
This changeset incorporates the proposed fix from nix-rust/issues/1325,
as well as passing the correct value (`mmsghdr.msg_len`) for the number
of bytes in a given message.

Fix recvmmsg(2) implementation

---

test/sys/test_aio_drop.rs

This test occasionally fails in Travis on x86_64-unknown-linux-gnu.  The
failure takes the form of the test executable receiving a random signal.
Sometimes SIGHUP, sometimes SIGKILL, etc.  I think this must be a bug in
glibc, even though I can't reproduce it in my development environment.
But it interferes with CI too much to leave enabled.

Disable test-aio-drop in GNU environments

---

test/sys/test_aio.rs
test/test_unistd.rs

These tests have recently begun to fail intermittently in CI.

Fix intermittency in some tests

---

src/unistd.rs

On Cirrus CI, this test would sometimes fail, probably due to pause
being awoken by SIGRT_1.  sigwait is a superior alternative to pause.
Fixes #1354

Fix intermittency in the doc test for alarm

---

.cirrus.yml
CHANGELOG.md
README.md
test/sys/test_aio.rs
test/test_unistd.rs

This will shortly be needed for Fuchsia support.

Raise MSRV to 1.40.0

---

CHANGELOG.md
src/sys/socket/mod.rs

Remove SockLevel

---

CHANGELOG.md
src/sys/mod.rs
src/sys/personality.rs

Adds a high level `Persona` bitflags enum, as well as `personality::get()` and `personality::set()` for interacting with `libc::personality()`.
Closes #1330.
See also https://github.com/rust-lang/libc/pull/1974.

feat(sys): High-level personality(2) wrappers

---

.cirrus.yml
CHANGELOG.md
Cargo.toml
README.md
src/errno.rs
src/features.rs
src/lib.rs
src/sys/signal.rs
src/sys/socket/addr.rs
src/unistd.rs
test/common/mod.rs
test/sys/mod.rs
test/sys/test_signal.rs
test/sys/test_socket.rs
test/test.rs
test/test_ptymaster_drop.rs
test/test_unistd.rs

This change adds support for the Fuchsia operating system to the nix
crate. Fuchsia developers have a use case for nix, particularly its safe
interfaces to the recvmsg(2) and sendmsg(2). Adding support requires:
* incrementing the libc dependency to 0.2.74
* conditionally not compiling nix functionality which depends on libc functionality
that does not exist for Fuchsia

Add fuchsia support

---

CHANGELOG.md
src/unistd.rs
test/test_unistd.rs

`getpeereid(3)` is not POSIX, but it's present on many BSD-derived Unices. It's also the standard mechanism on those OSes for retrieving socket peer credentials (compare `getsockopt` + `SO_PEERCRED` on Linux, which `nix` already supports).
Closes #1339.

feat(unistd): Add getpeereid(3)

---

src/fcntl.rs
test/test_fcntl.rs

When compiling the following code with nix `0.19.1` under FreeBSD 12.2:
```
use std::os::unix::io::AsRawFd;
fn main() {
let f = std::fs::File::create("/tmp/testfile").unwrap();
nix::fcntl::posix_fadvise(
f.as_raw_fd(),
0,
0,
nix::fcntl::PosixFadviseAdvice::POSIX_FADV_NOREUSE,
).unwrap();
}
```
I get the following error:
```
error[E0433]: failed to resolve: could not find `PosixFadviseAdvice` in `fcntl`
--> src/main.rs:10:21
|
10 |         nix::fcntl::PosixFadviseAdvice::POSIX_FADV_NOREUSE,
|                     ^^^^^^^^^^^^^^^^^^ could not find `PosixFadviseAdvice` in `fcntl`
error[E0425]: cannot find function `posix_fadvise` in module `nix::fcntl`
--> src/main.rs:6:17
|
6 |     nix::fcntl::posix_fadvise(
|                 ^^^^^^^^^^^^^ not found in `nix::fcntl`
error: aborting due to 2 …
```

Fix fcntl for FreeBSD platform

---

CHANGELOG.md
src/sys/socket/mod.rs

Add support for `SockAddr::Link` when receiving packets

---

CHANGELOG.md
Cargo.toml
src/sys/statfs.rs

Since rust-lang/libc is now using the correct data type on s390x (c_uint) for
statfs constants, the s390x exemptions in the statfs MAGIC definitions like
EXT4_SUPER_MAGIC can be removed.
Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>

Remove s390x exemptions from sys::statfs MAGIC constants

---

CHANGELOG.md
src/unistd.rs

Adds a `passwd` field to unistd::Group. The `gr_passwd` field exists on `libc::group` and wasn't exposed.
I didn't see tests for `from(libc:group)` for either `User` or `Password`. Let me know if there are other tests I should add!

Add a passwd field to Group

---

CHANGELOG.md
src/dir.rs
src/pty.rs
src/sys/signalfd.rs

Since they close their file descriptors on Drop, it's almost impossible
to use Clone without creating a double-close situation.
Also, check for EBADF in SignalFd::drop and Dir::drop.

Don't implement Clone on Dir, SignalFd, and PtyMaster

---

src/sys/wait.rs

libc 0.2.82 exposes status signals with macros generating safe functions

fix(unsafe): remove unnecessary unsafe

---

CHANGELOG.md
src/dir.rs
test/test_dir.rs

This is useful to allow returning an iterator based on a directory iterator
without needing a self-referential struct.

Dir: Implement `IntoIterator` for `Dir`

---

CHANGELOG.md
src/sys/timerfd.rs

This change closes the TimerFd file descriptor on drop. Note that the TimerFd will no longer be `Clone` or `Copy`. Since it has a destructor it can't be `Copy`, and if it were `Clone` you could end up trying to use a closed TimerFd, or double-closing the file descriptor.
Addresses #1379.

Close file descriptor on drop in TimerFd

---

CHANGELOG.md
src/pty.rs
test/test_pty.rs

After the child returns from a fork() of a multi-threaded process, it is
undefined behaviour to call non-async-signal-safe functions according to
POSIX.  Since forkpty() is implemented in terms of fork(), those
restrictions should apply to it too.
Fixes #1388

pty: Make forkpty() unsafe

---

.cirrus.yml

https://github.com/cirruslabs/cirrus-ci-docs/issues/741

During CI, use just 1 cpu for QEMU builds

---

CHANGELOG.md
src/sys/socket/mod.rs

libc removed it in version 0.2.87.
https://github.com/rust-lang/libc/pull/2079

Remove accept4 on Android arm

---

CHANGELOG.md
src/sys/socket/mod.rs

Apparently the Linux kernel can return smaller sizes when the value in
the last element of sockaddr_ll (`sll_addr`) is smaller than the
declared size of that field.

Allow sockaddr_ll size mismatch

---

test/sys/test_socket.rs

Temporarily disable test_vsock on QEMU arches

---

.cirrus.yml
Cargo.toml
src/dir.rs
src/errno.rs
src/fcntl.rs
src/features.rs
src/lib.rs
src/net/if_.rs
src/sys/ioctl/bsd.rs
src/sys/ioctl/mod.rs
src/sys/mod.rs
src/sys/socket/addr.rs
src/sys/socket/mod.rs
src/sys/socket/sockopt.rs
src/sys/termios.rs
src/unistd.rs
test/sys/test_signal.rs
test/test_dir.rs
test/test_pty.rs
test/test_unistd.rs

Adds support for the illumos target as well as improvements in the existing Solaris support.
Co-authored-by: Dominik Hassler <hadfl@omnios.org>
Co-authored-by: Joshua M. Clulow <josh@sysmgr.org>

illumos and Solaris support

---

test/sys/test_socket.rs

Starting from Linux 5.6, `VMADDR_CID_LOCAL` is supported to do local communication (loopback device).
Before Linux 5.6 it was called `VMADDR_CID_RESERVED` and was not supported, so we could expect an `EADDRNOTAVAIL`, but now this address is supported and handled by the 'vsock_loopback' kernel module loaded automatically if no other vsock transports are loaded.
Issue #1310
Issue #1403
Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>

Fix test_vsock failure on VMADDR_CID_LOCAL testing and re-enable it

---

src/unistd.rs

We have one UNIX group that contains most of our users whose size is
about 20 kB, so `Group::from_name` is failing with ERANGE.
The discussion on PR #864 suggests that 1 MB is a reasonable maximum -
it follows what FreeBSD's libc does. (glibc appears to have no maximum
on the _r function and will just double the buffer until malloc fails,
but that's not particularly Rusty.)

unistd: Increase maximum passwd/group buffer to 1MB

---

Cargo.toml
src/macros.rs
src/sys/socket/addr.rs
src/sys/socket/mod.rs

The homegrown macro was fine in 2016, but at some point it technically
became UB.  The memoffset crate does the same thing, but avoids UB when
using rustc 1.51.0 or later.
Fixes #1415

Use memoffset::offset_of instead of homegrown macro

---

CHANGELOG.md
src/sys/socket/mod.rs

Before this fix, the buffer that holds cmsgs may move due to the resize()
call. That causes msg_hdr pointing to invalid memory, which ends up
breaking the sendmmsg() call, resulting in EINVAL.
This change fixes it by avoiding re-allocating the buffers.

Fix corrupted sendmmsg() call

---

CHANGELOG.md
Cargo.toml
src/sys/socket/mod.rs
src/sys/socket/sockopt.rs
test/sys/test_socket.rs

This adds support of linux TIMESTAMPNS.
The code is mostly copied paste from https://github.com/nix-rust/nix/pull/663

Support TIMESTAMPNS

---

src/sys/socket/mod.rs

This fixed doc test issue here: https://docs.rs/nix/0.20.0/nix/sys/socket/enum.ControlMessageOwned.html#variant.ScmTimestamp

Fix timestamp doc

---

CHANGELOG.md
src/unistd.rs

Make some integer wrapper methods `const fn`.
* `Uid::from_raw`
* `Uid::as_raw`
* `Uid::is_root`
* `Gid::from_raw`
* `Gid::as_raw`
* `Pid::from_raw`
* `Pid::as_raw`
(Changelog mentions rust 1.40.0 as minimum required version which seems to compile this fine (using 1.40.0 from rustup))

constify from_raw and as_raw for Uid, Gid and Pid and Uid::is_root

---

CHANGELOG.md
README.md
src/kmod.rs
src/mqueue.rs
src/net/if_.rs
src/poll.rs
src/pty.rs
src/sched.rs
src/sys/aio.rs
src/sys/inotify.rs
src/sys/ioctl/mod.rs
src/sys/mman.rs
src/sys/pthread.rs
src/sys/select.rs
src/sys/sendfile.rs
src/sys/signal.rs
src/sys/signalfd.rs
src/sys/socket/addr.rs
src/sys/socket/mod.rs
src/sys/stat.rs
src/sys/statvfs.rs
src/sys/sysinfo.rs
src/sys/termios.rs
src/sys/timerfd.rs
src/sys/uio.rs
src/sys/wait.rs
src/unistd.rs

All of the `http://` links in the repository are also available as `https://, and have been updated.
The sole exception to this trivially rewrite is a dead-link to `http://rust-lang.org/COPYRIGHT`, which has been replaced with `https://www.rust-lang.org/policies/licenses`.

Rewrite links to use https:// instead of http://

---

.cirrus.yml

A regression in rustup has broken that tool on FreeBSD.  Set
RUSTUP_IO_THREADS=1 as a workaround.
https://github.com/rust-lang/rustup/issues/2774

Workaround Rustup bug 2774

---

src/fcntl.rs

Without this, the `lstat` call ignores the `dirfd` and checks the wrong file. I wanted to write a unit test for this but I'm not sure how to do it reliably, AFAIK the maximum path size can vary between filesystems.

Use fstatat to check long path sizes in fcntl::readlinkat

---

CHANGELOG.md
src/sys/sendfile.rs
test/test_sendfile.rs

`sendfile64` is a Linux-specific call with a wider type for the `offset` argument than `sendfile`.
This is largely a copy of the existing `sendfile` function and associated test.

Add sendfile64

---

src/sys/signal.rs

Beginning with 1.41.0, Rust considers it UB to zero-initialize a
function pointer, even if you try to hide it behind `mem::MaybeUninit`.
Suppress this warning to fix the build until we come up with a better
permanent solution.
Issue #1441

Suppress a build warning on Fuchsia

---

CHANGELOG.md
Cargo.toml
src/mount.rs

MS_LAZYTIME (since Linux 4.0) reduces on-disk updates of inode
timestamps (atime, mtime, ctime) by maintaining these changes only in memory.
MS_LAZYTIME is available from `libc` v0.2.95.
Signed-off-by: Manabu Sugimoto <Manabu.Sugimoto@sony.com>

Add MS_LAZYTIME flag

---

src/errno.rs
src/fcntl.rs
src/sys/aio.rs
src/sys/ptrace/bsd.rs
src/sys/select.rs
src/sys/socket/mod.rs
src/time.rs
src/unistd.rs
test/sys/test_ioctl.rs
test/sys/test_signal.rs
test/sys/test_socket.rs
test/sys/test_sockopt.rs
test/sys/test_uio.rs
test/sys/test_wait.rs
test/test_net.rs
test/test_stat.rs
test/test_unistd.rs

* Fix race conditions in the tests.  Two tests were grabbing a mutex but
immediately dropping it.  Thank you, Clippy.
* Remove vestigial Windows support.  Remove some code added to support
Windows in 2015.  Nix is no longer intended to ever run on Windows.
* Various other minor Clippy lints.

misc Clippy cleanup

---

src/sched.rs

Add a note in the documentation for sched::clone to point out that the
stack pointer does not neet to be a reference to the highest address of
the stack.
Users who simply read the manpages for clone(2) might assume that they
will need to use unsafe pointer arithmetics in order to create a
reference to the highest address of their buffer, rather than providing
their buffer directly.

Add documentation for sched::clone

---

CHANGELOG.md
src/errno.rs

* Add Errno::EOPNOTSUPP to FreeBSD, where it is missing
* Errno aliases are now associated consts of the Errno type
* Remove Errno consts from platforms where they aren't defined

Fix several problems with Errno aliases

---

Cargo.toml

A new libc release with the MNT_ fixes was released.

Bump libc to 0.2.98

---

CHANGELOG.md
src/fcntl.rs
test/test_fcntl.rs

Hi, please find my PR for adding the linux-specific `renameat2` syscall.  It's largely similar to `renameat`, with an additional flags parameter:
The flags are:
* RENAME_REPLACE - performs an atomic swap.
* RENAME_NOREPLACE - returns EEXIST if the target already exists.
* RENAME_WHITEOUT - specific to overly/union filesystems, and I haven't added a test-case for this one.
PLEASE NOTE: It looks like my formatter has made numerous changes.  If you have a preferred formatting config then please let me know, and I can push up changes consistent with the accepted style.
I'm not all that experienced with rust, and this is my first time looking at the nix project, so I'm more than happy to receive guidance on improving my submission.
Cheers!

Added support for renameat2 on linux

---

CHANGELOG.md
src/sys/socket/mod.rs
src/sys/socket/sockopt.rs
test/sys/test_socket.rs

This PR implements support of RXQ_OVFL flag and parsing ControlMessage
to get the packet drop counter of UDP socket.

Support SO_RXQ_OVFL socket option (android/fuchsia/linux)

---

src/unistd.rs

Replaces `println!`  with raw `libc::write`. `println!` isn't guaranteed
to be async-signal-safe, and almost certainly *isn't* due to internal
buffering and locking.
Adds a call to `libc::_exit` in the child arm, so that it doesn't fall
through and start executing the parent code.
Adds a call to `waitpid` in the parent arm, to clean up the child
process.
Removes the `no_run` directive, so that it's run in the doc tests.

Fix fork test and enable doc test

---

.gitignore
Cargo.toml

* Switch Cargo from an exclude list to an include list.  The exclude list had gotten out-of-date.
* Add more file types to .gitignore

Slim down the size of the built package

---

CHANGELOG.md
src/errno.rs

Add more errno definitions for better backwards compat with 0.21.0

---

CONTRIBUTING.md

Guess the label prefixes should be rendered bold and not with literal stars.

Fix CONTRIBUTING.md formating

---

CHANGELOG.md
src/sys/socket/sockopt.rs

`IPV6_V6ONLY` allows the user to select between dual-stack and IPv6-only sockets.
Platform support seems to be good; all platforms with IPv6 support seem to have this sockopt.

Add the IPV6_V6ONLY sockopt

---

CHANGELOG.md
src/sys/time.rs

Previously, there was no way to create a `TimeSpec` in a `const` context because all creation was through traits. This adds two utility functions to create a `const TimeSpec` from a `libc::timespec` or an `std::time::Duration`.
An alternative approach would be to make the inner `timespec` field `pub`, which would not require any additional functions but would expose some (potentially unwanted) implementation details.

Enable creating a const TimeSpec

---

CHANGELOG.md
src/sys/pthread.rs
test/sys/test_pthread.rs

This adds `pthread_kill`, following the design of `killpg`.
What do you think?

Add pthread_kill

---

CHANGELOG.md
src/unistd.rs
test/test_unistd.rs

Add `From<User> for libc::passwd` trait implementation to convert a `User` into a `libc::passwd`
Implementation consumes the `User` struct, giving ownership over the internal members to the `libc::passwd` struct
Exposes the `User::gecos` field to 64-bit Android builds, since `libc::passwd::pw_gecos` is supported on those builds

unistd: Add conversion from User to libc::passwd

---

CHANGELOG.md
src/sys/mod.rs

Androids bionic [supports](https://android.googlesource.com/platform/bionic/+/d1ad4f6/libc/include/sys/eventfd.h) `eventfd`. The `libc` crate also exposes [`eventfd`](https://github.com/rust-lang/libc/blob/36a6a8e254db89cd31d178b4ba102055ceabf9a8/src/unix/linux_like/android/mod.rs#L2648) for target `android`. 
Extend the conditional compilation check to include the target_os "android".
Fixes #1480

Include `sys::eventfd` for target_os = "android"

---

CHANGELOG.md
src/sys/stat.rs
test/test_stat.rs

This introduces a new `mknodat` helper.
Ref: https://pubs.opengroup.org/onlinepubs/9699919799/functions/mknod.html

sys/stat: add a safe wrapper for mknodat(2)

---

CHANGELOG.md
src/errno.rs
src/fcntl.rs
src/sys/aio.rs
src/sys/epoll.rs
src/sys/event.rs
src/sys/mman.rs
src/sys/ptrace/bsd.rs
src/sys/ptrace/linux.rs
src/sys/quota.rs
src/sys/reboot.rs
src/sys/signal.rs
src/sys/socket/addr.rs
src/sys/socket/mod.rs
src/sys/termios.rs
src/sys/timerfd.rs
src/unistd.rs

Since libc may add new variants at any time, Nix's consumers should not
use exhaustive match patterns.
Fixes #1182

Mark most C-derived enums as non_exhaustive

---

CHANGELOG.md
src/errno.rs
src/features.rs
src/mount/bsd.rs
src/mqueue.rs
src/poll.rs
src/sched.rs
src/sys/signal.rs
src/sys/socket/addr.rs
src/sys/socket/mod.rs
src/sys/stat.rs
src/sys/time.rs
src/sys/timerfd.rs
src/time.rs

Constify most functions that can be constified.  The exceptions are
mostly accessors for structs that have no const constructor.

Constify many functions

---

CHANGELOG.md
src/sys/mod.rs
src/sys/resource.rs
test/test.rs
test/test_resource.rs

This PR is based on the previous PR https://github.com/nix-rust/nix/pull/1190, which has not been updated for a very long time.
I have fixed the segfault and compilation error of the original PR and rebased the changes to the latest master branch.
Please let me know if anything need to been changed.

Add getrlimit and setrlimit

---

CHANGELOG.md
Cargo.toml
src/sys/termios.rs

Related to rust-lang/libc#2327

Remove some actually unsupported termios iflags on redox

---

CHANGELOG.md
src/sys/ptrace/linux.rs
test/sys/test_ptrace.rs

I've based the test on `fn test_ptrace_cont`. Removed some parts, but not 100% sure what's the proper way of testing in nix context.
From ptrace-man page:
```
PTRACE_INTERRUPT (since Linux 3.4)
Stop a tracee.  If the tracee is running or sleeping in
kernel space and PTRACE_SYSCALL is in effect, the system
call is interrupted and syscall-exit-stop is reported.
(The interrupted system call is restarted when the tracee
is restarted.)  If the tracee was already stopped by a
signal and PTRACE_LISTEN was sent to it, the tracee stops
with PTRACE_EVENT_STOP and WSTOPSIG(status) returns the
stop signal.  If any other ptrace-stop is generated at the
same time (for example, if a signal is sent to the
tracee), this ptrace-stop happens.  If none of the above
applies (for example, if the tracee is …
```

Add PTRACE_INTERRUPT call as `ptrace::interrupt(pid)` 

---

src/sys/signal.rs

Replace some mem::transmute calls in signal.rs with pointer casts

---

CHANGELOG.md
src/macros.rs
src/sys/event.rs
src/sys/signal.rs
src/sys/termios.rs

This saves code in several separate places that need to do this
separately.  At the same time, remove a few uses of mem::transmute that
were implementing TryFrom or similar functionality.
Issue #373

Optionally implement TryFrom in libc_enum!

---

CHANGELOG.md
src/sys/socket/mod.rs
src/sys/socket/sockopt.rs
test/sys/test_sockopt.rs

On FreeBSD and its derivatives, this socket option gets the credentials
of the connected peer.

Add support for LOCAL_PEER_CRED

---

.cirrus.yml
CHANGELOG.md
Cargo.toml
README.md
src/errno.rs
src/macros.rs
src/sys/signal.rs
src/sys/socket/addr.rs

Bitflags raised its MSRV in a minor version, forcing all consumers to follow suit.
Fixes #1491

Fix the build with bitflags-1.3.0 and newer

---

src/sys/signalfd.rs

There was a better case for using it before mem::uninitialized was
available, but not great.  Even before then, mem::zeroed could've been
used instead.
Issue #373

Don't use mem::transmute in SignalFd

---

src/sys/socket/mod.rs
test/sys/test_socket.rs

Relax assertions in sockaddr_storage_to_addr to match the documentation.

---

CHANGELOG.md
src/sys/socket/sockopt.rs

the original PR #1410 was stalled for a while
let's make it happen.
this should closes #1410 and #938

add libc::IP6T_SO_ORIGINAL_DST to socket opt

---

CHANGELOG.md
src/sys/ptrace/linux.rs

Adds the `PTRACE_EVENT_STOP` variant to the `ptrace::Event` enum.
Smaller part of #1279
Closes #1334

Add `PTRACE_EVENT_STOP` enum variant

---

CHANGELOG.md
src/ifaddrs.rs
src/sys/socket/addr.rs

I also noticed the `SockAddr/InetAddr::to_str` functions were entirely redundant - `ToString` exists for that, & has a blanket impl on `T: Display`.

Expose SockAddr::from_raw_sockaddr

---

test/common/mod.rs
test/sys/test_ptrace.rs
test/sys/test_sockopt.rs
test/sys/test_uio.rs
test/sys/test_wait.rs
test/test_kmod/mod.rs
test/test_unistd.rs

Currently when a test is skipped due to missing capabilities, a nondescript message is logged to stderr.
Improve that message to include both the function name and missing capability, making it possible to inspect stderr to see which capabilities are missing, and which tests they impact.

Print function name and missing capability when skipping tests

---

src/env.rs
src/lib.rs
src/mount/bsd.rs
src/mount/mod.rs
src/sched.rs
src/sys/aio.rs
src/sys/mod.rs
src/sys/signal.rs

Switch from allow(missing_docs) to deny(missing_docs), which should
gradually help us moving forward.  Also, add a few missing docs, such as
for sched and aio.

More rust docs

---

.cirrus.yml
CHANGELOG.md
Cargo.toml
src/lib.rs
src/sys/aio.rs
src/sys/mod.rs
src/sys/pthread.rs
src/sys/resource.rs
src/sys/select.rs
src/sys/sendfile.rs
src/sys/signal.rs
src/sys/socket/mod.rs
src/sys/stat.rs
src/sys/statfs.rs
src/sys/uio.rs
src/sys/utsname.rs
src/sys/wait.rs

Also, test rustdoc in CI, and demote missing_docs from a deny to a
warning (but still deny it in CI).

Document more things

---

.cirrus.yml

* Define the build and test scripts once instead of repeating them
* Don't use cross with OSX.  We no longer need it.

DRY in the CI config

---

CHANGELOG.md
src/sys/socket/mod.rs
src/sys/socket/sockopt.rs
test/sys/test_socket.rs

This pull request adds support for setting the `IP_RECVERR` (and corresponding `IPV6_RECVERR`) sockopt, and then decoding the resulting control messages from `recvmsg()`.  It is a Linux-specific API.
This PR extends #1161 by:
* Making the address associated with a `IpvXRecvErr` control message optional (`recvmsg` documentation claims it is not provided for some kinds of error), per @WGH-.
* Adding basic tests for both IPv4 and IPv6 (blat a UDP packet at a hopefully-unoccupied port on localhost and observe ICMP port unreachable).
* Adding a Changelog entry.
I added some trivial doc comments on the `ControlMessageOwned` variants, but I'm not sure exactly what documentation you had in mind earlier on #1161.

Add support for IP_RECVERR

---

test/sys/test_socket.rs

Starting with linux kernel 4.9, the crypto interface changed slightly such that the authentication tag memory is only needed in the output buffer for encryption and in the input buffer for decryption. Thus, we have fewer bytes to read than the buffer size. Do not block on read.
alternatively,  we can adjust the decrypted buffer size based on kernel version ( ">= 4.9") to not include auth_size .
```
if kernel_version >= "4.9":
let mut decrypted = vec![0u8; payload_len + (assoc_size as usize) ];
```
before 
```
test sys::test_socket::test_af_alg_aead ... test sys::test_socket::test_af_alg_aead has been running for over 60 seconds
```
after
```
test sys::test_socket::test_af_alg_aead ... ok
```

test_af_alg_aead waits indefinitely

---

CHANGELOG.md
src/poll.rs
test/test_poll.rs

Implement the trait on PollFd, providing an `as_raw_fd()` accessor to
get the RawFd associated with the PollFd.
Subsumes #1147, #1286.  Closes #1146.
Test: `cargo test --test test test_pollfd_fd`

Implement AsRawFd for PollFd

---

CHANGELOG.md
src/sys/socket/sockopt.rs
test/sys/test_sockopt.rs

Found myself in a situation where I needed to advertise a specific MSS. Thought this crate is the appropriate place for this feature (especially since the `TCP_MAXSEG` const was exposed through it before), so here goes.
Actual change is of course tiny but it comes with a test. Happy to make changes, especially since I need to do more research on which platforms this works.

Support `TCP_MAXSEG` TCP Maximum Segment Size socket options

---

src/errno.rs

This makes the success case a single `cmpl $-1, %eax` followed with a non-taken conditional jump, instead of the current `callq` which is always taken.
I have not benchmarked the difference, but it is an obvious improvement.

Make Errno::result() inline
